{dede:field name='keywords'}女贼的诱惑,女贼的诱惑迅{/dede:field}
{dede:field name='description'}最新电影《女贼的诱惑》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《女贼的诱惑》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋{/dede:field}
{dede:field name='title'}女贼的诱惑电影迅雷高清下载,女贼的诱惑高清下载在线观看 - 大陆 - a67手机电影网{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}孙建江 </li>
<li class="info_dq">地区：
大陆{/dede:field}
{dede:field name='yanyuan'}何蕴 依王越 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《女贼的诱惑》在线观看" title="《女贼的诱惑》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《女贼的诱惑》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">一个骗子团伙，在各地流窜作案。在一个城市作案的时候，偶然认识了一个女孩儿，这个女孩要拜骗子团伙老大为师，用身世打动了男人，跟骗子团伙骗取了很多社会人士的钱财，如碰瓷儿的，好色的，奸商等。得知这个城市的首富是娟姐，然后骗子团伙设下了个局，利用了这个女孩儿，最后骗取了城市首富的一笔钱财。快过年了，所以团伙要散伙，当骗子老大利用完女孩儿，预将她抛弃之时，却发现自己爱上了她。可是，万万没想到的事是，这个女人是警察，卧底到骗子团伙.</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语</li>
<li class="yanyuan">主演：
<a href="/search/%E4%BD%95%E8%95%B4" target="_blank">何蕴</a> <a href="/search/%E4%BE%9D%E7%8E%8B%E8%B6%8A" target="_blank">依王越</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《女贼的诱惑》在线观看" title="《女贼的诱惑》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《女贼的诱惑》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145913440915420-13MN.jpg{/dede:field}
