{dede:field name='keywords'}检察官外传/检师外传,检察{/dede:field}
{dede:field name='description'}最新电影《检察官外传/检师外传》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《检察官外传/检师外传》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a6{/dede:field}
{dede:field name='title'}检察官外传/检师外传电影迅雷高清下载,检察官外传/检师外传高清下载在线观看 - 日韩 - a67手机电影网{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}李日炯 </li>
<li class="info_dq">地区：
日韩{/dede:field}
{dede:field name='yanyuan'}黄政民 姜东元 李成民 朴圣雄 申素率 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《检察官外传/检师外传》在线观看" title="《检察官外传/检师外传》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《检察官外传/检师外传》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">投资发行公司Showbox透露，韩国演员黄政民将主演李日炯导演的新片《检察官外传》，该片是由《群盗：民乱的时代》的“月狂”制作公司和“男子汉电影”公司共同制作。 　　《检察官外传》讲述的是背负着杀人犯罪名冤枉入狱的检察官，聚集了一群有才能的犯罪者，对黑社会组织进行复仇的故事。黄政民在片中饰演男主人公。 　　今年年末黄政民主演的尹济均导演新片《国际市场》即将上映，而黄政民目前正在拍摄罗宏镇导演的《谷城》，之后还将主演李石勋导演的《喜马拉雅》，之后才会拍摄《检察官外传》。2014年末到2015年的日程都排满了，也印证了黄政民在韩国电影界的超高人气。 　　《检察官外传》预计会在2015年上映。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}韩语</li>
<li class="yanyuan">主演：
<a href="/tag/1161/" target="_blank">黄政民</a> <a href="/tag/7087/" target="_blank">姜东元</a> <a href="/search/%E6%9D%8E%E6%88%90%E6%B0%91" target="_blank">李成民</a> <a href="/search/%E6%9C%B4%E5%9C%A3%E9%9B%84" target="_blank">朴圣雄</a> <a href="/search/%E7%94%B3%E7%B4%A0%E7%8E%87" target="_blank">申素率</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《检察官外传/检师外传》在线观看" title="《检察官外传/检师外传》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《检察官外传/检师外传》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}日韩{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/14591344S42040-495Z.jpg{/dede:field}
