{dede:field name='keywords'}埃尔塞差点改变世界的人{/dede:field}
{dede:field name='description'}最新电影《埃尔塞差点改变世界的人》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《埃尔塞差点改变世界的人》完整版迅雷高清下载，以及高清在线播放，轻轻一点{/dede:field}
{dede:field name='title'}埃尔塞差点改变世界的人{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}奥利弗·西斯贝格 </li>
<li class="info_dq">地区：
欧美{/dede:field}
{dede:field name='yanyuan'}卡塔琳娜·舒特勒 伯格哈特·克莱斯纳 菲力克斯·伊特纳 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《埃尔塞差点改变世界的人》在线观看" title="《埃尔塞差点改变世界的人》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《埃尔塞差点改变世界的人》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}7.0{/dede:field}
{dede:field name='introduction'}《埃尔塞: 将近改变世界的人》讲述的是刺杀希特勒事件，但影片里的史实比《行动目标希特勒》要早几年。1939年。希特勒差一点被一个名叫埃尔塞的木匠干掉。那一年，希特勒的权力正在逐渐迈向顶峰，当大多数人都在狂热崇拜之时，埃尔塞成了少数几个的正义斗士。在精密的计划之下，他在希特勒演讲的讲台附近设置一个定时炸弹。可惜的是，希特勒的演讲结束得太早，炸弹引爆时希特勒已经不在现场。埃尔塞在当年11月遭到了纳粹的逮捕，遭处决。影片讲述了一段惊心动魄的故事，本土演员的演出保持了原汁原味。{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}英语</li>
<li class="yanyuan">主演：
<a href="/search/%E5%8D%A1%E5%A1%94%E7%90%B3%E5%A8%9C%C2%B7%E8%88%92%E7%89%B9%E5%8B%92" target="_blank">卡塔琳娜·舒特勒</a> <a href="/search/%E4%BC%AF%E6%A0%BC%E5%93%88%E7%89%B9%C2%B7%E5%85%8B%E8%8E%B1%E6%96%AF%E7%BA%B3" target="_blank">伯格哈特·克莱斯纳</a> <a href="/search/%E8%8F%B2%E5%8A%9B%E5%85%8B%E6%96%AF%C2%B7%E4%BC%8A%E7%89%B9%E7%BA%B3" target="_blank">菲力克斯·伊特纳</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《埃尔塞差点改变世界的人》在线观看" title="《埃尔塞差点改变世界的人》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《埃尔塞差点改变世界的人》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}欧美{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145913Q39D440-232426.jpg{/dede:field}
