{dede:field name='keywords'}校卫,校卫迅雷下载,校卫高{/dede:field}
{dede:field name='description'}最新电影《校卫》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《校卫》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共同享受下{/dede:field}
{dede:field name='title'}校卫{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='daoyan'}图郎{/dede:field}
{dede:field name='yanyuan'}刘哲 孙凡{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">徐强进入一所校风极差的学校维持纪律，校主任女儿高玲玲在校期间拉帮结派，勾结保安聚众赌博，欺负女同学，徐强制止这些的时候遭到陷害，受到处分的徐强因此泄气，最终在校长..</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160322/145V3342400O0-2L448.jpg{/dede:field}
