<?php
$z[0]=Array("field","全家挤一块\\麻烦满屋第一",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《全家挤一块\\麻烦满屋第一季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《全家挤一块\\麻烦满屋第一季》电视剧全集迅雷高清下载，以及高清在线播放，轻",77,366);
$z[1][4]['name']="description";
$z[2]=Array("field","全家挤一块\\麻烦满屋第一季",368,443);
$z[2][4]['name']="title";
$z[3]=Array("field","",445,484);
$z[3][4]['name']="writer";
$z[4]=Array("field","",486,525);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",527,568);
$z[5][4]['name']="time";
$z[6]=Array("field","詹姆斯·伯罗斯",570,629);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","嘉莉·崔普雷斯顿 帕特里克·沃伯顿 米兰达·卡斯格拉夫",631,745);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",747,791);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">由《热力克利夫兰 Hot In Cleveland》团队Suzanne Martinand和Hazy Mills打造的多镜头喜剧。讲述Mike和Martina为了抚养儿女，过了20年的无性无酒的生活后，终于可以投身这花花世界做一对花花蝴蝶。但是意 想不到的是，两个的女儿突然搬回家里住。更不幸的是，Mike的父母也要搬过来说要颐享天年。本来空荡的家又挤满了人。 　　Patrick Warburton扮演丈夫Mike Gunn﹑Carrie Preston扮演妻子 Martina Gunn﹑Miranda Cosgrove扮演小女儿Shea, 天体物理学博士，想成为宇航员，有点不善社交﹑Mia Serafino扮演大女儿Stella，是一名有魅力但演艺事业不顺的演员。</span>",793,1651);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1653,1694);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",1696,1740);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","美剧",1742,1785);
$z[12][4]['name']="area";
$z[13]=Array("field","",1787,1827);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914NS45560-131054.jpg",1829,1924);
$z[14][4]['name']="litpic";

?>