{dede:field name='keywords'}雪国列车/最后的列车/末世{/dede:field}
{dede:field name='description'}最新电影《雪国列车/最后的列车/末世列》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《雪国列车/最后的列车/末世列》完整版迅雷高清下载，以及高清在线播放，轻{/dede:field}
{dede:field name='title'}雪国列车/最后的列车/末世列{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}内详 </li>
<li class="info_dq">地区：
日韩{/dede:field}
{dede:field name='yanyuan'}奥克塔维亚·斯宾瑟 约翰·赫特 卢克·帕斯夸尼洛 艾丽森·皮尔 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《雪国列车/最后的列车/末世列》在线观看" title="《雪国列车/最后的列车/末世列》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《雪国列车/最后的列车/末世列》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}5.5{/dede:field}
{dede:field name='introduction'}{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}韩语</li>
<li class="yanyuan">主演：
<a href="/search/%E5%A5%A5%E5%85%8B%E5%A1%94%E7%BB%B4%E4%BA%9A%C2%B7%E6%96%AF%E5%AE%BE%E7%91%9F" target="_blank">奥克塔维亚·斯宾瑟</a> <a href="/tag/2607/" target="_blank">约翰·赫特</a> <a href="/search/%E5%8D%A2%E5%85%8B%C2%B7%E5%B8%95%E6%96%AF%E5%A4%B8%E5%B0%BC%E6%B4%9B" target="_blank">卢克·帕斯夸尼洛</a> <a href="/search/%E8%89%BE%E4%B8%BD%E6%A3%AE%C2%B7%E7%9A%AE%E5%B0%94" target="_blank">艾丽森·皮尔</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《雪国列车/最后的列车/末世列》在线观看" title="《雪国列车/最后的列车/末世列》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《雪国列车/最后的列车/末世列》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}日韩{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145913QE62Z-1452M.jpg{/dede:field}
