<?php
$z[0]=Array("field","阴阳诡捕之黄妖迷情,阴阳",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《阴阳诡捕之黄妖迷情》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《阴阳诡捕之黄妖迷情》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","阴阳诡捕之黄妖迷情",366,431);
$z[2][4]['name']="title";
$z[3]=Array("field","",433,472);
$z[3][4]['name']="writer";
$z[4]=Array("field","",474,513);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",515,556);
$z[5][4]['name']="time";
$z[6]=Array("field","李巨涛 </li>\r\n<li class=\"info_dq\">地区：\r\n大陆",558,651);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","杨玥 宫海滨",653,709);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","3.2",711,754);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">上世纪30年代，留洋归国的北宫琉璃不顾家人反对毅然加入警局，与警队队长林豹成为搭档，携手维护一方平安。一日，一桩诡异的凶杀案打破了往日的宁静，看似遭人毒手惨死的富贾.</span>",756,1161);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1163,1204);
$z[10][4]['name']="download";
$z[11]=Array("field","国语",1206,1250);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","大陆",1252,1295);
$z[12][4]['name']="area";
$z[13]=Array("field","",1297,1337);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914C0U4430-93c4.jpg",1339,1432);
$z[14][4]['name']="litpic";

?>