
<field:chuzur itemname="出租人" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="16" page="">
</field:chuzur>

<field:time itemname="出租时间" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="16" page="">
</field:time>

<field:price itemname="价格" autofield="1" notsend="0" type="float" isnull="true" islist="0" default="1000"  maxlength="16" page="">
</field:price>
