<?php
$z[0]=Array("field","掷地有声第一季,掷地有声",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《掷地有声第一季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《掷地有声第一季》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","掷地有声第一季",366,425);
$z[2][4]['name']="title";
$z[3]=Array("field","",427,466);
$z[3][4]['name']="writer";
$z[4]=Array("field","",468,507);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",509,550);
$z[5][4]['name']="time";
$z[6]=Array("field","James LaRosa",552,603);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","Robert Christopher Riley Kimberly Elise",605,684);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",686,730);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;\">Ahsha海耶斯进入的野生世界职业篮球当她尝试的精英洛杉矶魔鬼女孩舞蹈团队斯隆对她母亲的愿望,前舞者。</span>",732,1020);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1022,1063);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",1065,1109);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","美剧",1111,1154);
$z[12][4]['name']="area";
$z[13]=Array("field","",1156,1196);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914N4344630-194325.jpg",1198,1294);
$z[14][4]['name']="litpic";

?>