{dede:field name='keywords'}功夫熊猫3,功夫熊猫3迅雷{/dede:field}
{dede:field name='description'}最新电影《功夫熊猫3》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《功夫熊猫3》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共{/dede:field}
{dede:field name='title'}功夫熊猫3{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}吕寅荣 亚历山德罗·卡罗尼 </li>
<li class="info_dq">地区：
大陆{/dede:field}
{dede:field name='yanyuan'}杰克·布莱克 布莱恩·科兰斯顿 达斯汀·霍夫曼 安吉丽娜·朱莉 J·K·西蒙斯{/dede:field}
{dede:field name='pingfen'}7.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">在新一集故事里，与阿宝失散已久的生父突然现身，重逢的父子二人一起来到了一片不为人知的熊猫乐土。在这里，阿宝遇到了很多可爱有趣的熊猫同类。当拥有神秘力量的大反派“绿眼牛”企图横扫神州大地，残害所有功夫高手时，阿宝必须迎难而上，把那些热衷享乐、笨手笨脚的熊猫村民训练成一班所向披靡的功夫熊猫！</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914Bb15160-3T08.jpg{/dede:field}
