<?php
$z[0]=Array("field","功夫熊猫3,功夫熊猫3迅雷",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《功夫熊猫3》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《功夫熊猫3》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共",76,365);
$z[1][4]['name']="description";
$z[2]=Array("field","功夫熊猫3",367,418);
$z[2][4]['name']="title";
$z[3]=Array("field","",420,459);
$z[3][4]['name']="writer";
$z[4]=Array("field","",461,500);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",502,543);
$z[5][4]['name']="time";
$z[6]=Array("field","吕寅荣 亚历山德罗·卡罗尼 </li>\r\n<li class=\"info_dq\">地区：\r\n大陆",545,665);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","杰克·布莱克 布莱恩·科兰斯顿 达斯汀·霍夫曼 安吉丽娜·朱莉 J·K·西蒙斯",667,806);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","7.0",808,851);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;\">在新一集故事里，与阿宝失散已久的生父突然现身，重逢的父子二人一起来到了一片不为人知的熊猫乐土。在这里，阿宝遇到了很多可爱有趣的熊猫同类。当拥有神秘力量的大反派“绿眼牛”企图横扫神州大地，残害所有功夫高手时，阿宝必须迎难而上，把那些热衷享乐、笨手笨脚的熊猫村民训练成一班所向披靡的功夫熊猫！</span>",853,1432);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1434,1475);
$z[10][4]['name']="download";
$z[11]=Array("field","国语",1477,1521);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","大陆",1523,1566);
$z[12][4]['name']="area";
$z[13]=Array("field","",1568,1608);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914Bb15160-3T08.jpg",1610,1703);
$z[14][4]['name']="litpic";

?>