<?php
$z[0]=Array("field","双叶庄的朋友,双叶庄的朋",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《双叶庄的朋友》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《双叶庄的朋友》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","双叶庄的朋友",366,422);
$z[2][4]['name']="title";
$z[3]=Array("field","",424,463);
$z[3][4]['name']="writer";
$z[4]=Array("field","",465,504);
$z[4][4]['name']="source";
$z[5]=Array("field","10.0",506,550);
$z[5][4]['name']="pingfen";
$z[6]=Array("field","平松惠美子",552,606);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","市原隼人 臼田麻美 中村伦也 阳月华",608,696);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","2016",698,739);
$z[8][4]['name']="time";
$z[9]=Array("field","日语",741,785);
$z[9][4]['name']="yuyan";
$z[10]=Array("field","日韩",787,830);
$z[10][4]['name']="area";
$z[11]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">原舞台导演川村正治和他的妻子美江搬到了双叶庄居住。有一天，川村看到了26年前也住在这里的画家仓田的幻影，两人相似的境遇使他们交谈的很愉快……直到川村看到了无法相信的场景，而这些幻象是否是真实发生过的呢？令人惊讶的事实慢慢清晰了起来。</span>",832,1338);
$z[11][4]['name']="introduction";
$z[12]=Array("field","",1340,1381);
$z[12][4]['name']="download";
$z[13]=Array("field","",1383,1423);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V3342B4230-2b157.jpg",1425,1519);
$z[14][4]['name']="litpic";

?>