<?php
$z[0]=Array("field","戈德堡一家/金色年代第三",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《戈德堡一家/金色年代第三季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《戈德堡一家/金色年代第三季》电视剧全集迅雷高清下载，以及高清在线播放，轻",77,366);
$z[1][4]['name']="description";
$z[2]=Array("field","戈德堡一家/金色年代第三季",368,443);
$z[2][4]['name']="title";
$z[3]=Array("field","",445,484);
$z[3][4]['name']="writer";
$z[4]=Array("field","",486,525);
$z[4][4]['name']="source";
$z[5]=Array("field","2015",527,568);
$z[5][4]['name']="time";
$z[6]=Array("field","赛斯·戈登",570,623);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","温迪·麦丽登·康薇 杰夫·格尔林 乔治·席格 肖恩·吉布朗尼 托伊·金太尔",625,762);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","9.3",764,807);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"color:#111111;font-family:Helvetica, Arial, sans-serif;line-height:19px;\">ABC已续订《戈德堡一家》第三季。</span>",809,993);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",995,1036);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",1038,1082);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","美剧",1084,1127);
$z[12][4]['name']="area";
$z[13]=Array("field","",1129,1169);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914NTNW0-144049.jpg",1171,1264);
$z[14][4]['name']="litpic";

?>