<?php
$z[0]=Array("field","自杀森林,自杀森林迅雷下",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《自杀森林》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《自杀森林》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","自杀森林",366,416);
$z[2][4]['name']="title";
$z[3]=Array("field","",418,457);
$z[3][4]['name']="writer";
$z[4]=Array("field","",459,498);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",500,541);
$z[5][4]['name']="time";
$z[6]=Array("field","杰森·扎达 </li>\r\n<li class=\"info_dq\">地区：\r\n欧美",543,641);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","娜塔莉·多默尔 泰勒·金尼 欧文·马肯 斯蒂芬妮·沃格特",643,757);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",759,803);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">故事背景是日本著名的自杀森林青木原树海，歪嘴女多默尔演的主角从美国来到森林寻找自己的妹妹</span>",805,1099);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1101,1142);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",1144,1188);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","欧美",1190,1233);
$z[12][4]['name']="area";
$z[13]=Array("field","",1235,1275);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914BUYJ0-24c13.jpg",1277,1369);
$z[14][4]['name']="litpic";

?>