{dede:field name='keywords'}女汉子真爱公式/女汉子完{/dede:field}
{dede:field name='description'}最新电影《女汉子真爱公式/女汉子完美恋人》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《女汉子真爱公式/女汉子完美恋人》完整版迅雷高清下载，以及高清在线播{/dede:field}
{dede:field name='title'}女汉子真爱公式/女汉子完美恋人电影迅雷高清下载,女汉子真爱公式/女汉子完美恋人高清下载在线观看 - 大陆 - a67手机电影网{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}郭大雷 </li>
<li class="info_dq">地区：
大陆{/dede:field}
{dede:field name='yanyuan'}赵丽颖 张翰 童菲 丁一宇 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《女汉子真爱公式/女汉子完美恋人》在线观看" title="《女汉子真爱公式/女汉子完美恋人》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《女汉子真爱公式/女汉子完美恋人》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}9.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">&lt;span style="color:#111111;font-family:Helvetica, Arial, sans-serif;line-height:19px;"&gt;悉尼大学数学统计专业女学霸何修舞（赵丽颖 饰）在硕士论文中推导出了“真爱公式”，坚信自己公式绝对无误的何修舞，却接到了自己第一个实验对象失败自杀的噩耗……&amp;nbsp;&lt;/span&gt;&lt;br style="color:#111111;font-family:Helvetica, Arial, sans-serif;line-height:19px;" /&gt; &lt;span style="color:#111111;font-family:Helvetica, Arial, sans-serif;line-height:19px;"&gt;　　为了早点送走可怕的学霸女，叶思逸（张翰 饰）决定亲自帮助她寻觅她的真命天子，只是这个过程中，到底是哪里变的不对了，竟然有了奇怪的化学反应……&lt;/span&gt;</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语</li>
<li class="yanyuan">主演：
<a href="/search/%E8%B5%B5%E4%B8%BD%E9%A2%96" target="_blank">赵丽颖</a> <a href="/tag/8019/" target="_blank">张翰</a> <a href="/search/%E7%AB%A5%E8%8F%B2" target="_blank">童菲</a> <a href="/search/%E4%B8%81%E4%B8%80%E5%AE%87" target="_blank">丁一宇</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《女汉子真爱公式/女汉子完美恋人》在线观看" title="《女汉子真爱公式/女汉子完美恋人》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《女汉子真爱公式/女汉子完美恋人》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/14591345103960-22S58.jpg{/dede:field}
