<?php
$z[0]=Array("field","澄和薰\\澄和堇,澄和薰\\澄",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《澄和薰\\澄和堇》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《澄和薰\\澄和堇》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和",76,365);
$z[1][4]['name']="description";
$z[2]=Array("field","澄和薰\\澄和堇",367,424);
$z[2][4]['name']="title";
$z[3]=Array("field","",426,465);
$z[3][4]['name']="writer";
$z[4]=Array("field","",467,506);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",508,549);
$z[5][4]['name']="time";
$z[6]=Array("field","今井和久",551,602);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","桐谷美玲 松坂庆子 及川光博 町田启太",604,695);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","7.6",697,740);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"white-space:normal;word-spacing:0px;text-transform:none;float:none;color:#000000;text-align:left;font:12px/16px 宋体;widows:1;display:inline !important;letter-spacing:normal;background-color:#ffffff;text-indent:0px;-webkit-text-stroke-width:0px;\">桐谷美玲饰演的主人公如月薰，外表看起来是一个普通的20岁女大学生，然而实际上真身却是名为如月澄的65岁女性。澄幼年起就在家里帮忙，青春就在不知不觉中枉送，之后又开启了照顾祖母、父母的漫长岁月，不知不觉便来到了65岁，从未恋爱的她，一步一个脚印踏实活到了今天。在母亲去世后，澄冒出了一个想法，如果能够再次回到过去，人生也会再次重来吧，然而奇迹真的出现了，某日醒来后自己真的回到了二十岁，虽抱有不安，但还是以如月薰为名成功重返青春。</span>",742,1686);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1688,1729);
$z[10][4]['name']="download";
$z[11]=Array("field","日语",1731,1775);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","其他",1777,1820);
$z[12][4]['name']="area";
$z[13]=Array("field","",1822,1862);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914N12V960-2V01.jpg",1864,1957);
$z[14][4]['name']="litpic";

?>