{dede:field name='keywords'}禁果,禁果迅雷下载,禁果高{/dede:field}
{dede:field name='description'}最新电影《禁果》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《禁果》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共同享受下{/dede:field}
{dede:field name='title'}禁果{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2009{/dede:field}
{dede:field name='daoyan'}多姆·卡如库斯基 </li>
<li class="info_dq">地区：
欧美{/dede:field}
{dede:field name='yanyuan'}玛约特·马里斯托 阿曼达·皮尔克 玛拉·毛米瓦拉{/dede:field}
{dede:field name='pingfen'}8.6{/dede:field}
{dede:field name='introduction'}<p>
	《禁果》外面的世界更精彩，还是更无奈？两个成长于信仰保守乡村的女孩儿，决定去看看外面的真实世界，在快节奏和充满变化的都市里，她们的信仰和贞操都在不经意间流失，茫然，慌张，挣扎，最后她们懂得，只有经历了、失去了，对信仰的重要性才能有更切身的理解……这是一部感人的芬兰电影，信仰与爱欲发生着激烈的碰撞。同时，这又是一首略带忧伤的青春诗，两位女主角出门去看大世界，最终身心残缺地回到故乡，这，或许就是成长。本片故事简洁，手法节制，不动声色间动人心扉。
</p>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}英语{/dede:field}
{dede:field name='area'}欧美{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914BcOQ0-43212.jpg{/dede:field}
