{dede:field name='keywords'}战神：只是爱着你,战神：{/dede:field}
{dede:field name='description'}最新电影《战神：只是爱着你》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《战神：只是爱着你》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，{/dede:field}
{dede:field name='title'}战神：只是爱着你电影迅雷高清下载,战神：只是爱着你高清下载在线观看 - 日韩 - a67手机电影网{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2006{/dede:field}
{dede:field name='daoyan'}新城毅彦 </li>
<li class="info_dq">地区：
日韩{/dede:field}
{dede:field name='yanyuan'}玉木宏 宫崎葵 黑木明纱 青木崇高 小出惠介 上原美佐 大西麻惠 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《战神：只是爱着你》在线观看" title="《战神：只是爱着你》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《战神：只是爱着你》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}8.7{/dede:field}
{dede:field name='introduction'}<p>
	濑川诚人(玉木宏&nbsp;饰)是一个大学新鲜人，他不愿参加学校的开学典礼而选择了在校园附近闲逛。他在马路旁遇到了里中静流(宫崎葵&nbsp;饰)，她古怪的行径使热爱摄影的诚人忍不住按下了快门。自此静流喜欢上了诚人，可诚人只当她是朋友。随后他们成为了朋友，诚人也喜欢上了同班的富山美雪(黑木明纱&nbsp;饰)。他跟静流发现了一个环境优美的树林，因为喜欢诚人的关系，静流也喜欢上摄影。静流要和诚人一起参加摄影比赛，而她的作品就是拍下跟诚人在湖边接吻的画面。但是当天傍晚，静流却不辞而别……
</p>
<p>
	<br />
</p>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}日语</li>
<li class="yanyuan">主演：
<a href="/search/%E7%8E%89%E6%9C%A8%E5%AE%8F" target="_blank">玉木宏</a> <a href="/tag/1901/" target="_blank">宫崎葵</a> <a href="/tag/1965/" target="_blank">黑木明纱</a> <a href="/search/%E9%9D%92%E6%9C%A8%E5%B4%87%E9%AB%98" target="_blank">青木崇高</a> <a href="/tag/1277/" target="_blank">小出惠介</a> <a href="/search/%E4%B8%8A%E5%8E%9F%E7%BE%8E%E4%BD%90" target="_blank">上原美佐</a> <a href="/search/%E5%A4%A7%E8%A5%BF%E9%BA%BB%E6%83%A0" target="_blank">大西麻惠</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《战神：只是爱着你》在线观看" title="《战神：只是爱着你》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《战神：只是爱着你》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}日韩{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/14591344P44930-3B38.jpg{/dede:field}
