<?php
$z[0]=Array("field","嘻哈西游之五指山,嘻哈西",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《嘻哈西游之五指山》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《嘻哈西游之五指山》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","嘻哈西游之五指山",366,428);
$z[2][4]['name']="title";
$z[3]=Array("field","",430,469);
$z[3][4]['name']="writer";
$z[4]=Array("field","",471,510);
$z[4][4]['name']="source";
$z[5]=Array("field","5.5",512,555);
$z[5][4]['name']="pingfen";
$z[6]=Array("field","李葱",557,602);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","于小鱼 杨文",604,660);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","2016",662,703);
$z[8][4]['name']="time";
$z[9]=Array("field","国语",705,749);
$z[9][4]['name']="yuyan";
$z[10]=Array("field","大陆",751,794);
$z[10][4]['name']="area";
$z[11]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">新媒体电影《嘻哈西游之五指山》故事取材于《西游记》中唐僧在五指山相遇孙悟空的章节。故事以孙悟空和紫霞被挟持开始，劫匪绑架了孙悟空和紫霞，一同来到五指山客栈投宿，没想到这竟是猪八戒和老沙合伙经营的黑店！他们总想着给客人下药.......碰巧唐三藏要去西天取经，路过五指山，不巧又有一群妖怪想吃唐三藏，他们抓唐三藏抓到了五指山客栈，却不知，五指山客栈已经鱼龙混杂！一系列啼笑皆非的情节由此展开....</span>",796,1530);
$z[11][4]['name']="introduction";
$z[12]=Array("field","",1532,1573);
$z[12][4]['name']="download";
$z[13]=Array("field","",1575,1615);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V33401MY0-133530.jpg",1617,1711);
$z[14][4]['name']="litpic";

?>