{dede:field name='keywords'}嘻哈西游之五指山,嘻哈西{/dede:field}
{dede:field name='description'}最新电影《嘻哈西游之五指山》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《嘻哈西游之五指山》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，{/dede:field}
{dede:field name='title'}嘻哈西游之五指山{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pingfen'}5.5{/dede:field}
{dede:field name='daoyan'}李葱{/dede:field}
{dede:field name='yanyuan'}于小鱼 杨文{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">新媒体电影《嘻哈西游之五指山》故事取材于《西游记》中唐僧在五指山相遇孙悟空的章节。故事以孙悟空和紫霞被挟持开始，劫匪绑架了孙悟空和紫霞，一同来到五指山客栈投宿，没想到这竟是猪八戒和老沙合伙经营的黑店！他们总想着给客人下药.......碰巧唐三藏要去西天取经，路过五指山，不巧又有一群妖怪想吃唐三藏，他们抓唐三藏抓到了五指山客栈，却不知，五指山客栈已经鱼龙混杂！一系列啼笑皆非的情节由此展开....</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160322/145V33401MY0-133530.jpg{/dede:field}
