{dede:field name='keywords'}初恋搞笑艺人,初恋搞笑艺{/dede:field}
{dede:field name='description'}最新电视剧《初恋搞笑艺人》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《初恋搞笑艺人》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和{/dede:field}
{dede:field name='title'}初恋搞笑艺人{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}小林義則{/dede:field}
{dede:field name='yanyuan'}柄本時生 松井玲奈 内田朝陽 桜田通{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">一个没有卖点毫无可取之处的年轻搞笑艺人，有一天遇到了一个说他段子很有趣的迷之少女，开启了他的恋爱之心。"</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}日语{/dede:field}
{dede:field name='area'}其他{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914NW4EP-161Q9.jpg{/dede:field}
