<?php
$z[0]=Array("field","初恋搞笑艺人,初恋搞笑艺",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《初恋搞笑艺人》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《初恋搞笑艺人》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","初恋搞笑艺人",366,422);
$z[2][4]['name']="title";
$z[3]=Array("field","",424,463);
$z[3][4]['name']="writer";
$z[4]=Array("field","",465,504);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",506,547);
$z[5][4]['name']="time";
$z[6]=Array("field","小林義則",549,600);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","柄本時生 松井玲奈 内田朝陽 桜田通",602,690);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",692,736);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;\">一个没有卖点毫无可取之处的年轻搞笑艺人，有一天遇到了一个说他段子很有趣的迷之少女，开启了他的恋爱之心。\"</span>",738,1039);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1041,1082);
$z[10][4]['name']="download";
$z[11]=Array("field","日语",1084,1128);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","其他",1130,1173);
$z[12][4]['name']="area";
$z[13]=Array("field","",1175,1215);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914NW4EP-161Q9.jpg",1217,1309);
$z[14][4]['name']="litpic";

?>