<?php
$z[0]=Array("field","确认,确认迅雷下载,确认高",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《确认》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《确认》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共同享受下",78,365);
$z[1][4]['name']="description";
$z[2]=Array("field","确认",367,411);
$z[2][4]['name']="title";
$z[3]=Array("field","",413,452);
$z[3][4]['name']="writer";
$z[4]=Array("field","",454,493);
$z[4][4]['name']="source";
$z[5]=Array("field","",495,535);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","10.0",537,581);
$z[6][4]['name']="pingfen";
$z[7]=Array("field","Bob Nelson",583,632);
$z[7][4]['name']="daoyan";
$z[8]=Array("field","克里夫·欧文 玛丽亚·贝罗 帕顿·奥斯瓦尔特 斯蒂芬·托布罗斯基",634,760);
$z[8][4]['name']="yanyuan";
$z[9]=Array("field","2016",762,803);
$z[9][4]['name']="time";
$z[10]=Array("field","英语",805,849);
$z[10][4]['name']="yuyan";
$z[11]=Array("field","欧美",851,894);
$z[11][4]['name']="area";
$z[12]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">八岁的安东尼有点不安花周末和他的酒鬼,耗尽了木匠爸爸沃尔特,而他的妈妈邦妮和她的新丈夫凯尔一起去天主教撤退。沃尔特一样不安与安东尼,尤其是第一天一起不幸的是一系列的典型事件,包括他的卡车打破,他的房东锁定了他的房子,和窃取他的工具箱,他需要为即将到来的工作。</span>",896,1431);
$z[12][4]['name']="introduction";
$z[13]=Array("field","",1433,1474);
$z[13][4]['name']="download";
$z[14]=Array("field","",1476,1515);
$z[14][4]['name']="litpic";

?>