<?php
$z[0]=Array("field","疯狂动物城,疯狂动物城迅",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《疯狂动物城》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《疯狂动物城》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","疯狂动物城",366,419);
$z[2][4]['name']="title";
$z[3]=Array("field","",421,460);
$z[3][4]['name']="writer";
$z[4]=Array("field","",462,501);
$z[4][4]['name']="source";
$z[5]=Array("field","",503,543);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","8.1",545,588);
$z[6][4]['name']="pingfen";
$z[7]=Array("field","拜伦·霍华德 瑞奇·摩尔",590,661);
$z[7][4]['name']="daoyan";
$z[8]=Array("field","金妮弗·古德温 杰森·贝特曼 夏奇拉",663,751);
$z[8][4]['name']="yanyuan";
$z[9]=Array("field","2016",753,794);
$z[9][4]['name']="time";
$z[10]=Array("field","英语",796,840);
$z[10][4]['name']="yuyan";
$z[11]=Array("field","欧美",842,885);
$z[11][4]['name']="area";
$z[12]=Array("field","<span style=\"font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;\">疯狂动物城是一座独一无二的现代动物都市。每种动物在这里都有自己的居所，比如富丽堂皇的撒哈拉广场，或者常年严寒的冰川镇。它就像一座大熔炉，动物们在这里和平共处——无论是大象还是小老鼠，只要你努力，都能在此闯出一番名堂。不过乐观的警官兔朱迪（金妮弗·古德温 Ginnifer Goodwin 配音）却发现，作为史上第一任兔子警官，要和一群强硬的大块头动物警察合作可不是件容易事。为了证明自己，她决心侦破一桩神秘案件；追寻真相的路上她被迫与口若悬河、谎技高超的狐尼克（杰森·贝特曼 Jason Bateman 配音）联手，却发现这桩案件背后隐藏着一个意欲颠覆动物城的巨大阴谋……</span>",887,1824);
$z[12][4]['name']="introduction";
$z[13]=Array("field","",1826,1867);
$z[13][4]['name']="download";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V3341934R0-249420.jpg",1869,1964);
$z[14][4]['name']="litpic";

?>