<?php
$z[0]=Array("field","爱回家粤语,爱回家粤语电",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《爱回家粤语》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《爱回家粤语》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","爱回家粤语",366,419);
$z[2][4]['name']="title";
$z[3]=Array("field","",421,460);
$z[3][4]['name']="writer";
$z[4]=Array("field","",462,501);
$z[4][4]['name']="source";
$z[5]=Array("field","2012",503,544);
$z[5][4]['name']="time";
$z[6]=Array("field","未知",546,591);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","刘丹 黎诺懿 徐荣 郭少芸 林漪娸 朱慧敏",593,686);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","7.2",688,731);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span property=\"v:summary\">爱回家(TVB剧)任职惩教署多年的马虎（<a href=\"\" target=\"_target\">家庭</a>及各人，造型会(4张)令小儿子马壮（黎诺懿饰）回家犹如坐牢，就连他在律师楼的工作也经常受老爸干涉，两父子争拗日多，夹在中间的二哥马强（徐荣饰）和妻子劳丽嫦（林漪娸饰）除了经常充当调解者，更要背负抚养大哥遗下一对子女的重担，加上一个十三点的姑姐马柔（郭少芸饰）；马家三代同堂，因着不同的际遇、经历及价值观，令原来温馨的小<a href=\"\" target=\"_target\">家庭</a>里埋伏着莫名的芥蒂，到底用什么才可真正填补各人心中的罅隙……</span>",733,1499);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1501,1542);
$z[10][4]['name']="download";
$z[11]=Array("field","粤语",1544,1588);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","港台",1590,1633);
$z[12][4]['name']="area";
$z[13]=Array("field","",1635,1675);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914NF50D0-54M3.jpg",1677,1769);
$z[14][4]['name']="litpic";

?>