{dede:field name='keywords'}噩梦老师,噩梦老师电视剧{/dede:field}
{dede:field name='description'}最新电视剧《噩梦老师》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《噩梦老师》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友{/dede:field}
{dede:field name='title'}噩梦老师{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}内详{/dede:field}
{dede:field name='yanyuan'}金所炫{/dede:field}
{dede:field name='pingfen'}8.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:Simsun;font-size:medium;line-height:normal;white-space:normal;">《噩梦老师》是一部学园神秘剧。剧中，某所高中日复一日的生活中，学生们在做梦的瞬间陷入了陌生而奇妙、无法抗拒的甜蜜诱惑。李旼赫饰演的高二学生尚宇很有好奇心和正义感，与好友誉林(金所炫 饰)一起，调查身份不明的噩梦老师河奉九(严基俊 饰)调任来校后发生的可疑事件。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}韩语{/dede:field}
{dede:field name='area'}韩剧{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914N640H50-1OE.jpg{/dede:field}
