<?php
$z[0]=Array("field","芝加哥警署第三季,芝加哥",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《芝加哥警署第三季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《芝加哥警署第三季》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","芝加哥警署第三季",366,428);
$z[2][4]['name']="title";
$z[3]=Array("field","",430,469);
$z[3][4]['name']="writer";
$z[4]=Array("field","",471,510);
$z[4][4]['name']="source";
$z[5]=Array("field","2015",512,553);
$z[5][4]['name']="time";
$z[6]=Array("field","ArthurW.Forney",555,608);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","杰森·贝吉 乔恩·塞达 索菲亚·布什 杰西·李·索弗 帕特里克·约翰·弗鲁格",610,749);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","0.0",751,794);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"color:#111111;font-family:Helvetica, Arial, sans-serif;line-height:19px;\">NBC已续订《芝加哥警署》第三季。</span>",796,980);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",982,1023);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",1025,1069);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","美剧",1071,1114);
$z[12][4]['name']="area";
$z[13]=Array("field","",1116,1156);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","http://img.a67.com/201511/13/201511131634175096.jpg",1158,1248);
$z[14][4]['name']="litpic";

?>