<?php
$z[0]=Array("field","失常/异常现象,失常/异常",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《失常/异常现象》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《失常/异常现象》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您",76,365);
$z[1][4]['name']="description";
$z[2]=Array("field","失常/异常现象",367,424);
$z[2][4]['name']="title";
$z[3]=Array("field","",426,465);
$z[3][4]['name']="writer";
$z[4]=Array("field","",467,506);
$z[4][4]['name']="source";
$z[5]=Array("field","5.5",508,551);
$z[5][4]['name']="pingfen";
$z[6]=Array("field","查理·考夫曼",553,609);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","詹妮弗·杰森·李 大卫·休里斯 汤姆·诺南",611,706);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","2016",708,749);
$z[8][4]['name']="time";
$z[9]=Array("field","英语",751,795);
$z[9][4]['name']="yuyan";
$z[10]=Array("field","欧美",797,840);
$z[10][4]['name']="area";
$z[11]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">鸡汤书籍《我该如何帮你去帮助他人》作者迈克尔·斯通（Michael Stone）来到辛辛那提，准备在一场大会上发表励志演说。这个面临中年危机的已婚男人邂逅了一位不善言辞的销售代理丽莎（Lisa），两人碰出了火花，由此展开了一段婚外情。</span>",842,1320);
$z[11][4]['name']="introduction";
$z[12]=Array("field","",1322,1363);
$z[12][4]['name']="download";
$z[13]=Array("field","",1365,1405);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V3339594250-10W09.jpg",1407,1502);
$z[14][4]['name']="litpic";

?>