<?php
$z[0]=Array("field","恶魔之子第一季,恶魔之子",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《恶魔之子第一季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《恶魔之子第一季》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","恶魔之子第一季",366,425);
$z[2][4]['name']="title";
$z[3]=Array("field","",427,466);
$z[3][4]['name']="writer";
$z[4]=Array("field","",468,507);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",509,550);
$z[5][4]['name']="time";
$z[6]=Array("field","厄内斯特·R·迪克森 </li>\r\n<li class=\"info_dq\">地区：\r\n欧美",552,662);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","奥米德·阿布塔西 梅歌林·艾奇坤沃克",664,754);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","8.4",756,799);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:Simsun;font-size:medium;line-height:normal;white-space:normal;\">A&amp;E宣布惊悚超自然题材剧集Damien将会在今年年底时候播出、这部剧集最早在去年夏天被Lifetime以6集的形式预订，如今转换到A&amp;E以后，第一季的集数将扩为10集。 　　这部剧集取材于1976年的经典恐怖片《凶兆 The Omen》（由Gregory Peck主演）。在电影里，主人公领养了一个叫Damien的小孩，之后却遭遇了一系列奇怪的事件。神父更认为Damien是魔鬼撒旦的孩子。 　　而电视剧集则将讲述电影里Damien Thorn长大成人的故事。随着长大，他渐渐意识到了自己的真实身份----一个反基督者。该剧已经确定《梅林传奇》“Arthur”Bradley James担当主角Damien。</span>",801,1659);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1661,1702);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",1704,1748);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","欧美",1750,1793);
$z[12][4]['name']="area";
$z[13]=Array("field","",1795,1835);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914BQF1P-21L34.jpg",1837,1929);
$z[14][4]['name']="litpic";

?>