{dede:field name='keywords'}恶魔之子第一季,恶魔之子{/dede:field}
{dede:field name='description'}最新电影《恶魔之子第一季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《恶魔之子第一季》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您{/dede:field}
{dede:field name='title'}恶魔之子第一季{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}厄内斯特·R·迪克森 </li>
<li class="info_dq">地区：
欧美{/dede:field}
{dede:field name='yanyuan'}奥米德·阿布塔西 梅歌林·艾奇坤沃克{/dede:field}
{dede:field name='pingfen'}8.4{/dede:field}
{dede:field name='introduction'}<span style="font-family:Simsun;font-size:medium;line-height:normal;white-space:normal;">A&amp;E宣布惊悚超自然题材剧集Damien将会在今年年底时候播出、这部剧集最早在去年夏天被Lifetime以6集的形式预订，如今转换到A&amp;E以后，第一季的集数将扩为10集。 　　这部剧集取材于1976年的经典恐怖片《凶兆 The Omen》（由Gregory Peck主演）。在电影里，主人公领养了一个叫Damien的小孩，之后却遭遇了一系列奇怪的事件。神父更认为Damien是魔鬼撒旦的孩子。 　　而电视剧集则将讲述电影里Damien Thorn长大成人的故事。随着长大，他渐渐意识到了自己的真实身份----一个反基督者。该剧已经确定《梅林传奇》“Arthur”Bradley James担当主角Damien。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}英语{/dede:field}
{dede:field name='area'}欧美{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914BQF1P-21L34.jpg{/dede:field}
