{dede:field name='keywords'}心跳零距离/让心跳动,心跳{/dede:field}
{dede:field name='description'}最新电影《心跳零距离/让心跳动》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《心跳零距离/让心跳动》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a6{/dede:field}
{dede:field name='title'}心跳零距离/让心跳动{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}卓娅·阿赫塔尔 </li>
<li class="info_dq">地区：
其他{/dede:field}
{dede:field name='yanyuan'}亚尼·卡普 普里扬卡·乔普拉{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">Kamal Mehra（亚尼·卡普 Anil Kapoor 饰）是一位成功的商人，但他的公司却濒临破产，他与妻子Neelam（Shefali Shetty 饰）感情不和，他们的儿子Kabir（兰维尔·辛格 Ranveer Singh 饰）不愿继承家业，而是渴望当一名飞行 员，女儿Ayesha（普里扬卡·乔普拉 Priyanka Chopra 饰）拥有一家旅行社，但因被安排嫁给Manav（Rahul Bose 饰）而郁郁寡欢。为庆祝父母的30周年结婚纪念日，兄妹二人邀请亲朋好友参加为期十天的海上旅行，而旅行的过程却并不平静…</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}{/dede:field}
{dede:field name='area'}其他{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914B641J10-10P30.jpg{/dede:field}
