<?php
$z[0]=Array("field","心跳零距离/让心跳动,心跳",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《心跳零距离/让心跳动》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《心跳零距离/让心跳动》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a6",78,363);
$z[1][4]['name']="description";
$z[2]=Array("field","心跳零距离/让心跳动",365,431);
$z[2][4]['name']="title";
$z[3]=Array("field","",433,472);
$z[3][4]['name']="writer";
$z[4]=Array("field","",474,513);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",515,556);
$z[5][4]['name']="time";
$z[6]=Array("field","卓娅·阿赫塔尔 </li>\r\n<li class=\"info_dq\">地区：\r\n其他",558,662);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","亚尼·卡普 普里扬卡·乔普拉",664,742);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",744,788);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">Kamal Mehra（亚尼·卡普 Anil Kapoor 饰）是一位成功的商人，但他的公司却濒临破产，他与妻子Neelam（Shefali Shetty 饰）感情不和，他们的儿子Kabir（兰维尔·辛格 Ranveer Singh 饰）不愿继承家业，而是渴望当一名飞行 员，女儿Ayesha（普里扬卡·乔普拉 Priyanka Chopra 饰）拥有一家旅行社，但因被安排嫁给Manav（Rahul Bose 饰）而郁郁寡欢。为庆祝父母的30周年结婚纪念日，兄妹二人邀请亲朋好友参加为期十天的海上旅行，而旅行的过程却并不平静…</span>",790,1527);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1529,1570);
$z[10][4]['name']="download";
$z[11]=Array("field","",1572,1610);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","其他",1612,1655);
$z[12][4]['name']="area";
$z[13]=Array("field","",1657,1697);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914B641J10-10P30.jpg",1699,1793);
$z[14][4]['name']="litpic";

?>