{dede:field name='keywords'}神战：权力之眼/埃及神战{/dede:field}
{dede:field name='description'}最新电影《神战：权力之眼/埃及神战》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《神战：权力之眼/埃及神战》完整版迅雷高清下载，以及高清在线播放，轻轻一点{/dede:field}
{dede:field name='title'}神战：权力之眼/埃及神战{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='daoyan'}亚历克斯·普罗亚斯{/dede:field}
{dede:field name='yanyuan'}尼古拉·科斯特-瓦尔道 杰拉德·巴特勒 布伦顿·思韦茨{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='yuyan'}英语{/dede:field}
{dede:field name='area'}欧美{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">故事发生在矗立着宫殿和金字塔的婉转萦回的尼罗河畔。 当时的古埃及充满了魔法、怪兽和神灵。无情的黑暗之神赛特,夺取了原本属于天神荷鲁斯的埃及王权,并让曾经繁荣和平的国家陷入冲突与混乱。人类的存亡与世界的安定岌岌可危。 一位年轻的窃贼贝克被神所眷顾,为拯救世界和自己的真爱踏上了一场惊险的奇幻旅程。为了成功,他必须寻求并得到强大的荷鲁斯神的帮助,与其组成一个看似不太可能的“英雄” 联盟。随着人类生命的危在旦夕,两个英雄站了出来,开启了对抗邪恶的不归路...... 作为荷鲁斯与贝克强有力的敌人,赛特指派心腹为他们的对抗制造重重艰难险阻。如果荷鲁斯神与凡人贝克希望在这场对抗中最终获胜,他们就必须通过一系列对勇气和牺牲的考验。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160322/145V3341502N0-21N09.jpg{/dede:field}
