<?php
$z[0]=Array("field","时空救援之明月危机,时空",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《时空救援之明月危机》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《时空救援之明月危机》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","时空救援之明月危机",366,431);
$z[2][4]['name']="title";
$z[3]=Array("field","",433,472);
$z[3][4]['name']="writer";
$z[4]=Array("field","",474,513);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",515,556);
$z[5][4]['name']="time";
$z[6]=Array("field","聂海熙 </li>\r\n<li class=\"info_dq\">地区：\r\n大陆",558,651);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","杨润坤 史雨",653,709);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",711,755);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">我爱上了一个已经死去的女孩，我必须阻止一场4年前的谋杀！” 小职员宇浩无意中发现，自己整天观察的对楼女孩，竟然是一个4年前就被谋杀的人。本以为是一场人鬼情未了，没想到却是时空错位导致他可以和4年前的夏如联系。 于是，宇浩展开了一场拯救心爱女孩生命的惊险历程。他们究竟能不能抓住凶手，在同一个时空相遇？</span>",757,1359);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1361,1402);
$z[10][4]['name']="download";
$z[11]=Array("field","国语",1404,1448);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","大陆",1450,1493);
$z[12][4]['name']="area";
$z[13]=Array("field","",1495,1535);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914BX4U50-2A319.jpg",1537,1630);
$z[14][4]['name']="litpic";

?>