{dede:field name='keywords'}进击的巨人真人版后篇.世{/dede:field}
{dede:field name='description'}最新电影《进击的巨人真人版后篇.世界终结》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《进击的巨人真人版后篇.世界终结》完整版迅雷高清下载，以及高清在线播{/dede:field}
{dede:field name='title'}进击的巨人真人版后篇.世界终结{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}樋口真嗣 </li>
<li class="info_dq">地区：
其他{/dede:field}
{dede:field name='yanyuan'}三浦春马 长谷川博己 水原希子 三浦贵大 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《进击的巨人真人版后篇.世界终结》在线观看" title="《进击的巨人真人版后篇.世界终结》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《进击的巨人真人版后篇.世界终结》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}8.9{/dede:field}
{dede:field name='introduction'}{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}日语</li>
<li class="yanyuan">主演：
<a href="/search/%E4%B8%89%E6%B5%A6%E6%98%A5%E9%A9%AC" target="_blank">三浦春马</a> <a href="/search/%E9%95%BF%E8%B0%B7%E5%B7%9D%E5%8D%9A%E5%B7%B1" target="_blank">长谷川博己</a> <a href="/search/%E6%B0%B4%E5%8E%9F%E5%B8%8C%E5%AD%90" target="_blank">水原希子</a> <a href="/search/%E4%B8%89%E6%B5%A6%E8%B4%B5%E5%A4%A7" target="_blank">三浦贵大</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《进击的巨人真人版后篇.世界终结》在线观看" title="《进击的巨人真人版后篇.世界终结》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《进击的巨人真人版后篇.世界终结》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}其他{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145913QX59110-2Kb3.jpg{/dede:field}
