{dede:field name='keywords'}听见下雨的声音,听见下雨{/dede:field}
{dede:field name='description'}最新电影《听见下雨的声音》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《听见下雨的声音》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您{/dede:field}
{dede:field name='title'}听见下雨的声音{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2013{/dede:field}
{dede:field name='daoyan'}方文山 </li>
<li class="info_dq">地区：
大陆{/dede:field}
{dede:field name='yanyuan'}柯有伦 韩雨洁 徐若瑄 释小龙 徐娇 周觅 康康 邹承恩 魏如昀 林志炫 品冠 侯佩岑 李东学 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《听见下雨的声音》在线观看" title="《听见下雨的声音》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《听见下雨的声音》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}9.2{/dede:field}
{dede:field name='introduction'}{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语</li>
<li class="yanyuan">主演：
<a href="/tag/5331/" target="_blank">柯有伦</a> <a href="/search/%E9%9F%A9%E9%9B%A8%E6%B4%81" target="_blank">韩雨洁</a> <a href="/tag/4553/" target="_blank">徐若瑄</a> <a href="/tag/961/" target="_blank">释小龙</a> <a href="/tag/8029/" target="_blank">徐娇</a> <a href="/search/%E5%91%A8%E8%A7%85" target="_blank">周觅</a> <a href="/search/%E5%BA%B7%E5%BA%B7" target="_blank">康康</a> <a href="/search/%E9%82%B9%E6%89%BF%E6%81%A9" target="_blank">邹承恩</a> <a href="/search/%E9%AD%8F%E5%A6%82%E6%98%80" target="_blank">魏如昀</a> <a href="/search/%E6%9E%97%E5%BF%97%E7%82%AB" target="_blank">林志炫</a> <a href="/search/%E5%93%81%E5%86%A0" target="_blank">品冠</a> <a href="/tag/503/" target="_blank">侯佩岑</a> <a href="/search/%E6%9D%8E%E4%B8%9C%E5%AD%A6" target="_blank">李东学</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《听见下雨的声音》在线观看" title="《听见下雨的声音》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《听见下雨的声音》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145913Q643FF-10aN.jpg{/dede:field}
