{dede:field name='keywords'}Goodbye Mr.Black,Goodbye Mr.Bla{/dede:field}
{dede:field name='description'}最新电视剧《Goodbye Mr.Black》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《Goodbye Mr.Black》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的{/dede:field}
{dede:field name='title'}Goodbye Mr.Black{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}韩熙{/dede:field}
{dede:field name='yanyuan'}李阵郁 文彩元 宋再临 金康宇{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:Simsun;font-size:medium;line-height:normal;white-space:normal;">《Good bye Mr.black》（再见，布莱克先生）时隔32年电视剧化...SBS编成 漫画《Good bye Mr.black》(再见，布莱克先生）时隔32年电视剧化。 一位电视剧局相关人士29日表示“1983年黄美娜（音）作家的《Good bye Mr.black》会拍摄同名电视剧。” 内容是这样的，是基督山伯爵的题材，男主人公被曾经信任的好朋友背叛，回到澳大利亚，之后逃到英国进行复仇。 他在澳大利亚认识了两个人，又形成了故事的新线路。被爱人和朋友背叛的男主人公忘掉过去，变成复仇的化身。 该剧将由《美女的诞生》李昌敏（音）导演，编剧为文锡正（音）作家。 该剧有很多海外镜头，所以会早早结束选角投入拍摄。 SBS水木剧</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}韩语{/dede:field}
{dede:field name='area'}韩剧{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914O1U1160-305U6.jpg{/dede:field}
