<?php
$z[0]=Array("field","Goodbye Mr.Black,Goodbye Mr.Bla",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《Goodbye Mr.Black》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《Goodbye Mr.Black》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的",74,363);
$z[1][4]['name']="description";
$z[2]=Array("field","Goodbye Mr.Black",365,419);
$z[2][4]['name']="title";
$z[3]=Array("field","",421,460);
$z[3][4]['name']="writer";
$z[4]=Array("field","",462,501);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",503,544);
$z[5][4]['name']="time";
$z[6]=Array("field","韩熙",546,591);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","李阵郁 文彩元 宋再临 金康宇",593,672);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",674,718);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:Simsun;font-size:medium;line-height:normal;white-space:normal;\">《Good bye Mr.black》（再见，布莱克先生）时隔32年电视剧化...SBS编成 漫画《Good bye Mr.black》(再见，布莱克先生）时隔32年电视剧化。 一位电视剧局相关人士29日表示“1983年黄美娜（音）作家的《Good bye Mr.black》会拍摄同名电视剧。” 内容是这样的，是基督山伯爵的题材，男主人公被曾经信任的好朋友背叛，回到澳大利亚，之后逃到英国进行复仇。 他在澳大利亚认识了两个人，又形成了故事的新线路。被爱人和朋友背叛的男主人公忘掉过去，变成复仇的化身。 该剧将由《美女的诞生》李昌敏（音）导演，编剧为文锡正（音）作家。 该剧有很多海外镜头，所以会早早结束选角投入拍摄。 SBS水木剧</span>",720,1653);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1655,1696);
$z[10][4]['name']="download";
$z[11]=Array("field","韩语",1698,1742);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","韩剧",1744,1787);
$z[12][4]['name']="area";
$z[13]=Array("field","",1789,1829);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914O1U1160-305U6.jpg",1831,1925);
$z[14][4]['name']="litpic";

?>