<?php
$z[0]=Array("field","女汉子真爱公式/女汉子完",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《女汉子真爱公式/女汉子完美恋人》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《女汉子真爱公式/女汉子完美恋人》完整版迅雷高清下载，以及高清在线播",77,366);
$z[1][4]['name']="description";
$z[2]=Array("field","女汉子真爱公式/女汉子完美恋人",368,449);
$z[2][4]['name']="title";
$z[3]=Array("field","",451,490);
$z[3][4]['name']="writer";
$z[4]=Array("field","",492,531);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",533,574);
$z[5][4]['name']="time";
$z[6]=Array("field","郭大雷 </li>\r\n<li class=\"info_dq\">地区：\r\n大陆",576,669);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","赵丽颖 张翰 童菲 丁一宇",671,744);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","9.0",746,789);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">&lt;span style=\"color:#111111;font-family:Helvetica, Arial, sans-serif;line-height:19px;\"&gt;悉尼大学数学统计专业女学霸何修舞（赵丽颖 饰）在硕士论文中推导出了“真爱公式”，坚信自己公式绝对无误的何修舞，却接到了自己第一个实验对象失败自杀的噩耗……&amp;nbsp;&lt;/span&gt;&lt;br style=\"color:#111111;font-family:Helvetica, Arial, sans-serif;line-height:19px;\" /&gt; &lt;span style=\"color:#111111;font-family:Helvetica, Arial, sans-serif;line-height:19px;\"&gt;　　为了早点送走可怕的学霸女，叶思逸（张翰 饰）决定亲自帮助她寻觅她的真命天子，只是这个过程中，到底是哪里变的不对了，竟然有了奇怪的化学反应……&lt;/span&gt;</span>",791,1712);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1714,1755);
$z[10][4]['name']="download";
$z[11]=Array("field","国语",1757,1801);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","大陆",1803,1846);
$z[12][4]['name']="area";
$z[13]=Array("field","",1848,1888);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914BDE010-13PH.jpg",1890,1982);
$z[14][4]['name']="litpic";

?>