{dede:field name='keywords'}女汉子真爱公式/女汉子完{/dede:field}
{dede:field name='description'}最新电影《女汉子真爱公式/女汉子完美恋人》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《女汉子真爱公式/女汉子完美恋人》完整版迅雷高清下载，以及高清在线播{/dede:field}
{dede:field name='title'}女汉子真爱公式/女汉子完美恋人{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}郭大雷 </li>
<li class="info_dq">地区：
大陆{/dede:field}
{dede:field name='yanyuan'}赵丽颖 张翰 童菲 丁一宇{/dede:field}
{dede:field name='pingfen'}9.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">&lt;span style="color:#111111;font-family:Helvetica, Arial, sans-serif;line-height:19px;"&gt;悉尼大学数学统计专业女学霸何修舞（赵丽颖 饰）在硕士论文中推导出了“真爱公式”，坚信自己公式绝对无误的何修舞，却接到了自己第一个实验对象失败自杀的噩耗……&amp;nbsp;&lt;/span&gt;&lt;br style="color:#111111;font-family:Helvetica, Arial, sans-serif;line-height:19px;" /&gt; &lt;span style="color:#111111;font-family:Helvetica, Arial, sans-serif;line-height:19px;"&gt;　　为了早点送走可怕的学霸女，叶思逸（张翰 饰）决定亲自帮助她寻觅她的真命天子，只是这个过程中，到底是哪里变的不对了，竟然有了奇怪的化学反应……&lt;/span&gt;</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914BDE010-13PH.jpg{/dede:field}
