<li class="c[field:global.autoindex/]">
									<a href="" target="_blank">
										<img  src="[field:litpic/]"
											  alt="爱情维修站" /></a
									><p>[field:yuyan/]</p>
									<b><a href="[field:arcurl/]" target="_blank">[field:title/]</a>
										<script src="[field:global.cfg_plus_dir/]/pinfen.php?type=getstar&aid=[field:id/]" type='text/javascript' language="javascript"></script>
										<em>[field:pingfen/]分</em></b>
								</li>