{dede:field name='keywords'}小镇大法官/中国式法庭{/dede:field}
{dede:field name='description'}最新电视剧《小镇大法官/中国式法庭》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《小镇大法官/中国式法庭》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，{/dede:field}
{dede:field name='title'}小镇大法官/中国式法庭{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}梦继{/dede:field}
{dede:field name='yanyuan'}林永健 陈瑾 范明 李健{/dede:field}
{dede:field name='pingfen'}5.5{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">讲述中国最基层法官的故事。荷塘法庭坐落在一个古典小镇，它是人民法院的最小派出机构。法庭一共有五个人，像邻家大叔一样的老庭长王德忠，性格像刘罗锅一样幽默可爱，办案时“能屈能伸，当断不断”，经常出人意料。新到荷塘法庭任职的年轻法官姜浩不问困难有多少，只问困难在哪里，相信草根也能成凤凰男，是职场草根阶层的代表。只想调离法庭，到上级法院当法官，并为女儿找一个重点学校读书的老法官何见。是生活中守信用的好父亲，是工作中不容任何人提缺点、找毛病，挑战自己权威的自负男。法庭的书记员彭小青，是职场中可爱女。法律援助工作者肖丽云，工作起来认真负责，不容侵犯，释放情感时，又温柔与火热并举，让人难以捉磨和招架。全剧通过一个个民事案件的办理，展现平民百姓鲜活生动的故事。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914NZ21P-1Xb6.jpg{/dede:field}
