{dede:field name='keywords'}城市不知我哭泣,城市不知{/dede:field}
{dede:field name='description'}最新电影《城市不知我哭泣》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《城市不知我哭泣》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您{/dede:field}
{dede:field name='title'}城市不知我哭泣电影迅雷高清下载,城市不知我哭泣高清下载在线观看 - 大陆 - a67手机电影网{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}袁一木 </li>
<li class="info_dq">地区：
大陆{/dede:field}
{dede:field name='yanyuan'}田子琳 郝旭晖 马鑫鑫 周莹 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《城市不知我哭泣》在线观看" title="《城市不知我哭泣》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《城市不知我哭泣》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">农村女孩边菲菲在大学毕业后，发誓要自己走出一片天地，改变自己的人生。可面对纷繁复杂的社会，和尔虞我诈的人间是非，边菲菲真是感到很难很难。从求职屡屡受挫，到当上饭店普通服务员。好朋友的出现改变了她的一切，她从车模到堕落的糜烂生活，很长一段时间里，边菲菲沉浸在纸醉金迷的世界里，而她却在糜烂的生活中一次次受到伤害，让她在一次事件中彻底懂了人生的真谛。她决定改变自己，用自己的双手撑起一片属于自己的蓝天，时尚内涵携带着对梦想的追求，或许一片新的蓝天会呈现在她的面前--</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语</li>
<li class="yanyuan">主演：
<a href="/search/%E7%94%B0%E5%AD%90%E7%90%B3" target="_blank">田子琳</a> <a href="/search/%E9%83%9D%E6%97%AD%E6%99%96" target="_blank">郝旭晖</a> <a href="/search/%E9%A9%AC%E9%91%AB%E9%91%AB" target="_blank">马鑫鑫</a> <a href="/search/%E5%91%A8%E8%8E%B9" target="_blank">周莹</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《城市不知我哭泣》在线观看" title="《城市不知我哭泣》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《城市不知我哭泣》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/1459134403H3Z-91103.jpg{/dede:field}
