{dede:field name='keywords'}诡宅·夜呻吟,诡宅·夜呻吟{/dede:field}
{dede:field name='description'}最新电影《诡宅·夜呻吟》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《诡宅·夜呻吟》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的{/dede:field}
{dede:field name='title'}诡宅·夜呻吟电影迅雷高清下载,诡宅·夜呻吟高清下载在线观看 - 大陆 - a67手机电影网{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}内详 </li>
<li class="info_dq">地区：
大陆{/dede:field}
{dede:field name='yanyuan'}郜晓雨 蒋姗 郭晋豪 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《诡宅·夜呻吟》在线观看" title="《诡宅·夜呻吟》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《诡宅·夜呻吟》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">50年前，一座三层老宅孤零零地伫立在一片绿林中，美丽少女珍珍在三层卧室被一群男人虐杀。 一个电闪雷鸣的雨夜，房门被猛地敲响。正在裸聊的房东伟哥走到客厅打开门，门外出现的竟是一个无头的塑料服装模特，在雷电之中显得格外恐怖。伟哥被吓得将大门一关，瘫倒在地。小侯听见动静跑下楼，敲门声再次响了起来。小侯不顾伟哥阻拦打开门，只见一个漂亮性感的女人抱着塑料模特、拉着行李箱站在门口。女人自称珍珍，想要租住三楼的房间。伟哥被珍珍的美貌深深吸引，没多追问便立刻答应下来。同样垂涎欲滴的小侯则跑前跑后帮珍珍搬东西。然而伟哥的狗“蛋蛋”却不太喜欢这个新客人，对着珍珍不停地狂吠。 雨越下越大，老宅在雷雨中更显可怕。被雷声惊醒的伟哥隐约听到楼上传来女人撩人的呻吟声。伟哥黑着灯偷偷走上三楼，那声音正是从珍珍的卧室传出。伟哥色心大发，伸手想要拧开珍珍的房门，却听到走廊尽头传来窸窸窣窣的声音。伟哥蹑手蹑脚走过去，恐怖的气氛弥漫全身。突然，一个鬼影冒出来，伟哥尖叫着与鬼影抱成一团，滚下楼梯。而后接二连三的出现的诡异事件将整个故事推向了高潮……</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语</li>
<li class="yanyuan">主演：
<a href="/search/%E9%83%9C%E6%99%93%E9%9B%A8" target="_blank">郜晓雨</a> <a href="/search/%E8%92%8B%E5%A7%97" target="_blank">蒋姗</a> <a href="/search/%E9%83%AD%E6%99%8B%E8%B1%AA" target="_blank">郭晋豪</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《诡宅·夜呻吟》在线观看" title="《诡宅·夜呻吟》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《诡宅·夜呻吟》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145913441O2a0-192Z5.jpg{/dede:field}
