{dede:field name='keywords'}再见了德彪西～钢琴侦探{/dede:field}
{dede:field name='description'}最新电影《再见了德彪西～钢琴侦探岬洋介》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《再见了德彪西～钢琴侦探岬洋介》完整版迅雷高清下载，以及高清在线播{/dede:field}
{dede:field name='title'}再见了德彪西～钢琴侦探岬洋介{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='daoyan'}菅原伸太郎{/dede:field}
{dede:field name='yanyuan'}东出昌大 黑岛结菜 北大路欣也{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='yuyan'}日语{/dede:field}
{dede:field name='area'}日韩{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">该剧改编自获得第八届“这本推理小说真了不起”大奖的中山七里的畅销作品《再见了德彪西》，2013年曾被翻拍成电影，由桥本爱主演。电视剧中，左耳突然失聪的天才钢琴师、名侦探岬洋介针对发生在其钢琴课女学生（黑岛结菜）身边的事件进行侦查和破解。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160322/145V333c154F-1153L.jpg{/dede:field}
