{dede:field name='keywords'}养魂计划,养魂计划迅雷下{/dede:field}
{dede:field name='description'}最新电影《养魂计划》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《养魂计划》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共{/dede:field}
{dede:field name='title'}养魂计划{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}牟星 </li>
<li class="info_dq">地区：
大陆{/dede:field}
{dede:field name='yanyuan'}李秋望 王丝露{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">电影讲述因为一宗离奇死亡案件，城里知名侦探组合莫氏兄妹受家属委托来小镇寻求一个真相，却未曾想到会牵涉到上世纪70年代发生的一段孽缘。随着一步步接近真相的同时，不断伴随者诡异的事情发生，红衣男孩、白衣女子、挂满尸体的横梁和满布咒语的密室，这时的他们能否全身而退..</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914B5453T0-39643.jpg{/dede:field}
