<?php
$z[0]=Array("field","养魂计划,养魂计划迅雷下",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《养魂计划》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《养魂计划》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","养魂计划",366,416);
$z[2][4]['name']="title";
$z[3]=Array("field","",418,457);
$z[3][4]['name']="writer";
$z[4]=Array("field","",459,498);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",500,541);
$z[5][4]['name']="time";
$z[6]=Array("field","牟星 </li>\r\n<li class=\"info_dq\">地区：\r\n大陆",543,633);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","李秋望 王丝露",635,694);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",696,740);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">电影讲述因为一宗离奇死亡案件，城里知名侦探组合莫氏兄妹受家属委托来小镇寻求一个真相，却未曾想到会牵涉到上世纪70年代发生的一段孽缘。随着一步步接近真相的同时，不断伴随者诡异的事情发生，红衣男孩、白衣女子、挂满尸体的横梁和满布咒语的密室，这时的他们能否全身而退..</span>",742,1289);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1291,1332);
$z[10][4]['name']="download";
$z[11]=Array("field","国语",1334,1378);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","大陆",1380,1423);
$z[12][4]['name']="area";
$z[13]=Array("field","",1425,1465);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914B5453T0-39643.jpg",1467,1561);
$z[14][4]['name']="litpic";

?>