{dede:field name='keywords'}女主角失格,女主角失格迅{/dede:field}
{dede:field name='description'}最新电影《女主角失格》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《女主角失格》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋{/dede:field}
{dede:field name='title'}女主角失格{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='daoyan'}英勉{/dede:field}
{dede:field name='yanyuan'}桐谷美玲 山崎贤人 坂口健太郎{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='yuyan'}日语{/dede:field}
{dede:field name='area'}欧美{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">在某座平凡的高中内，漂亮而可爱的女孩松崎羽鸟（桐谷美玲 饰）兀自沉浸在虚无缥缈的恋爱幻想中。她和同一年级的寺坂利太（山崎贤人 饰）从小学时代就认识了，不过最初两人形同水火，相互诋毁，直到五年级时的一起事件后，两人的关系得到改善，进而变成无话不说、可以毫无忌惮戏谑打逗的好朋友。不知曾几何时，羽鸟悄悄喜欢上了对方。她信心十足，坚信自己才是利太生命中的女主角。所以无论利太先后与多少女孩交往，羽鸟从来未表现出丁点的嫉妒与不快，只因为她作为女主角的地位不可撼动，其他女孩都只是匆匆而过的配角而已。也许太过自信而不屑一顾，也许生怕一旦说出便渐行渐远，羽鸟在利太面前隐藏心事，只肯将真实的想法说与闺蜜好友中岛幸子（福田彩乃 饰）。 这一次利太又因为小事和新一任女友分手，羽鸟一副料事如神的自得之外，掩饰不住心中的喜悦。谁曾想利太很快又接受了另一位女孩的告白，而且对方还是貌不惊人甚至有些土了土气的安达未帆（我妻三轮子 饰）。不久之前，老实耿直的未帆在食堂遭到几名不良少年的刁难，那时多亏利太为她解围，似乎从这时起，未帆便喜欢上了这个闪耀的大男孩。令羽鸟倍感震惊的是，未帆与之前那些配角决然不同。她认真观察着利太的一举一动，对他的内心世界有着深入的了解和体察，甚至看似弱不经风的她敢于为了利太挺身对抗不良少年的欺负。更为严重的是，利太对着未帆露出了久违的笑容，两人的关系迅速拉近。 习惯了坐看云起的羽鸟感受到空前的危机，她自信“比任何人都更站在利太这边，比任何人都更心疼利太”，但从未有过任何行动也从未表白的她，似乎正在孤芳自赏的过程中悄然丢掉了女主角的宝座。为了抢回利太，羽鸟制定了一系列的作战计划，结果无一例外遭受惨败。当她意志消沉的时候，并没有注意到不远处有一双充满欣赏的眼睛正注视着她。对方名叫弘光广祐（坂口健太郎 饰），是学校内体学兼优的明星男生，他慢慢走近羽鸟，由此引发了青春恋爱的新一轮的波澜。 谁是谁的女主角？谁又是谁的真命天子？</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160322/145V3340cS30-1U534.jpg{/dede:field}
