<?php
$z[0]=Array("field","犯罪心理第十一季,犯罪心",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《犯罪心理第十一季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《犯罪心理第十一季》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","犯罪心理第十一季",366,428);
$z[2][4]['name']="title";
$z[3]=Array("field","",430,469);
$z[3][4]['name']="writer";
$z[4]=Array("field","",471,510);
$z[4][4]['name']="source";
$z[5]=Array("field","2015",512,553);
$z[5][4]['name']="time";
$z[6]=Array("field","GlennKershaw",555,606);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","乔·曼特纳 托马斯·吉布森",608,683);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","0.0",685,728);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","《<a href=\"\" target=\"_target\">犯罪</a>心理》第十一季正式续订。讲述了<a href=\"\" target=\"_target\">美国</a>联邦调查局总部下属的行为分析科部门（简称“BAU”）中，行为分析师们剖析最棘手的案件，分析凶手的心理和作案特征，并在他们再次施暴前预测出他们的下一步行动，协助当地警察捉拿凶手。",730,1157);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1159,1200);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",1202,1246);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","美剧",1248,1291);
$z[12][4]['name']="area";
$z[13]=Array("field","",1293,1333);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914NXU0Z-1M520.jpg",1335,1427);
$z[14][4]['name']="litpic";

?>