{dede:field name='keywords'}征服2016,征服2016迅雷下载{/dede:field}
{dede:field name='description'}最新电影《征服2016》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《征服2016》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共同享{/dede:field}
{dede:field name='title'}征服2016电影迅雷高清下载,征服2016高清下载在线观看 - 大陆 - a67手机电影网{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}王小凯 </li>
<li class="info_dq">地区：
大陆{/dede:field}
{dede:field name='yanyuan'}王凯 唐涛 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《征服2016》在线观看" title="《征服2016》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《征服2016》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">权利、利益、女人、金钱交织而成却又充斥着的整个氛围——黑帮。《征服2016》是一部男人情节浓厚的影片，本片主要描写的就是黑帮因利益而发生冲突后，黑帮内外的状...</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语</li>
<li class="yanyuan">主演：
<a href="/search/%E7%8E%8B%E5%87%AF" target="_blank">王凯</a> <a href="/search/%E5%94%90%E6%B6%9B" target="_blank">唐涛</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《征服2016》在线观看" title="《征服2016》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《征服2016》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/1459134515H030-23BD.jpg{/dede:field}
