{dede:field name='keywords'}南拳北腿之怒火营救,南拳{/dede:field}
{dede:field name='description'}最新电影《南拳北腿之怒火营救》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《南拳北腿之怒火营救》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收{/dede:field}
{dede:field name='title'}南拳北腿之怒火营救{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='daoyan'}胡登临{/dede:field}
{dede:field name='yanyuan'}白洁 卢鑫{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">早在洪荒时代，人魔两族为争夺世界，厮杀千年。人王“阳焰”通过天神遗落神器“灵血石”将魔族封印。但是，人间仍有残存魔族，他们并未死心，为了夺得灵血石，他们一直伺机窥望。走过千年，这个机密已被凡人遗忘，以教拳为生的南拳、北腿二人谨遵师训隐匿于俗世之中。不料城市中却发生多起离奇凶案，众多小孩遭到绑架。二人觉察到凶手与师傅临终前所诉机密极为相似，为了找出真相，二人重出江湖，暴走开打！</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160322/145V3326004M0-61403.jpg{/dede:field}
