<?php
$z[0]=Array("field","南拳北腿之怒火营救,南拳",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《南拳北腿之怒火营救》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《南拳北腿之怒火营救》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","南拳北腿之怒火营救",366,431);
$z[2][4]['name']="title";
$z[3]=Array("field","",433,472);
$z[3][4]['name']="writer";
$z[4]=Array("field","",474,513);
$z[4][4]['name']="source";
$z[5]=Array("field","10.0",515,559);
$z[5][4]['name']="pingfen";
$z[6]=Array("field","胡登临",561,609);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","白洁 卢鑫",611,664);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","2016",666,707);
$z[8][4]['name']="time";
$z[9]=Array("field","国语",709,753);
$z[9][4]['name']="yuyan";
$z[10]=Array("field","大陆",755,798);
$z[10][4]['name']="area";
$z[11]=Array("field","<span style=\"font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;\">早在洪荒时代，人魔两族为争夺世界，厮杀千年。人王“阳焰”通过天神遗落神器“灵血石”将魔族封印。但是，人间仍有残存魔族，他们并未死心，为了夺得灵血石，他们一直伺机窥望。走过千年，这个机密已被凡人遗忘，以教拳为生的南拳、北腿二人谨遵师训隐匿于俗世之中。不料城市中却发生多起离奇凶案，众多小孩遭到绑架。二人觉察到凶手与师傅临终前所诉机密极为相似，为了找出真相，二人重出江湖，暴走开打！</span>",800,1514);
$z[11][4]['name']="introduction";
$z[12]=Array("field","",1516,1557);
$z[12][4]['name']="download";
$z[13]=Array("field","",1559,1599);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V3326004M0-61403.jpg",1601,1695);
$z[14][4]['name']="litpic";

?>