<?php
$z[0]=Array("field","反黑行动组/反帮派,反黑行",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《反黑行动组/反帮派》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《反黑行动组/反帮派》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，",78,367);
$z[1][4]['name']="description";
$z[2]=Array("field","反黑行动组/反帮派",369,432);
$z[2][4]['name']="title";
$z[3]=Array("field","",434,473);
$z[3][4]['name']="writer";
$z[4]=Array("field","",475,514);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",516,557);
$z[5][4]['name']="time";
$z[6]=Array("field","Benjamin Rocher </li>\r\n<li class=\"info_dq\">地区：\r\n欧美",559,658);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","让·雷诺 卡特琳娜·莫里诺 蒂埃里·钮维",660,753);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",755,799);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">Serge Buren追踪不法分子方法很不一般。他与女同事有私情，而新上任的上司恰好又是同事的老公。在追踪珠宝抢劫犯的案中，上司把他的编队隔离出来，事后证明，这是劫匪的调虎离山计。他独自行动跟上犯人却遇到激励火拼，伤亡惨重，女同事死了，他是否可以用自己的方法破案呢？</span>",801,1340);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1342,1383);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",1385,1429);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","欧美",1431,1474);
$z[12][4]['name']="area";
$z[13]=Array("field","",1476,1516);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914C35164F-2K153.jpg",1518,1612);
$z[14][4]['name']="litpic";

?>