<?php
$z[0]=Array("field","最终复仇弓,最终复仇弓迅",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《最终复仇弓》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《最终复仇弓》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","最终复仇弓",366,419);
$z[2][4]['name']="title";
$z[3]=Array("field","",421,460);
$z[3][4]['name']="writer";
$z[4]=Array("field","",462,501);
$z[4][4]['name']="source";
$z[5]=Array("field","",503,543);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","10.0",545,589);
$z[6][4]['name']="pingfen";
$z[7]=Array("field","阳子政",591,639);
$z[7][4]['name']="daoyan";
$z[8]=Array("field","栗菡 李宜坤",641,697);
$z[8][4]['name']="yanyuan";
$z[9]=Array("field","2016",699,740);
$z[9][4]['name']="time";
$z[10]=Array("field","国语",742,786);
$z[10][4]['name']="yuyan";
$z[11]=Array("field","大陆",788,831);
$z[11][4]['name']="area";
$z[12]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">供职于省射箭队队员的纪冬,在妹妹纪雪遭遇强暴惨遭杀害后的复仇故事。独自找出租房的纪雪被暴力杀人狂向南残忍杀害,纪冬痛不欲生,为找到嫌疑人开始独立追查凶手。经过一番调查,终于将目标锁定在中介经理向南身上。向南性格极度扭曲,经常袭击夜归女子,并将她们强暴后无情杀害。一场复仇游戏由此开始</span>",833,1406);
$z[12][4]['name']="introduction";
$z[13]=Array("field","",1408,1449);
$z[13][4]['name']="download";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V332L135F-1R148.jpg",1451,1544);
$z[14][4]['name']="litpic";

?>