<?php
$z[0]=Array("field","八项注意之泡我女儿没那",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《八项注意之泡我女儿没那么容易/泡我千金有规矩第一季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《八项注意之泡我女儿没那么容易/泡我千金有规矩第一",76,365);
$z[1][4]['name']="description";
$z[2]=Array("field","八项注意之泡我女儿没那么容易/泡我千金有规矩第一季",367,478);
$z[2][4]['name']="title";
$z[3]=Array("field","",480,519);
$z[3][4]['name']="writer";
$z[4]=Array("field","",521,560);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",562,603);
$z[5][4]['name']="time";
$z[6]=Array("field","Tracy Gamble",605,656);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","凯莉·库柯 凯特蕾·萨加尔",658,733);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",735,779);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","",781,826);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",828,869);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",871,915);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","美剧",917,960);
$z[12][4]['name']="area";
$z[13]=Array("field","",962,1002);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914NDQ1F-4W16.jpg",1004,1095);
$z[14][4]['name']="litpic";

?>