{dede:field name='keywords'}致命怪谈,致命怪谈迅雷下{/dede:field}
{dede:field name='description'}最新电影《致命怪谈》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《致命怪谈》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共{/dede:field}
{dede:field name='title'}致命怪谈{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='daoyan'}依平{/dede:field}
{dede:field name='yanyuan'}刘青 周浩东 苏婷 杨海超 魏建云{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">妙龄少女天天（刘青 饰）因为童年阴影患上了严重的广场恐惧症，一直把自己锁闭在家中。一天一觉醒来她突然发现自己被关在血腥的禁闭囚室中，耳边传来阵阵磨刀声和惨烈的嘶叫声，隔壁的囚禁者一个个的被面具杀人魔残虐而死，天天即将成为下一个目标……</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160322/145V333Zc3Z-63613.jpg{/dede:field}
