{dede:field name='keywords'}南拳北腿之怒火营救,南拳{/dede:field}
{dede:field name='description'}最新电影《南拳北腿之怒火营救》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《南拳北腿之怒火营救》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收{/dede:field}
{dede:field name='title'}南拳北腿之怒火营救电影迅雷高清下载,南拳北腿之怒火营救高清下载在线观看 - 大陆 - a67手机电影网{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}胡登临 </li>
<li class="info_dq">地区：
大陆{/dede:field}
{dede:field name='yanyuan'}白洁 卢鑫 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《南拳北腿之怒火营救》在线观看" title="《南拳北腿之怒火营救》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《南拳北腿之怒火营救》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">早在洪荒时代，人魔两族为争夺世界，厮杀千年。人王“阳焰”通过天神遗落神器“灵血石”将魔族封印。但是，人间仍有残存魔族，他们并未死心，为了夺得灵血石，他们一直伺机窥望。走过千年，这个机密已被凡人遗忘，以教拳为生的南拳、北腿二人谨遵师训隐匿于俗世之中。不料城市中却发生多起离奇凶案，众多小孩遭到绑架。二人觉察到凶手与师傅临终前所诉机密极为相似，为了找出真相，二人重出江湖，暴走开打！</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语</li>
<li class="yanyuan">主演：
<a href="/search/%E7%99%BD%E6%B4%81" target="_blank">白洁</a> <a href="/search/%E5%8D%A2%E9%91%AB" target="_blank">卢鑫</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《南拳北腿之怒火营救》在线观看" title="《南拳北腿之怒火营救》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《南拳北腿之怒火营救》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/14591343a95460-63314.jpg{/dede:field}
