<?php
$z[0]=Array("field","城市不知我哭泣,城市不知",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《城市不知我哭泣》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《城市不知我哭泣》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","城市不知我哭泣",366,425);
$z[2][4]['name']="title";
$z[3]=Array("field","",427,466);
$z[3][4]['name']="writer";
$z[4]=Array("field","",468,507);
$z[4][4]['name']="source";
$z[5]=Array("field","",509,549);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","10.0",551,595);
$z[6][4]['name']="pingfen";
$z[7]=Array("field","袁一木",597,645);
$z[7][4]['name']="daoyan";
$z[8]=Array("field","田子琳 郝旭晖 马鑫鑫 周莹",647,723);
$z[8][4]['name']="yanyuan";
$z[9]=Array("field","2016",725,766);
$z[9][4]['name']="time";
$z[10]=Array("field","国语",768,812);
$z[10][4]['name']="yuyan";
$z[11]=Array("field","大陆",814,857);
$z[11][4]['name']="area";
$z[12]=Array("field","<span style=\"font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;\">农村女孩边菲菲在大学毕业后，发誓要自己走出一片天地，改变自己的人生。可面对纷繁复杂的社会，和尔虞我诈的人间是非，边菲菲真是感到很难很难。从求职屡屡受挫，到当上饭店普通服务员。好朋友的出现改变了她的一切，她从车模到堕落的糜烂生活，很长一段时间里，边菲菲沉浸在纸醉金迷的世界里，而她却在糜烂的生活中一次次受到伤害，让她在一次事件中彻底懂了人生的真谛。她决定改变自己，用自己的双手撑起一片属于自己的蓝天，时尚内涵携带着对梦想的追求，或许一片新的蓝天会呈现在她的面前--</span>",859,1695);
$z[12][4]['name']="introduction";
$z[13]=Array("field","",1697,1738);
$z[13][4]['name']="download";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V33264220F-b443.jpg",1740,1833);
$z[14][4]['name']="litpic";

?>