{dede:field name='keywords'}我的国王/我心深爱的国王{/dede:field}
{dede:field name='description'}最新电影《我的国王/我心深爱的国王》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《我的国王/我心深爱的国王》完整版迅雷高清下载，以及高清在线播放，轻轻一点{/dede:field}
{dede:field name='title'}我的国王/我心深爱的国王电影迅雷高清下载,我的国王/我心深爱的国王高清下载在线观看 - 欧美 - a67手机电影网{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}麦温·勒·贝斯柯 </li>
<li class="info_dq">地区：
欧美{/dede:field}
{dede:field name='yanyuan'}艾玛纽尔·贝克特 文森特·卡索 路易·加瑞尔 伊希尔·勒·贝斯柯 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《我的国王/我心深爱的国王》在线观看" title="《我的国王/我心深爱的国王》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《我的国王/我心深爱的国王》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}9.5{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">影片由法国女导演麦温执导，法国巨星文森特·卡索搭档法国女星艾玛纽尔·贝克特和法国男星路易·加瑞尔出演，影片入围第68届法国戛纳电影节主竞赛单元。值得一提的是，文森特·卡索也有出演入围主竞赛的《故事的故事》，而艾玛纽尔·贝克特执导的影片《昂首挺胸》被选为本届电影节的开幕片 。　　女律师汤妮（Emmanuelle Bercot饰）滑雪受伤疗养时，回忆起她曾经历过的一段刻骨铭心爱情。她爱上了迷人的餐厅经理乔治欧（Vincent Cassel饰），两人从相互吸引、陷入热恋、甜蜜闪婚到天翻地覆的疯狂毁灭…。而她的疗伤过程，也不断地与这些感情经历相互对映，让观众彷彿置身其中、感同身受，前一秒才纵情欢笑、干柴烈火，下一秒却忌恨争执、甚至大打出手。当爱情从热恋跨向婚姻，究竟该是浓郁的幸福？抑或是烦苦的羁绊？</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}其他</li>
<li class="yanyuan">主演：
<a href="/search/%E8%89%BE%E7%8E%9B%E7%BA%BD%E5%B0%94%C2%B7%E8%B4%9D%E5%85%8B%E7%89%B9" target="_blank">艾玛纽尔·贝克特</a> <a href="/tag/3709/" target="_blank">文森特·卡索</a> <a href="/search/%E8%B7%AF%E6%98%93%C2%B7%E5%8A%A0%E7%91%9E%E5%B0%94" target="_blank">路易·加瑞尔</a> <a href="/search/%E4%BC%8A%E5%B8%8C%E5%B0%94%C2%B7%E5%8B%92%C2%B7%E8%B4%9D%E6%96%AF%E6%9F%AF" target="_blank">伊希尔·勒·贝斯柯</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《我的国王/我心深爱的国王》在线观看" title="《我的国王/我心深爱的国王》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《我的国王/我心深爱的国王》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}欧美{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/14591345022F50-1I349.jpg{/dede:field}
