{dede:field name='keywords'}阴阳诡捕之黄妖迷情,阴阳{/dede:field}
{dede:field name='description'}最新电影《阴阳诡捕之黄妖迷情》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《阴阳诡捕之黄妖迷情》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收{/dede:field}
{dede:field name='title'}阴阳诡捕之黄妖迷情{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='pingfen'}3.2{/dede:field}
{dede:field name='daoyan'}李巨涛{/dede:field}
{dede:field name='yanyuan'}杨玥 宫海滨{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">上世纪30年代，留洋归国的北宫琉璃不顾家人反对毅然加入警局，与警队队长林豹成为搭档，携手维护一方平安。一日，一桩诡异的凶杀案打破了往日的宁静，看似遭人毒手惨死的富贾.</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160322/145V332H94W0-161537.jpg{/dede:field}
