<?php
$z[0]=Array("field","检察官外传/检师外传,检察",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《检察官外传/检师外传》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《检察官外传/检师外传》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a6",78,363);
$z[1][4]['name']="description";
$z[2]=Array("field","检察官外传/检师外传",365,431);
$z[2][4]['name']="title";
$z[3]=Array("field","",433,472);
$z[3][4]['name']="writer";
$z[4]=Array("field","",474,513);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",515,556);
$z[5][4]['name']="time";
$z[6]=Array("field","李日炯 </li>\r\n<li class=\"info_dq\">地区：\r\n日韩",558,651);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","黄政民 姜东元 李成民 朴圣雄 申素率",653,742);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",744,788);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">投资发行公司Showbox透露，韩国演员黄政民将主演李日炯导演的新片《检察官外传》，该片是由《群盗：民乱的时代》的“月狂”制作公司和“男子汉电影”公司共同制作。 　　《检察官外传》讲述的是背负着杀人犯罪名冤枉入狱的检察官，聚集了一群有才能的犯罪者，对黑社会组织进行复仇的故事。黄政民在片中饰演男主人公。 　　今年年末黄政民主演的尹济均导演新片《国际市场》即将上映，而黄政民目前正在拍摄罗宏镇导演的《谷城》，之后还将主演李石勋导演的《喜马拉雅》，之后才会拍摄《检察官外传》。2014年末到2015年的日程都排满了，也印证了黄政民在韩国电影界的超高人气。 　　《检察官外传》预计会在2015年上映。</span>",790,1799);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1801,1842);
$z[10][4]['name']="download";
$z[11]=Array("field","韩语",1844,1888);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","日韩",1890,1933);
$z[12][4]['name']="area";
$z[13]=Array("field","",1935,1975);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914C33M620-2DL9.jpg",1977,2070);
$z[14][4]['name']="litpic";

?>