{dede:field name='keywords'}检察官外传/检师外传,检察{/dede:field}
{dede:field name='description'}最新电影《检察官外传/检师外传》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《检察官外传/检师外传》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a6{/dede:field}
{dede:field name='title'}检察官外传/检师外传{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}李日炯 </li>
<li class="info_dq">地区：
日韩{/dede:field}
{dede:field name='yanyuan'}黄政民 姜东元 李成民 朴圣雄 申素率{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">投资发行公司Showbox透露，韩国演员黄政民将主演李日炯导演的新片《检察官外传》，该片是由《群盗：民乱的时代》的“月狂”制作公司和“男子汉电影”公司共同制作。 　　《检察官外传》讲述的是背负着杀人犯罪名冤枉入狱的检察官，聚集了一群有才能的犯罪者，对黑社会组织进行复仇的故事。黄政民在片中饰演男主人公。 　　今年年末黄政民主演的尹济均导演新片《国际市场》即将上映，而黄政民目前正在拍摄罗宏镇导演的《谷城》，之后还将主演李石勋导演的《喜马拉雅》，之后才会拍摄《检察官外传》。2014年末到2015年的日程都排满了，也印证了黄政民在韩国电影界的超高人气。 　　《检察官外传》预计会在2015年上映。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}韩语{/dede:field}
{dede:field name='area'}日韩{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914C33M620-2DL9.jpg{/dede:field}
