<?php
$z[0]=Array("global","",12,37);
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",59,74);
$z[2]=Array("litpic","",115,130);
$z[3]=Array("title","",151,165);
$z[4]=Array("yuyan","",187,201);
$z[5]=Array("arcurl","",228,243);
$z[6]=Array("title","",261,275);
$z[7]=Array("global","",304,332);
$z[7][4]['name']="cfg_plus_dir";
$z[8]=Array("id","",361,372);
$z[9]=Array("pingfen","",444,460);

?>