{dede:noteinfo notename="电影" channelid="18" macthtype="string"
    refurl="http://www.a67.com/movie/434950" sourcelang="utf-8" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.a67.com/movie/p.(*)"
startid="2" endid="3" addv="1" urlrule="area" musthas=""
 nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="list_p">
{/dede:areastart}
    {dede:areaend}</div>
<div class="pages">{/dede:areaend}
{/dede:listrule}
