<?php
$z[0]=Array("field","兄弟,兄弟迅雷下载,兄弟高",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《兄弟》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《兄弟》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共同享受下",78,365);
$z[1][4]['name']="description";
$z[2]=Array("field","兄弟",367,411);
$z[2][4]['name']="title";
$z[3]=Array("field","",413,452);
$z[3][4]['name']="writer";
$z[4]=Array("field","",454,493);
$z[4][4]['name']="source";
$z[5]=Array("field","10.0",495,539);
$z[5][4]['name']="pingfen";
$z[6]=Array("field","Aslaug Holm",541,591);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","Aslaug Holm",593,644);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","2016",646,687);
$z[8][4]['name']="time";
$z[9]=Array("field","英语",689,733);
$z[9][4]['name']="yuyan";
$z[10]=Array("field","欧美",735,778);
$z[10][4]['name']="area";
$z[11]=Array("field","<span style=\"font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;\">14岁的马库斯和11岁的卢卡斯住在奥斯陆中部的一座古老的房子里，房子边有条河，河边的参天大树和水中的神秘都对两人的童年有着无限的吸引力。这里就是大城市中心的天堂，他们在这里成长，在这里憧憬未来。马库斯热爱足球，并希望可以成为职业选手。他从五岁就开始踢球，而进入最棒的利物浦球队是他的梦想。那么他的努力奋斗终有结果吗？卢卡斯喜欢思考，思考他自己，思考整个世界。他问妈妈：“在我死后，我的梦想也会随我死去吗？”</span>",780,1528);
$z[11][4]['name']="introduction";
$z[12]=Array("field","",1530,1571);
$z[12][4]['name']="download";
$z[13]=Array("field","",1573,1613);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V3325JE60-41507.jpg",1615,1708);
$z[14][4]['name']="litpic";

?>