<?php
$z[0]=Array("field","示铃录,示铃录电视剧,示铃",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《示铃录》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《示铃录》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共同",78,365);
$z[1][4]['name']="description";
$z[2]=Array("field","示铃录",367,414);
$z[2][4]['name']="title";
$z[3]=Array("field","",416,455);
$z[3][4]['name']="writer";
$z[4]=Array("field","",457,496);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",498,539);
$z[5][4]['name']="time";
$z[6]=Array("field","林楠",541,586);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","许景媛 孟阿塞 李乃文 李宗翰 王美人 朱杰",588,684);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","8.0",686,729);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;\">季棠棠的母亲是上一代路铃掌铃人盛清屏，被父亲秦守成欺骗感情，逃离盛家，生下盛夏后被秦家害死。作为下一任路铃掌铃人的季棠棠在母亲被杀害后独自踏上旅途，棠棠拥有着不为人所知的神奇超能力，她一路调查与冒险。在途中结识了男主角岳峰，与岳峰一路斗嘴却又惺惺相惜，并在岳峰等人的帮助下，一步一步揭开盛家、秦家、石家三大家族间百年恩怨的故事。</span>",731,1370);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1372,1413);
$z[10][4]['name']="download";
$z[11]=Array("field","国语",1415,1459);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","大陆",1461,1504);
$z[12][4]['name']="area";
$z[13]=Array("field","",1506,1546);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914N1b20-O012.jpg",1548,1639);
$z[14][4]['name']="litpic";

?>