{dede:field name='keywords'}示铃录,示铃录电视剧,示铃{/dede:field}
{dede:field name='description'}最新电视剧《示铃录》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《示铃录》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共同{/dede:field}
{dede:field name='title'}示铃录{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}林楠{/dede:field}
{dede:field name='yanyuan'}许景媛 孟阿塞 李乃文 李宗翰 王美人 朱杰{/dede:field}
{dede:field name='pingfen'}8.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">季棠棠的母亲是上一代路铃掌铃人盛清屏，被父亲秦守成欺骗感情，逃离盛家，生下盛夏后被秦家害死。作为下一任路铃掌铃人的季棠棠在母亲被杀害后独自踏上旅途，棠棠拥有着不为人所知的神奇超能力，她一路调查与冒险。在途中结识了男主角岳峰，与岳峰一路斗嘴却又惺惺相惜，并在岳峰等人的帮助下，一步一步揭开盛家、秦家、石家三大家族间百年恩怨的故事。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914N1b20-O012.jpg{/dede:field}
