<?php
$z[0]=Array("field","纹身室,纹身室迅雷下载",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《纹身室》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《纹身室》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共同享",74,361);
$z[1][4]['name']="description";
$z[2]=Array("field","纹身室",363,410);
$z[2][4]['name']="title";
$z[3]=Array("field","",412,451);
$z[3][4]['name']="writer";
$z[4]=Array("field","",453,492);
$z[4][4]['name']="source";
$z[5]=Array("field","6.7",494,537);
$z[5][4]['name']="pingfen";
$z[6]=Array("field","Devon Downs Kenny Gage",539,600);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","Robert LaSardo Anthony Del Negro 乔丹·詹姆斯·史密斯 Claire Garvey",602,717);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","2016",719,760);
$z[8][4]['name']="time";
$z[9]=Array("field","英语",762,806);
$z[9][4]['name']="yuyan";
$z[10]=Array("field","欧美",808,851);
$z[10][4]['name']="area";
$z[11]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">一个神秘的游牧称为“艺术家”实践黑暗的艺术形式相传</span>",853,1090);
$z[11][4]['name']="introduction";
$z[12]=Array("field","",1092,1133);
$z[12][4]['name']="download";
$z[13]=Array("field","",1135,1175);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V332O43130-2043B.jpg",1177,1271);
$z[14][4]['name']="litpic";

?>