<?php
$z[0]=Array("field","最后一个道士的往事,最后",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《最后一个道士的往事》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《最后一个道士的往事》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","最后一个道士的往事",366,431);
$z[2][4]['name']="title";
$z[3]=Array("field","",433,472);
$z[3][4]['name']="writer";
$z[4]=Array("field","",474,513);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",515,556);
$z[5][4]['name']="time";
$z[6]=Array("field","林育塘 </li>\r\n<li class=\"info_dq\">地区：\r\n大陆",558,651);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","廉捷 高天景",653,709);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","6.7",711,754);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">住在城里的夏家闹鬼，于是寻找有本事捉鬼降妖的人，陈言谷（马宗彬 饰）闻讯带着两徒弟进城捉鬼。帮夏家驱除恶鬼之后，陈言谷得到100万。而师傅从此出去花天酒地。不顾两个徒弟刘梦阳（廉捷 饰）、顾博（高天景 饰）。而顾博则想办法偷到了师傅钱箱的钥匙，骗师弟一起去城里。路上顾博耍心机带钱跑了，留下了刘梦阳一人。刘梦阳走投无路到了足疗店工作，不巧又碰到师兄，却发现师兄不学正道跑入偏门，为了解救师兄，刘梦阳展开了一系列的行动……</span>",756,1536);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1538,1579);
$z[10][4]['name']="download";
$z[11]=Array("field","国语",1581,1625);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","大陆",1627,1670);
$z[12][4]['name']="area";
$z[13]=Array("field","",1672,1712);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914C10I430-10Cb.jpg",1714,1807);
$z[14][4]['name']="litpic";

?>