{dede:field name='keywords'}紫色大稻埕,紫色大稻埕电{/dede:field}
{dede:field name='description'}最新电视剧《紫色大稻埕》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《紫色大稻埕》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的{/dede:field}
{dede:field name='title'}紫色大稻埕{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}叶天伦 陈长纶{/dede:field}
{dede:field name='yanyuan'}施易男 柯佳嬿 林玟谊 曾子益{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">本片主要是在讲述1920年代台湾日治时代画家，以“台阳美展”的画家为主，像是杨三郎及陈澄波等画家的故事。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}港台{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914N14310F-394U.jpg{/dede:field}
