<?php
$z[0]=Array("field","紫色大稻埕,紫色大稻埕电",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《紫色大稻埕》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《紫色大稻埕》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","紫色大稻埕",366,419);
$z[2][4]['name']="title";
$z[3]=Array("field","",421,460);
$z[3][4]['name']="writer";
$z[4]=Array("field","",462,501);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",503,544);
$z[5][4]['name']="time";
$z[6]=Array("field","叶天伦 陈长纶",546,604);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","施易男 柯佳嬿 林玟谊 曾子益",606,685);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",687,731);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;\">本片主要是在讲述1920年代台湾日治时代画家，以“台阳美展”的画家为主，像是杨三郎及陈澄波等画家的故事。</span>",733,1028);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1030,1071);
$z[10][4]['name']="download";
$z[11]=Array("field","国语",1073,1117);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","港台",1119,1162);
$z[12][4]['name']="area";
$z[13]=Array("field","",1164,1204);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914N14310F-394U.jpg",1206,1299);
$z[14][4]['name']="litpic";

?>