<?php
$z[0]=Array("field","薛定谔的猫,薛定谔的猫迅",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《薛定谔的猫》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《薛定谔的猫》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","薛定谔的猫",366,419);
$z[2][4]['name']="title";
$z[3]=Array("field","",421,460);
$z[3][4]['name']="writer";
$z[4]=Array("field","",462,501);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",503,544);
$z[5][4]['name']="time";
$z[6]=Array("field","冯桂云 </li>\r\n<li class=\"info_dq\">地区：\r\n大陆",546,639);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","阮晓伟 王馨瑶",641,700);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",702,746);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">归国当天意外邂逅了身着古装戏的替身艾金，尾随着艾金而后进入了片场并且见识到了国内的拍戏方式。之后，晓艺在酒吧里被国内的旧友Tony跟笑笑灌输追女孩子的方法。Tony是个典型的“快餐爱情”消费者，无时无刻都在运用自己的科学理论泡妞，无时无刻都处于猎艳的状态，为了让晓艺成功追上艾金，Tony教授给晓艺一个理论——“薛定谔的猫”（把猫关在一个放置毒气开关的箱子里，猫的死活取决于你打开箱子那瞬间，在没打开箱子之前，猫处于一种“即生又死”的状态）晓艺根据Tony的理论对艾金展开追求攻势，在眼看得手之际，艾金却没接受晓艺。</span>",748,1652);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1654,1695);
$z[10][4]['name']="download";
$z[11]=Array("field","国语",1697,1741);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","大陆",1743,1786);
$z[12][4]['name']="area";
$z[13]=Array("field","",1788,1828);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914C1916040-1AC1.jpg",1830,1924);
$z[14][4]['name']="litpic";

?>