{dede:field name='keywords'}震荡效应,震荡效应迅雷下{/dede:field}
{dede:field name='description'}最新电影《震荡效应》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《震荡效应》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共{/dede:field}
{dede:field name='title'}震荡效应{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2015{/dede:field}
{dede:field name='daoyan'}彼得·兰德斯曼 Peter Landesman </li>
<li class="info_dq">地区：
欧美{/dede:field}
{dede:field name='yanyuan'}威尔·史密斯 Will Smith  亚历克·鲍德温 Alec Baldwin{/dede:field}
{dede:field name='pingfen'}9.3{/dede:field}
{dede:field name='introduction'}<p>
	<div>
		◎导　　演　彼得·兰德斯曼 Peter Landesman
	</div>
	<div>
		◎主　　演　威尔·史密斯 Will Smith
	</div>
	<div>
		亚历克·鲍德温 Alec Baldwin
	</div>
	<div>
		古古·姆巴塔-劳 Gugu Mbatha-Raw
	</div>
	<div>
		艾利斯·霍华德 Arliss Howard
	</div>
	<div>
		卢克·威尔逊 Luke Wilson
	</div>
	<div>
		保罗·雷瑟 Paul Reiser
	</div>
	<div>
		阿德沃尔·阿吉纽依-艾格拜吉 Adewale Akinnuoye-Agbaje
	</div>
	<div>
		大卫·摩斯 David Morse
	</div>
	<div>
		艾伯特·布鲁克斯 Albert Brooks
	</div>
	<div>
		麦克·奥麦利 Mike O'Malley
	</div>
	<div>
		埃迪·马森 Eddie Marsan
	</div>
	<div>
		史蒂芬·莫耶 Stephen Moyer
	</div>
	<div>
		理查德·琼斯 Richard T. Jones
	</div>
	<div>
		希尔·哈勃 Hill Harper
	</div>
	<div>
		比茜·图诺克 Bitsie Tulloch
	</div>
	<div>
		马修·维利希 Matthew Willig
	</div>
</p>
<p>
	改编自珍妮·玛丽·拉斯卡斯于2009年在《GQ》上发表的文章《Game 
Brain》。电影主要描述脑神经学医生班奈特·奥玛鲁最先发现到运动员容易罹患一种慢性创伤性脑病（CTE），会使该运动员产生自杀念头。
</p>
<div>
	故事改编自真实事件，叙述班奈特·奥玛鲁是一名美国脑神经学医生，他是首位发现美式橄榄球员高概率会因职业缘故而造成脑部慢性病变，便决定将此研究公诸于世。但此研究却遭国家美式橄榄球联盟强烈否认，使得班奈特将面临对事业造成强烈冲击的危机。{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}英语{/dede:field}
{dede:field name='area'}欧美{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914BW195Z-25W03.jpg{/dede:field}
