
<field:time itemname="上映时间" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="16" page="">
</field:time>

<field:daoyan itemname="导演" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="50" page="">
</field:daoyan>

<field:yanyuan itemname="演员" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="50" page="">
</field:yanyuan>

<field:pingfen itemname="评分" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="0"  maxlength="50" page="">
</field:pingfen>

<field:introduction itemname="简介" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="1024" page="">
</field:introduction>
