
<field:pingfen itemname="评分" autofield="1" notsend="0" type="float" isnull="true" islist="0" default=""  maxlength="16" page="">
</field:pingfen>

<field:daoyan itemname="导演" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="16" page="">
</field:daoyan>

<field:yanyuan itemname="演员" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="52" page="">
</field:yanyuan>

<field:time itemname="上映时间" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="20" page="">
</field:time>
