{dede:field name='keywords'}反黑行动组/反帮派,反黑行{/dede:field}
{dede:field name='description'}最新电影《反黑行动组/反帮派》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《反黑行动组/反帮派》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，{/dede:field}
{dede:field name='title'}反黑行动组/反帮派电影迅雷高清下载,反黑行动组/反帮派高清下载在线观看 - 欧美 - a67手机电影网{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}Benjamin Rocher </li>
<li class="info_dq">地区：
欧美{/dede:field}
{dede:field name='yanyuan'}让·雷诺 卡特琳娜·莫里诺 蒂埃里·钮维 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《反黑行动组/反帮派》在线观看" title="《反黑行动组/反帮派》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《反黑行动组/反帮派》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">Serge Buren追踪不法分子方法很不一般。他与女同事有私情，而新上任的上司恰好又是同事的老公。在追踪珠宝抢劫犯的案中，上司把他的编队隔离出来，事后证明，这是劫匪的调虎离山计。他独自行动跟上犯人却遇到激励火拼，伤亡惨重，女同事死了，他是否可以用自己的方法破案呢？</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}英语</li>
<li class="yanyuan">主演：
<a href="/tag/1363/" target="_blank">让·雷诺</a> <a href="/search/%E5%8D%A1%E7%89%B9%E7%90%B3%E5%A8%9C%C2%B7%E8%8E%AB%E9%87%8C%E8%AF%BA" target="_blank">卡特琳娜·莫里诺</a> <a href="/search/%E8%92%82%E5%9F%83%E9%87%8C%C2%B7%E9%92%AE%E7%BB%B4" target="_blank">蒂埃里·钮维</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《反黑行动组/反帮派》在线观看" title="《反黑行动组/反帮派》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《反黑行动组/反帮派》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}欧美{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/14591344U09450-5B33.jpg{/dede:field}
