{dede:field name='keywords'}再见了德彪西～钢琴侦探{/dede:field}
{dede:field name='description'}最新电影《再见了德彪西～钢琴侦探岬洋介》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《再见了德彪西～钢琴侦探岬洋介》完整版迅雷高清下载，以及高清在线播{/dede:field}
{dede:field name='title'}再见了德彪西～钢琴侦探岬洋介电影迅雷高清下载,再见了德彪西～钢琴侦探岬洋介高清下载在线观看 - 日韩 - a67手机电影网{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}菅原伸太郎 </li>
<li class="info_dq">地区：
日韩{/dede:field}
{dede:field name='yanyuan'}东出昌大 黑岛结菜 北大路欣也 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《再见了德彪西～钢琴侦探岬洋介》在线观看" title="《再见了德彪西～钢琴侦探岬洋介》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《再见了德彪西～钢琴侦探岬洋介》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">该剧改编自获得第八届“这本推理小说真了不起”大奖的中山七里的畅销作品《再见了德彪西》，2013年曾被翻拍成电影，由桥本爱主演。电视剧中，左耳突然失聪的天才钢琴师、名侦探岬洋介针对发生在其钢琴课女学生（黑岛结菜）身边的事件进行侦查和破解。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}日语</li>
<li class="yanyuan">主演：
<a href="/search/%E4%B8%9C%E5%87%BA%E6%98%8C%E5%A4%A7" target="_blank">东出昌大</a> <a href="/search/%E9%BB%91%E5%B2%9B%E7%BB%93%E8%8F%9C" target="_blank">黑岛结菜</a> <a href="/search/%E5%8C%97%E5%A4%A7%E8%B7%AF%E6%AC%A3%E4%B9%9F" target="_blank">北大路欣也</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《再见了德彪西～钢琴侦探岬洋介》在线观看" title="《再见了德彪西～钢琴侦探岬洋介》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《再见了德彪西～钢琴侦探岬洋介》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}日韩{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/1459134493a40-113544.jpg{/dede:field}
