<?php
$z[0]=Array("field","美女主播惊魂记,美女主播",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《美女主播惊魂记》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《美女主播惊魂记》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","美女主播惊魂记",366,425);
$z[2][4]['name']="title";
$z[3]=Array("field","",427,466);
$z[3][4]['name']="writer";
$z[4]=Array("field","",468,507);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",509,550);
$z[5][4]['name']="time";
$z[6]=Array("field","张睿龙 </li>\r\n<li class=\"info_dq\">地区：\r\n大陆",552,645);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","TAMMY甜蜜 刘小婉",647,708);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","9.5",710,753);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">两位网络美女女主播，泰国女孩塔米和中国女孩海伦，被绑架于一个仓库里。一小时前塔米在她家洗澡时被绑架，海伦在网络公司下班后在公司门外被绑走。她们被绑架后苦苦回忆却依..</span>",755,1162);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1164,1205);
$z[10][4]['name']="download";
$z[11]=Array("field","国语",1207,1251);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","大陆",1253,1296);
$z[12][4]['name']="area";
$z[13]=Array("field","",1298,1338);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914BHN4F-151493.jpg",1340,1433);
$z[14][4]['name']="litpic";

?>