{dede:field name='keywords'}星球大战7:原力觉醒,星球{/dede:field}
{dede:field name='description'}最新电影《星球大战7:原力觉醒》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《星球大战7:原力觉醒》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏{/dede:field}
{dede:field name='title'}星球大战7:原力觉醒{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2014{/dede:field}
{dede:field name='daoyan'}J·J·艾布拉姆斯 </li>
<li class="info_dq">地区：
欧美{/dede:field}
{dede:field name='yanyuan'}HarrionFord MarkHamill CarrieFiher AnthonyDaniel BillyDeeWilliam{/dede:field}
{dede:field name='pingfen'}6.8{/dede:field}
{dede:field name='introduction'}<div>
	外媒曝出消息，《星战7》将于2014年1月21日开拍（此前消息称拍摄地在伦敦的松林制片厂），2015年圣诞节（12月25日）上映。{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}英语{/dede:field}
{dede:field name='area'}欧美{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914BT4D40-234Q8.jpg{/dede:field}
