<?php
$z[0]=Array("field","星球大战7:原力觉醒,星球",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《星球大战7:原力觉醒》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《星球大战7:原力觉醒》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏",76,364);
$z[1][4]['name']="description";
$z[2]=Array("field","星球大战7:原力觉醒",366,430);
$z[2][4]['name']="title";
$z[3]=Array("field","",432,471);
$z[3][4]['name']="writer";
$z[4]=Array("field","",473,512);
$z[4][4]['name']="source";
$z[5]=Array("field","2014",514,555);
$z[5][4]['name']="time";
$z[6]=Array("field","J·J·艾布拉姆斯 </li>\r\n<li class=\"info_dq\">地区：\r\n欧美",557,662);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","HarrionFord MarkHamill CarrieFiher AnthonyDaniel BillyDeeWilliam",664,768);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","6.8",770,813);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<div>\r\n	外媒曝出消息，《星战7》将于2014年1月21日开拍（此前消息称拍摄地在伦敦的松林制片厂），2015年圣诞节（12月25日）上映。",815,1031);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1033,1074);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",1076,1120);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","欧美",1122,1165);
$z[12][4]['name']="area";
$z[13]=Array("field","",1167,1207);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914BT4D40-234Q8.jpg",1209,1302);
$z[14][4]['name']="litpic";

?>