{dede:field name='keywords'}春花望露,春花望露电视剧{/dede:field}
{dede:field name='description'}最新电视剧《春花望露》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《春花望露》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友{/dede:field}
{dede:field name='title'}春花望露{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}陈朱煌{/dede:field}
{dede:field name='yanyuan'}萧大陆 叶欢 方馨 张铭杰 楚宣{/dede:field}
{dede:field name='pingfen'}5.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:Simsun;font-size:medium;line-height:normal;white-space:normal;">《春花望露》为台湾民视制播的八点档连续剧。此剧以1950至1980年代的台湾为故事背景，刻划出台湾人努力奋斗的精神。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}港台{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914O0H1c0-232O4.jpg{/dede:field}
