<?php
$z[0]=Array("field","春花望露,春花望露电视剧",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《春花望露》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《春花望露》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","春花望露",366,416);
$z[2][4]['name']="title";
$z[3]=Array("field","",418,457);
$z[3][4]['name']="writer";
$z[4]=Array("field","",459,498);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",500,541);
$z[5][4]['name']="time";
$z[6]=Array("field","陈朱煌",543,591);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","萧大陆 叶欢 方馨 张铭杰 楚宣",593,673);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","5.0",675,718);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:Simsun;font-size:medium;line-height:normal;white-space:normal;\">《春花望露》为台湾民视制播的八点档连续剧。此剧以1950至1980年代的台湾为故事背景，刻划出台湾人努力奋斗的精神。</span>",720,1019);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1021,1062);
$z[10][4]['name']="download";
$z[11]=Array("field","国语",1064,1108);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","港台",1110,1153);
$z[12][4]['name']="area";
$z[13]=Array("field","",1155,1195);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914O0H1c0-232O4.jpg",1197,1290);
$z[14][4]['name']="litpic";

?>