<?php
$z[0]=Array("field","降魔传,降魔传迅雷下载",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《降魔传》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《降魔传》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共同享",74,361);
$z[1][4]['name']="description";
$z[2]=Array("field","降魔传",363,410);
$z[2][4]['name']="title";
$z[3]=Array("field","",412,451);
$z[3][4]['name']="writer";
$z[4]=Array("field","",453,492);
$z[4][4]['name']="source";
$z[5]=Array("field","10.0",494,538);
$z[5][4]['name']="pingfen";
$z[6]=Array("field","未知",540,585);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","于歌 傅筱",587,640);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","2016",642,683);
$z[8][4]['name']="time";
$z[9]=Array("field","国语",685,729);
$z[9][4]['name']="yuyan";
$z[10]=Array("field","大陆",731,774);
$z[10][4]['name']="area";
$z[11]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">在中国几千年的文化传承中流传着诸多人、神、妖三界有关的玄幻故事传说如《白娘子传奇》《八仙过海》等等，人们总是对玄幻的世界充满了好奇。《降魔传》则讲述了道教弟子——看护太合殿太衡宝盒的道童张小虎因心慈善怜，相信了美丽兔妖的百般请求，意外开启了尘封已久关押着众妖的太衡宝盒，导致被镇压的众妖四散奔逃且纷纷逃到了结界之外，重现人间。张小虎带着师傅所赐的玉佩进城助其寻找有缘人方可一举降服群妖。</span>",776,1517);
$z[11][4]['name']="introduction";
$z[12]=Array("field","",1519,1560);
$z[12][4]['name']="download";
$z[13]=Array("field","",1562,1602);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V332P62a0-21aU.jpg",1604,1696);
$z[14][4]['name']="litpic";

?>