<?php
$z[0]=Array("field","王的美人之野蛮人乱入,王",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《王的美人之野蛮人乱入》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《王的美人之野蛮人乱入》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","王的美人之野蛮人乱入",366,434);
$z[2][4]['name']="title";
$z[3]=Array("field","",436,475);
$z[3][4]['name']="writer";
$z[4]=Array("field","",477,516);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",518,559);
$z[5][4]['name']="time";
$z[6]=Array("field","陈鹏翱 </li>\r\n<li class=\"info_dq\">地区：\r\n大陆",561,654);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","赵波 姬天宇",656,712);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",714,758);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">波诡云谲的资本市场上，国内一线地产商万石地产突然被一股来历不明的资金收购，公司第一大股东的位置也迅速被一群来历不明的野蛮人把持着。这里，究竟隐藏着什么样的阴谋？迷影重重..</span>",760,1176);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1178,1219);
$z[10][4]['name']="download";
$z[11]=Array("field","国语",1221,1265);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","大陆",1267,1310);
$z[12][4]['name']="area";
$z[13]=Array("field","",1312,1352);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914C204T0-1M446.jpg",1354,1447);
$z[14][4]['name']="litpic";

?>