{dede:field name='keywords'}诡宅·夜呻吟,诡宅·夜呻吟{/dede:field}
{dede:field name='description'}最新电影《诡宅·夜呻吟》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《诡宅·夜呻吟》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的{/dede:field}
{dede:field name='title'}诡宅·夜呻吟{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}内详 </li>
<li class="info_dq">地区：
大陆{/dede:field}
{dede:field name='yanyuan'}郜晓雨 蒋姗 郭晋豪{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">50年前，一座三层老宅孤零零地伫立在一片绿林中，美丽少女珍珍在三层卧室被一群男人虐杀。 一个电闪雷鸣的雨夜，房门被猛地敲响。正在裸聊的房东伟哥走到客厅打开门，门外出现的竟是一个无头的塑料服装模特，在雷电之中显得格外恐怖。伟哥被吓得将大门一关，瘫倒在地。小侯听见动静跑下楼，敲门声再次响了起来。小侯不顾伟哥阻拦打开门，只见一个漂亮性感的女人抱着塑料模特、拉着行李箱站在门口。女人自称珍珍，想要租住三楼的房间。伟哥被珍珍的美貌深深吸引，没多追问便立刻答应下来。同样垂涎欲滴的小侯则跑前跑后帮珍珍搬东西。然而伟哥的狗“蛋蛋”却不太喜欢这个新客人，对着珍珍不停地狂吠。 雨越下越大，老宅在雷雨中更显可怕。被雷声惊醒的伟哥隐约听到楼上传来女人撩人的呻吟声。伟哥黑着灯偷偷走上三楼，那声音正是从珍珍的卧室传出。伟哥色心大发，伸手想要拧开珍珍的房门，却听到走廊尽头传来窸窸窣窣的声音。伟哥蹑手蹑脚走过去，恐怖的气氛弥漫全身。突然，一个鬼影冒出来，伟哥尖叫着与鬼影抱成一团，滚下楼梯。而后接二连三的出现的诡异事件将整个故事推向了高潮……</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914C13D030-12R92.jpg{/dede:field}
