{dede:field name='keywords'}最后一个道士的往事,最后{/dede:field}
{dede:field name='description'}最新电影《最后一个道士的往事》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《最后一个道士的往事》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收{/dede:field}
{dede:field name='title'}最后一个道士的往事{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pingfen'}6.7{/dede:field}
{dede:field name='daoyan'}林育塘{/dede:field}
{dede:field name='yanyuan'}廉捷 高天景{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">住在城里的夏家闹鬼，于是寻找有本事捉鬼降妖的人，陈言谷（马宗彬 饰）闻讯带着两徒弟进城捉鬼。帮夏家驱除恶鬼之后，陈言谷得到100万。而师傅从此出去花天酒地。不顾两个徒弟刘梦阳（廉捷 饰）、顾博（高天景 饰）。而顾博则想办法偷到了师傅钱箱的钥匙，骗师弟一起去城里。路上顾博耍心机带钱跑了，留下了刘梦阳一人。刘梦阳走投无路到了足疗店工作，不巧又碰到师兄，却发现师兄不学正道跑入偏门，为了解救师兄，刘梦阳展开了一系列的行动……</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160322/145V332JJ2F-1HQ8.jpg{/dede:field}
