<?php
$z[0]=Array("field","青春追梦曲,青春追梦曲迅",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《青春追梦曲》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《青春追梦曲》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","青春追梦曲",366,419);
$z[2][4]['name']="title";
$z[3]=Array("field","",421,460);
$z[3][4]['name']="writer";
$z[4]=Array("field","",462,501);
$z[4][4]['name']="source";
$z[5]=Array("field","",503,543);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","10.0",545,589);
$z[6][4]['name']="pingfen";
$z[7]=Array("field","内详",591,636);
$z[7][4]['name']="daoyan";
$z[8]=Array("field","ngern Fifa",638,688);
$z[8][4]['name']="yanyuan";
$z[9]=Array("field","2016",690,731);
$z[9][4]['name']="time";
$z[10]=Array("field","其他",733,777);
$z[10][4]['name']="yuyan";
$z[11]=Array("field","其他",779,822);
$z[11][4]['name']="area";
$z[12]=Array("field","<span style=\"font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;\">青春校园剧《PartTimeTheSeries》，这个故事将围绕多对男生展开。该剧制作团队由为爱所困第二季团队担当，主演除了新人外，为爱众男星也有倾情出演，如ngern，Fifa等。</span>",824,1192);
$z[12][4]['name']="introduction";
$z[13]=Array("field","",1194,1235);
$z[13][4]['name']="download";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V33252B5P-1L24.jpg",1237,1329);
$z[14][4]['name']="litpic";

?>