{dede:field name='keywords'}阴阳诡捕之黄妖迷情,阴阳{/dede:field}
{dede:field name='description'}最新电影《阴阳诡捕之黄妖迷情》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《阴阳诡捕之黄妖迷情》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收{/dede:field}
{dede:field name='title'}阴阳诡捕之黄妖迷情{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}李巨涛 </li>
<li class="info_dq">地区：
大陆{/dede:field}
{dede:field name='yanyuan'}杨玥 宫海滨 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《阴阳诡捕之黄妖迷情》在线观看" title="《阴阳诡捕之黄妖迷情》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《阴阳诡捕之黄妖迷情》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}3.2{/dede:field}
{dede:field name='introduction'}上世纪30年代，留洋归国的北宫琉璃不顾家人反对毅然加入警局，与警队队长林豹成为搭档，携手维护一方平安。一日，一桩诡异的凶杀案打破了往日的宁静，看似遭人毒手惨死的富贾.{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语</li>
<li class="yanyuan">主演：
<a href="/search/%E6%9D%A8%E7%8E%A5" target="_blank">杨玥</a> <a href="/search/%E5%AE%AB%E6%B5%B7%E6%BB%A8" target="_blank">宫海滨</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《阴阳诡捕之黄妖迷情》在线观看" title="《阴阳诡捕之黄妖迷情》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《阴阳诡捕之黄妖迷情》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145913Q2104030-109261.jpg{/dede:field}
