
<field:time itemname="上映时间" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="16" page="">
</field:time>

<field:daoyan itemname="导演" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="50" page="">
</field:daoyan>

<field:yanyuan itemname="演员" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="50" page="">
</field:yanyuan>

<field:pingfen itemname="评分" autofield="1" notsend="0" type="text" isnull="true" islist="0" default="0"  maxlength="50" page="">
</field:pingfen>

<field:introduction itemname="简介" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="1024" page="">
</field:introduction>

<field:download itemname="下载" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="1024" page="">
</field:download>

<field:yuyan itemname="语言" autofield="1" notsend="0" type="select" isnull="true" islist="0" default="粤语,国语,英语,韩语,日语,其他"  maxlength="50" page="">
</field:yuyan>

<field:area itemname="地区" autofield="1" notsend="0" type="select" isnull="true" islist="0" default="大陆,韩国,日本,欧美,港台,其他"  maxlength="50" page="">
</field:area>
