{dede:field name='keywords'}魔女之城,魔女之城电视剧{/dede:field}
{dede:field name='description'}最新电视剧《魔女之城》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《魔女之城》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友{/dede:field}
{dede:field name='title'}魔女之城{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2000{/dede:field}
{dede:field name='daoyan'}郑孝{/dede:field}
{dede:field name='yanyuan'}崔贞媛 徐智锡 金桢勋 李海仁{/dede:field}
{dede:field name='pingfen'}5.7{/dede:field}
{dede:field name='introduction'}<span style="color:#555555;font-family:宋体;line-height:21px;white-space:normal;background-color:#FFFFFF;">讲述了离婚的婆婆、媳妇、小姑子三个女人间虽然开始有很多不可调和的矛盾，但渐渐互相理解，共同度过困难的故事。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}韩剧{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914N31aM0-14S91.jpg{/dede:field}
