<?php
$z[0]=Array("field","魔女之城,魔女之城电视剧",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《魔女之城》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《魔女之城》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","魔女之城",366,416);
$z[2][4]['name']="title";
$z[3]=Array("field","",418,457);
$z[3][4]['name']="writer";
$z[4]=Array("field","",459,498);
$z[4][4]['name']="source";
$z[5]=Array("field","2000",500,541);
$z[5][4]['name']="time";
$z[6]=Array("field","郑孝",543,588);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","崔贞媛 徐智锡 金桢勋 李海仁",590,669);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","5.7",671,714);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"color:#555555;font-family:宋体;line-height:21px;white-space:normal;background-color:#FFFFFF;\">讲述了离婚的婆婆、媳妇、小姑子三个女人间虽然开始有很多不可调和的矛盾，但渐渐互相理解，共同度过困难的故事。</span>",716,1036);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1038,1079);
$z[10][4]['name']="download";
$z[11]=Array("field","国语",1081,1125);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","韩剧",1127,1170);
$z[12][4]['name']="area";
$z[13]=Array("field","",1172,1212);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914N31aM0-14S91.jpg",1214,1307);
$z[14][4]['name']="litpic";

?>