<?php
$z[0]=Array("field","编织记忆\\思想调查员第二",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《编织记忆\\思想调查员第二季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《编织记忆\\思想调查员第二季》电视剧全集迅雷高清下载，以及高清在线播放，轻",77,366);
$z[1][4]['name']="description";
$z[2]=Array("field","编织记忆\\思想调查员第二季",368,443);
$z[2][4]['name']="title";
$z[3]=Array("field","",445,484);
$z[3][4]['name']="writer";
$z[4]=Array("field","",486,525);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",527,568);
$z[5][4]['name']="time";
$z[6]=Array("field","内详",570,615);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","戴安·法尔 费利克斯·戈麦兹 埃林·亚金",617,710);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",712,756);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">这是一部带有超自然色彩的青春剧，故事描述一个年轻女人被一个绝密政府组织雇佣参与一项超自然研究。他们将「刺探」最近刚刚死亡的人的大脑，利用他们的记忆来调查悬疑谋杀案，破解各种秘密——如果他们不这么做，那么这些秘密就只能追随死者一起进坟墓了。Emma Ishta扮演女主人公Kirsten Clark，聪明但不善社交，身患一种罕见病症。她没有任何情感，也体会不到「时间的流逝」。她是个计算机高手，拥有非凡的黑客技能。她原本可以拿到计算机科学领域的高级学位……但是她因为公开室友和辅导教授的私情而遇到麻烦。 　　 　　美国政府看中了她的独特技能，选择她参加一个绝密的政府研究项目。用Kirsten自己的话来说，这个项目就是「入侵死者的大脑，读取他们的记忆」。她对这项看起来很吓人的、难以预测的工作应付自如，这连她自己也有些惊讶。 　　Kyle Harris扮演男主人公Cameron，是从事这项绝密研究的政府秘密组织的首席技术员，也是所有科研人员的管理员。这个研究项目的负责人是Cameron的母亲Maggie，他们不仅在一起工作，还在一起生活。Cameron关心这项研究，关心所有科研人员，但他对母亲选择计算机黑客Kirsten参加这个团队持保留意见。Cameron对工作充满激情，但始终循规蹈矩。Kirsten为了拯救无辜生命时常会做出违反程序和超越职权范围的事情，这让Cameron既好气又好笑。Felix Gomez扮演计算机教授Jerome Smallwood，是教Kirsten学习计算机科学的老师。</span>",758,2613);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",2615,2656);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",2658,2702);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","美剧",2704,2747);
$z[12][4]['name']="area";
$z[13]=Array("field","",2749,2789);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914O134X30-2NZ3.jpg",2791,2884);
$z[14][4]['name']="litpic";

?>