{dede:field name='keywords'}夺路狂飙,夺路狂飙迅雷下{/dede:field}
{dede:field name='description'}最新电影《夺路狂飙》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《夺路狂飙》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共{/dede:field}
{dede:field name='title'}夺路狂飙{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='daoyan'}左勋{/dede:field}
{dede:field name='yanyuan'}秦楚明 贾茹{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">传奇车手，飞车界的老大雷子风，带着兄弟们一起备战中朝边境越野拉力赛，却突然接到了一个神秘的电话，得知从朝鲜来的黑帮老大道哥绑架了鸟叔，以此威胁雷子风帮他运送毒品，雷子风为了救出师傅，决定铤而走险。这时太子季从俄罗斯回来参加比赛，目的也为了抢夺这批货，两人相遇，揭开了之间多年的恩怨，太子季曾经因为黑市赌车被师傅逐出家门，太子季以为雷子风出卖了自己而怀恨在心，他为了抢到这批货不择手段，策反了阿森帮他。而此时狡猾的道哥知道大家的注意力都在雷子风身上，为了安全的把货取回来，他找到了安娜，告诉她真正藏货的地点，安娜为了不让雷子风以身犯险，决定自己去救师傅，比赛开始之后，安娜冲出赛道，来到交易地点，却被叛变的阿森抢走了保险箱，太子季和阿森带着保险箱驾车逃走，安娜紧追不舍，最后撞毁了阿森的车，取回了箱子，和知道后赶来的的雷子风救出了师傅。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160322/145V332BDI0-11aN.jpg{/dede:field}
