<?php
$z[0]=Array("field","邪恶力量/凶鬼恶灵第十一",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《邪恶力量/凶鬼恶灵第十一季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《邪恶力量/凶鬼恶灵第十一季》电视剧全集迅雷高清下载，以及高清在线播放，轻",77,366);
$z[1][4]['name']="description";
$z[2]=Array("field","邪恶力量/凶鬼恶灵第十一季",368,443);
$z[2][4]['name']="title";
$z[3]=Array("field","",445,484);
$z[3][4]['name']="writer";
$z[4]=Array("field","",486,525);
$z[4][4]['name']="source";
$z[5]=Array("field","2015",527,568);
$z[5][4]['name']="time";
$z[6]=Array("field","JeremyCarver",570,621);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","贾德·帕达里克 詹森·阿克斯 米沙·克林斯 马克·谢泼德",623,737);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","0.0",739,782);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","农场里的大屠杀事件过后，Dean、Sam和Castiel必须加倍努力来寻找去除「该隐标记」（Mark Of Cain）的方法。他们查遍了所有的民间传说，结果一无所获。绝望的Castiel想出一个新主意，但Sam却称之为「我听到过的最糟糕的主意」。与此同时，Rowena（Ruth Connell）继续实施对付Crowley的计划。Castiel试图与Claire（Kathryn Love Newton）缓和关系，但Claire一心要向杀害自己朋友Randy的凶手Dean报仇。「该隐标记」现在是Dean、Sam和Castiel必须要解决的大问题，或许该隐（Timothy Omundson）本人能提供一点帮助？无论如何，这个角色在下半季中会再次出现，另一方面，Felicia Day扮演的Charlie将从奥兹国归来。她出现在「最危险的情况下」，而且她「带回来一些非常危险的东西」。她将和Wenchester兄弟、Castiel共同追踪那个危险的东西。制片人承诺，观众将看到一个「从未见过的Charlie」。与此同时，Rowena将继续插手儿子Crowley的事务。在寻找「该隐标记」解决方案的过程中，Sam、Dean、Castiel和他们的盟友会和一些「你原本认为不可能」的人进行合作，并且干出极其冒险的事情。该隐（Cain）本人和Metatron均将在下半季回归，他们与「该隐标记」的特殊关系既会帮助Sam、Dean和Castiel，同时也会伤害他们。此外，Claire和Dean的恩恩怨怨、Claire和Castiel的故事都没有结束。",784,2333);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",2335,2376);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",2378,2422);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","美剧",2424,2467);
$z[12][4]['name']="area";
$z[13]=Array("field","",2469,2509);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914O1542640-2W954.jpg",2511,2606);
$z[14][4]['name']="litpic";

?>