{dede:field name='keywords'}十五年等待候鸟,十五年等{/dede:field}
{dede:field name='description'}最新电视剧《十五年等待候鸟》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《十五年等待候鸟》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让{/dede:field}
{dede:field name='title'}十五年等待候鸟{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}柯翰辰{/dede:field}
{dede:field name='yanyuan'}张若昀 孙怡 邓伦 张雪迎 李宗霖{/dede:field}
{dede:field name='pingfen'}6.4{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">2015年北京电视节#秋推会#筹备剧。观达影视：#十五年等待候鸟#（根据@盈风 小说改编）</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914N1U25Z-D141.jpg{/dede:field}
