<?php
$z[0]=Array("field","十五年等待候鸟,十五年等",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《十五年等待候鸟》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《十五年等待候鸟》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","十五年等待候鸟",366,425);
$z[2][4]['name']="title";
$z[3]=Array("field","",427,466);
$z[3][4]['name']="writer";
$z[4]=Array("field","",468,507);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",509,550);
$z[5][4]['name']="time";
$z[6]=Array("field","柯翰辰",552,600);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","张若昀 孙怡 邓伦 张雪迎 李宗霖",602,685);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","6.4",687,730);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;\">2015年北京电视节#秋推会#筹备剧。观达影视：#十五年等待候鸟#（根据@盈风 小说改编）</span>",732,994);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",996,1037);
$z[10][4]['name']="download";
$z[11]=Array("field","国语",1039,1083);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","大陆",1085,1128);
$z[12][4]['name']="area";
$z[13]=Array("field","",1130,1170);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914N1U25Z-D141.jpg",1172,1264);
$z[14][4]['name']="litpic";

?>