{dede:field name='keywords'}双叶庄的朋友,双叶庄的朋{/dede:field}
{dede:field name='description'}最新电影《双叶庄的朋友》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《双叶庄的朋友》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您{/dede:field}
{dede:field name='title'}双叶庄的朋友电影迅雷高清下载,双叶庄的朋友高清下载在线观看 - 日韩 - a67手机电影网{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}平松惠美子 </li>
<li class="info_dq">地区：
日韩{/dede:field}
{dede:field name='yanyuan'}市原隼人 臼田麻美 中村伦也 阳月华 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《双叶庄的朋友》在线观看" title="《双叶庄的朋友》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《双叶庄的朋友》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">原舞台导演川村正治和他的妻子美江搬到了双叶庄居住。有一天，川村看到了26年前也住在这里的画家仓田的幻影，两人相似的境遇使他们交谈的很愉快……直到川村看到了无法相信的场景，而这些幻象是否是真实发生过的呢？令人惊讶的事实慢慢清晰了起来。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}日语</li>
<li class="yanyuan">主演：
<a href="/tag/5525/" target="_blank">市原隼人</a> <a href="/search/%E8%87%BC%E7%94%B0%E9%BA%BB%E7%BE%8E" target="_blank">臼田麻美</a> <a href="/search/%E4%B8%AD%E6%9D%91%E4%BC%A6%E4%B9%9F" target="_blank">中村伦也</a> <a href="/search/%E9%98%B3%E6%9C%88%E5%8D%8E" target="_blank">阳月华</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《双叶庄的朋友》在线观看" title="《双叶庄的朋友》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《双叶庄的朋友》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}日韩{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/14591345235aF-2GI5.jpg{/dede:field}
