{dede:field name='keywords'}我的国王/我心深爱的国王{/dede:field}
{dede:field name='description'}最新电影《我的国王/我心深爱的国王》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《我的国王/我心深爱的国王》完整版迅雷高清下载，以及高清在线播放，轻轻一点{/dede:field}
{dede:field name='title'}我的国王/我心深爱的国王{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}麦温·勒·贝斯柯 </li>
<li class="info_dq">地区：
欧美{/dede:field}
{dede:field name='yanyuan'}艾玛纽尔·贝克特 文森特·卡索 路易·加瑞尔 伊希尔·勒·贝斯柯{/dede:field}
{dede:field name='pingfen'}9.5{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">影片由法国女导演麦温执导，法国巨星文森特·卡索搭档法国女星艾玛纽尔·贝克特和法国男星路易·加瑞尔出演，影片入围第68届法国戛纳电影节主竞赛单元。值得一提的是，文森特·卡索也有出演入围主竞赛的《故事的故事》，而艾玛纽尔·贝克特执导的影片《昂首挺胸》被选为本届电影节的开幕片 。　　女律师汤妮（Emmanuelle Bercot饰）滑雪受伤疗养时，回忆起她曾经历过的一段刻骨铭心爱情。她爱上了迷人的餐厅经理乔治欧（Vincent Cassel饰），两人从相互吸引、陷入热恋、甜蜜闪婚到天翻地覆的疯狂毁灭…。而她的疗伤过程，也不断地与这些感情经历相互对映，让观众彷彿置身其中、感同身受，前一秒才纵情欢笑、干柴烈火，下一秒却忌恨争执、甚至大打出手。当爱情从热恋跨向婚姻，究竟该是浓郁的幸福？抑或是烦苦的羁绊？</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}其他{/dede:field}
{dede:field name='area'}欧美{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914B6132P-Q234.jpg{/dede:field}
