<?php
$z[0]=Array("field","我的国王/我心深爱的国王",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《我的国王/我心深爱的国王》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《我的国王/我心深爱的国王》完整版迅雷高清下载，以及高清在线播放，轻轻一点",77,366);
$z[1][4]['name']="description";
$z[2]=Array("field","我的国王/我心深爱的国王",368,440);
$z[2][4]['name']="title";
$z[3]=Array("field","",442,481);
$z[3][4]['name']="writer";
$z[4]=Array("field","",483,522);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",524,565);
$z[5][4]['name']="time";
$z[6]=Array("field","麦温·勒·贝斯柯 </li>\r\n<li class=\"info_dq\">地区：\r\n欧美",567,673);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","艾玛纽尔·贝克特 文森特·卡索 路易·加瑞尔 伊希尔·勒·贝斯柯",675,800);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","9.5",802,845);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">影片由法国女导演麦温执导，法国巨星文森特·卡索搭档法国女星艾玛纽尔·贝克特和法国男星路易·加瑞尔出演，影片入围第68届法国戛纳电影节主竞赛单元。值得一提的是，文森特·卡索也有出演入围主竞赛的《故事的故事》，而艾玛纽尔·贝克特执导的影片《昂首挺胸》被选为本届电影节的开幕片 。　　女律师汤妮（Emmanuelle Bercot饰）滑雪受伤疗养时，回忆起她曾经历过的一段刻骨铭心爱情。她爱上了迷人的餐厅经理乔治欧（Vincent Cassel饰），两人从相互吸引、陷入热恋、甜蜜闪婚到天翻地覆的疯狂毁灭…。而她的疗伤过程，也不断地与这些感情经历相互对映，让观众彷彿置身其中、感同身受，前一秒才纵情欢笑、干柴烈火，下一秒却忌恨争执、甚至大打出手。当爱情从热恋跨向婚姻，究竟该是浓郁的幸福？抑或是烦苦的羁绊？</span>",847,1986);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1988,2029);
$z[10][4]['name']="download";
$z[11]=Array("field","其他",2031,2075);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","欧美",2077,2120);
$z[12][4]['name']="area";
$z[13]=Array("field","",2122,2162);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914B6132P-Q234.jpg",2164,2256);
$z[14][4]['name']="litpic";

?>