{dede:field name='keywords'}一代宗师,一代宗师迅雷下{/dede:field}
{dede:field name='description'}最新电影《一代宗师》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《一代宗师》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共{/dede:field}
{dede:field name='title'}一代宗师{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2012{/dede:field}
{dede:field name='daoyan'}王家卫 </li>
<li class="info_dq">地区：
港台{/dede:field}
{dede:field name='yanyuan'}梁朝伟 章子怡 宋慧乔 张震 赵本山 小沈阳 王庆祥 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《一代宗师》在线观看" title="《一代宗师》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《一代宗师》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}6.7{/dede:field}
{dede:field name='introduction'}{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语</li>
<li class="yanyuan">主演：
<a href="/tag/191/" target="_blank">梁朝伟</a> <a href="/tag/255/" target="_blank">章子怡</a> <a href="/search/%E5%AE%8B%E6%85%A7%E4%B9%94" target="_blank">宋慧乔</a> <a href="/tag/4371/" target="_blank">张震</a> <a href="/tag/131/" target="_blank">赵本山</a> <a href="/tag/7059/" target="_blank">小沈阳</a> <a href="/search/%E7%8E%8B%E5%BA%86%E7%A5%A5" target="_blank">王庆祥</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《一代宗师》在线观看" title="《一代宗师》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《一代宗师》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}港台{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145913QA621P-1194K.jpg{/dede:field}
