<?php
$z[0]=Array("field","我心之花雨,我心之花雨电",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《我心之花雨》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《我心之花雨》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","我心之花雨",366,419);
$z[2][4]['name']="title";
$z[3]=Array("field","",421,460);
$z[3][4]['name']="writer";
$z[4]=Array("field","",462,501);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",503,544);
$z[5][4]['name']="time";
$z[6]=Array("field","鱼秀善",546,594);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","罗海岭 李昌旭 林彩媛 林志恩 崔娜舞",596,685);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","6.2",687,730);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;\">江苏1950年代战争中命运互换的两个女人，在70年代所拥有的不同的人生与爱情的故事。</span>",732,993);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",995,1036);
$z[10][4]['name']="download";
$z[11]=Array("field","韩语",1038,1082);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","韩剧",1084,1127);
$z[12][4]['name']="area";
$z[13]=Array("field","",1129,1169);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914NL46120-96239.jpg",1171,1265);
$z[14][4]['name']="litpic";

?>