{dede:field name='keywords'}德云三逗士,德云三逗士迅{/dede:field}
{dede:field name='description'}最新电影《德云三逗士》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《德云三逗士》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋{/dede:field}
{dede:field name='title'}德云三逗士{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='daoyan'}张莫闲{/dede:field}
{dede:field name='yanyuan'}郭德纲 于谦{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">本片以搞笑、活泼的手法讲述一群“贱男”在大都市生活的种种糗事。每集都会为“贱男“配备不同的性感都市美女，用写实手法让大家在莞尔一笑同时产生共鸣,提升“话题感”。以时下时髦的生活方式,以及族群为标本,让大家在搞笑同时,也崇尚这种自由自在的生活态度,以及对人生的“囧”刻也能轻松的心情对待</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160322/145V332615230-O228.jpg{/dede:field}
