{dede:field name='keywords'}通学途中,通学途中迅雷下{/dede:field}
{dede:field name='description'}最新电影《通学途中》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《通学途中》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共{/dede:field}
{dede:field name='title'}通学途中{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='daoyan'}川野浩司{/dede:field}
{dede:field name='yanyuan'}中川大志 森川葵 藤本泉 赤楚衛二{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='yuyan'}日语{/dede:field}
{dede:field name='area'}日韩{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">腼腆的女孩由纪（森川葵 饰）渴望体会一下心似小鹿乱撞的感觉，可是命中注定的白马王子迟迟未曾出现。同在美术部的弘（中川大志 饰）始终暖暖注视着由纪，他为了这位“好朋友”的恋情给出了自己的建议。而对由纪来说，谁才能让她领悟到“真正的恋情”呢？ 本片根据访问量超过770万人次、累计发行量超过135万部的网络小说“通学系列”改编，上部《通学电车》定于2015年11月7日上映</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160322/145V333LKZ-2G047.jpg{/dede:field}
