<?php
$z[0]=Array("field","通学途中,通学途中迅雷下",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《通学途中》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《通学途中》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","通学途中",366,416);
$z[2][4]['name']="title";
$z[3]=Array("field","",418,457);
$z[3][4]['name']="writer";
$z[4]=Array("field","",459,498);
$z[4][4]['name']="source";
$z[5]=Array("field","",500,540);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","10.0",542,586);
$z[6][4]['name']="pingfen";
$z[7]=Array("field","川野浩司",588,639);
$z[7][4]['name']="daoyan";
$z[8]=Array("field","中川大志 森川葵 藤本泉 赤楚衛二",641,726);
$z[8][4]['name']="yanyuan";
$z[9]=Array("field","2016",728,769);
$z[9][4]['name']="time";
$z[10]=Array("field","日语",771,815);
$z[10][4]['name']="yuyan";
$z[11]=Array("field","日韩",817,860);
$z[11][4]['name']="area";
$z[12]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">腼腆的女孩由纪（森川葵 饰）渴望体会一下心似小鹿乱撞的感觉，可是命中注定的白马王子迟迟未曾出现。同在美术部的弘（中川大志 饰）始终暖暖注视着由纪，他为了这位“好朋友”的恋情给出了自己的建议。而对由纪来说，谁才能让她领悟到“真正的恋情”呢？ 本片根据访问量超过770万人次、累计发行量超过135万部的网络小说“通学系列”改编，上部《通学电车》定于2015年11月7日上映</span>",862,1544);
$z[12][4]['name']="introduction";
$z[13]=Array("field","",1546,1587);
$z[13][4]['name']="download";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V333LKZ-2G047.jpg",1589,1680);
$z[14][4]['name']="litpic";

?>