<?php
$z[0]=Array("field","美女主播惊魂记,美女主播",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《美女主播惊魂记》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《美女主播惊魂记》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","美女主播惊魂记",366,425);
$z[2][4]['name']="title";
$z[3]=Array("field","",427,466);
$z[3][4]['name']="writer";
$z[4]=Array("field","",468,507);
$z[4][4]['name']="source";
$z[5]=Array("field","10.0",509,553);
$z[5][4]['name']="pingfen";
$z[6]=Array("field","张睿龙",555,603);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","TAMMY甜蜜 刘小婉",605,666);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","2016",668,709);
$z[8][4]['name']="time";
$z[9]=Array("field","国语",711,755);
$z[9][4]['name']="yuyan";
$z[10]=Array("field","大陆",757,800);
$z[10][4]['name']="area";
$z[11]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">两位网络美女女主播，泰国女孩塔米和中国女孩海伦，被绑架于一个仓库里。一小时前塔米在她家洗澡时被绑架，海伦在网络公司下班后在公司门外被绑走。她们被绑架后苦苦回忆却依..</span>",802,1209);
$z[11][4]['name']="introduction";
$z[12]=Array("field","",1211,1252);
$z[12][4]['name']="download";
$z[13]=Array("field","",1254,1294);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V33422Z20-261F1.jpg",1296,1389);
$z[14][4]['name']="litpic";

?>