{dede:field name='keywords'}鸭王2,鸭王2迅雷下载,鸭王{/dede:field}
{dede:field name='description'}最新电影《鸭王2》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《鸭王2》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共同享受下{/dede:field}
{dede:field name='title'}鸭王2{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}姜国民 </li>
<li class="info_dq">地区：
港台{/dede:field}
{dede:field name='yanyuan'}何浩文 林子善 文凯玲 鍾采羲 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《鸭王2》在线观看" title="《鸭王2》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《鸭王2》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}8.3{/dede:field}
{dede:field name='introduction'}{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}粤语</li>
<li class="yanyuan">主演：
<a href="/search/%E4%BD%95%E6%B5%A9%E6%96%87" target="_blank">何浩文</a> <a href="/search/%E6%9E%97%E5%AD%90%E5%96%84" target="_blank">林子善</a> <a href="/search/%E6%96%87%E5%87%AF%E7%8E%B2" target="_blank">文凯玲</a> <a href="/search/%E9%8D%BE%E9%87%87%E7%BE%B2" target="_blank">鍾采羲</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《鸭王2》在线观看" title="《鸭王2》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《鸭王2》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}港台{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145913Q6309C0-95A9.jpg{/dede:field}
