{dede:field name='keywords'}最终复仇弓,最终复仇弓迅{/dede:field}
{dede:field name='description'}最新电影《最终复仇弓》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《最终复仇弓》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋{/dede:field}
{dede:field name='title'}最终复仇弓电影迅雷高清下载,最终复仇弓高清下载在线观看 - 大陆 - a67手机电影网{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}阳子政 </li>
<li class="info_dq">地区：
大陆{/dede:field}
{dede:field name='yanyuan'}栗菡 李宜坤 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《最终复仇弓》在线观看" title="《最终复仇弓》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《最终复仇弓》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">供职于省射箭队队员的纪冬,在妹妹纪雪遭遇强暴惨遭杀害后的复仇故事。独自找出租房的纪雪被暴力杀人狂向南残忍杀害,纪冬痛不欲生,为找到嫌疑人开始独立追查凶手。经过一番调查,终于将目标锁定在中介经理向南身上。向南性格极度扭曲,经常袭击夜归女子,并将她们强暴后无情杀害。一场复仇游戏由此开始</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语</li>
<li class="yanyuan">主演：
<a href="/search/%E6%A0%97%E8%8F%A1" target="_blank">栗菡</a> <a href="/search/%E6%9D%8E%E5%AE%9C%E5%9D%A4" target="_blank">李宜坤</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《最终复仇弓》在线观看" title="《最终复仇弓》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《最终复仇弓》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145913441646360-1YV6.jpg{/dede:field}
