{dede:field name='keywords'}确认,确认迅雷下载,确认高{/dede:field}
{dede:field name='description'}最新电影《确认》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《确认》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共同享受下{/dede:field}
{dede:field name='title'}确认{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}Bob Nelson </li>
<li class="info_dq">地区：
欧美{/dede:field}
{dede:field name='yanyuan'}克里夫·欧文 玛丽亚·贝罗 帕顿·奥斯瓦尔特 斯蒂芬·托布罗斯基{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">八岁的安东尼有点不安花周末和他的酒鬼,耗尽了木匠爸爸沃尔特,而他的妈妈邦妮和她的新丈夫凯尔一起去天主教撤退。沃尔特一样不安与安东尼,尤其是第一天一起不幸的是一系列的典型事件,包括他的卡车打破,他的房东锁定了他的房子,和窃取他的工具箱,他需要为即将到来的工作。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}英语{/dede:field}
{dede:field name='area'}欧美{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
