<li class="d[field:global.autoindex/]">
					<a href="" target="_blank">
						<img  src="[field:litpic/]"
							  alt="[field:title/]" /></a
					><p>[field:yuyan/]</p>
					<b><a href="[field:arcurl/]" target="_blank">[field:title/]</a>
						<script src="[field:global.cfg_plus_dir/]/pinfen.php?type=getstar&aid=[field:id/]" type='text/javascript' language="javascript"></script>
						<!--<img src="[field:global.cfg_templets_skin/]/images/1.jpg">-->

						<em>[field:pingfen/]分</em></b>
				</li>