{dede:field name='keywords'}第五波\第五天劫,第五波{/dede:field}
{dede:field name='description'}最新电影《第五波\第五天劫》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《第五波\第五天劫》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您{/dede:field}
{dede:field name='title'}第五波\第五天劫电影迅雷高清下载,第五波\第五天劫高清下载在线观看 - 欧美 - a67手机电影网{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}J·布莱克森 </li>
<li class="info_dq">地区：
欧美{/dede:field}
{dede:field name='yanyuan'}科洛·莫瑞兹 尼克·罗宾森 朗·里维斯顿 玛姬·丝弗 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《第五波\第五天劫》在线观看" title="《第五波\第五天劫》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《第五波\第五天劫》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">影片改编自同名畅销小说，故事讲述地球遭到外星人攻击，人类文明退回石器时代，16岁少女凯西作为仅存人类之一，挣扎生存，寻找希望</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}英语</li>
<li class="yanyuan">主演：
<a href="/tag/7459/" target="_blank">科洛·莫瑞兹</a> <a href="/search/%E5%B0%BC%E5%85%8B%C2%B7%E7%BD%97%E5%AE%BE%E6%A3%AE" target="_blank">尼克·罗宾森</a> <a href="/search/%E6%9C%97%C2%B7%E9%87%8C%E7%BB%B4%E6%96%AF%E9%A1%BF" target="_blank">朗·里维斯顿</a> <a href="/search/%E7%8E%9B%E5%A7%AC%C2%B7%E4%B8%9D%E5%BC%97" target="_blank">玛姬·丝弗</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《第五波\第五天劫》在线观看" title="《第五波\第五天劫》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《第五波\第五天劫》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}欧美{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145913450111450-163145.jpg{/dede:field}
