
<field:pingfen itemname="评分" autofield="1" notsend="0" type="float" isnull="true" islist="0" default=""  maxlength="16" page="">
</field:pingfen>

<field:daoyan itemname="导演" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="16" page="">
</field:daoyan>

<field:yanyuan itemname="演员" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="52" page="">
</field:yanyuan>

<field:time itemname="上映时间" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="20" page="">
</field:time>

<field:yuyan itemname="语言" autofield="1" notsend="0" type="checkbox" isnull="true" islist="0" default="中文,英文,粤语,韩语"  maxlength="20" page="">
</field:yuyan>


<field:area itemname="地区" autofield="1" notsend="0" type="select" isnull="true" islist="0" default="大陆,欧美,港台,韩国"  maxlength="50" page="">
</field:area>


<field:introduction itemname="简介" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="150" page="">
</field:introduction>

<field:download itemname="下载" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="1024" page="">
</field:download>
