<?php
$z[0]=Array("field","神战：权力之眼/埃及神战",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《神战：权力之眼/埃及神战》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《神战：权力之眼/埃及神战》完整版迅雷高清下载，以及高清在线播放，轻轻一点",77,366);
$z[1][4]['name']="description";
$z[2]=Array("field","神战：权力之眼/埃及神战",368,440);
$z[2][4]['name']="title";
$z[3]=Array("field","",442,481);
$z[3][4]['name']="writer";
$z[4]=Array("field","",483,522);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",524,565);
$z[5][4]['name']="time";
$z[6]=Array("field","亚历克斯·普罗亚斯 </li>\r\n<li class=\"info_dq\">地区：\r\n欧美",567,677);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","尼古拉·科斯特-瓦尔道 杰拉德·巴特勒 布伦顿·思韦茨",679,791);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",793,837);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">故事发生在矗立着宫殿和金字塔的婉转萦回的尼罗河畔。 当时的古埃及充满了魔法、怪兽和神灵。无情的黑暗之神赛特,夺取了原本属于天神荷鲁斯的埃及王权,并让曾经繁荣和平的国家陷入冲突与混乱。人类的存亡与世界的安定岌岌可危。 一位年轻的窃贼贝克被神所眷顾,为拯救世界和自己的真爱踏上了一场惊险的奇幻旅程。为了成功,他必须寻求并得到强大的荷鲁斯神的帮助,与其组成一个看似不太可能的“英雄” 联盟。随着人类生命的危在旦夕,两个英雄站了出来,开启了对抗邪恶的不归路...... 作为荷鲁斯与贝克强有力的敌人,赛特指派心腹为他们的对抗制造重重艰难险阻。如果荷鲁斯神与凡人贝克希望在这场对抗中最终获胜,他们就必须通过一系列对勇气和牺牲的考验。</span>",839,1896);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1898,1939);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",1941,1985);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","欧美",1987,2030);
$z[12][4]['name']="area";
$z[13]=Array("field","",2032,2072);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914BARB0-112252.jpg",2074,2167);
$z[14][4]['name']="litpic";

?>