{dede:field name='keywords'}我的同学不是人,我的同学{/dede:field}
{dede:field name='description'}最新电影《我的同学不是人》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《我的同学不是人》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您{/dede:field}
{dede:field name='title'}我的同学不是人电影迅雷高清下载,我的同学不是人高清下载在线观看 - 大陆 - a67手机电影网{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}轩祥杰 </li>
<li class="info_dq">地区：
大陆{/dede:field}
{dede:field name='yanyuan'}胡悦 高骏 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《我的同学不是人》在线观看" title="《我的同学不是人》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《我的同学不是人》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}6.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">由北京光影华视文化传媒有限公司、MSI映美传媒、吉诺出品、撲度娱乐、龙胤盛世影业联合出品。女神诺兰（胡悦 饰）在生日当晚，目睹了班上另类学霸发生恐怖变异并惨遭攻击，第二天她对朋友说出真相却无人相信，当众指出变异者后反而受到众人嘲笑。唯一相信她的只有暗恋她多年的姚飞（高骏 饰）。但在姚飞决心拯救女神之际，变异病毒却在校园内飞速扩散甚至威胁到整座城市，姚飞更是遭到诺兰的怀疑。究竟谁才是威胁校园安全的变种人母体？姚飞又能否在千钧一发之际拯救整座城市的安全？</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语</li>
<li class="yanyuan">主演：
<a href="/search/%E8%83%A1%E6%82%A6" target="_blank">胡悦</a> <a href="/search/%E9%AB%98%E9%AA%8F" target="_blank">高骏</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《我的同学不是人》在线观看" title="《我的同学不是人》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《我的同学不是人》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145913450U25Z-21Y19.jpg{/dede:field}
