<?php
$z[0]=Array("field","校卫,校卫迅雷下载,校卫高",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《校卫》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《校卫》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共同享受下",78,365);
$z[1][4]['name']="description";
$z[2]=Array("field","校卫",367,411);
$z[2][4]['name']="title";
$z[3]=Array("field","",413,452);
$z[3][4]['name']="writer";
$z[4]=Array("field","",454,493);
$z[4][4]['name']="source";
$z[5]=Array("field","",495,535);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","10.0",537,581);
$z[6][4]['name']="pingfen";
$z[7]=Array("field","图郎",583,628);
$z[7][4]['name']="daoyan";
$z[8]=Array("field","刘哲 孙凡",630,683);
$z[8][4]['name']="yanyuan";
$z[9]=Array("field","2016",685,726);
$z[9][4]['name']="time";
$z[10]=Array("field","国语",728,772);
$z[10][4]['name']="yuyan";
$z[11]=Array("field","大陆",774,817);
$z[11][4]['name']="area";
$z[12]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">徐强进入一所校风极差的学校维持纪律，校主任女儿高玲玲在校期间拉帮结派，勾结保安聚众赌博，欺负女同学，徐强制止这些的时候遭到陷害，受到处分的徐强因此泄气，最终在校长..</span>",819,1226);
$z[12][4]['name']="introduction";
$z[13]=Array("field","",1228,1269);
$z[13][4]['name']="download";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V3342400O0-2L448.jpg",1271,1365);
$z[14][4]['name']="litpic";

?>