{dede:field name='keywords'}青少年哪吒,青少年哪吒迅{/dede:field}
{dede:field name='description'}最新电影《青少年哪吒》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《青少年哪吒》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋{/dede:field}
{dede:field name='title'}青少年哪吒电影迅雷高清下载,青少年哪吒高清下载在线观看 - 欧美 - a67手机电影网{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}蔡明亮 </li>
<li class="info_dq">地区：
欧美{/dede:field}
{dede:field name='yanyuan'}李康生 王渝文 陈昭荣 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《青少年哪吒》在线观看" title="《青少年哪吒》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《青少年哪吒》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">拿着退来的补习费用逃离压抑的补习班后，小康（李康生）开始漫无目的的在西门町晃荡，偶遇有着另一种身份过着另一种日子的“不良少年”阿泽（陈昭荣），被其吸引，渴望融入其生活。但阿泽只是表面看来光鲜，打电动、开一辆重型机车在街上呼啸只因可以暂时让自己看起来像个胜利者，内心却一样是封闭孤独的。 　　在跟踪阿泽的过程中，小康渐发觉自己的性向可能与大多数人有别，也发现阿泽生活的单调与苦闷。但好过小康的是，阿泽虽也几乎不知何为亲情，却有“好兄弟”阿彬（任长彬）常陪左右，有阿桂（王渝文）暂当女友，来过“当天和尚撞天钟”的生活。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}</li>
<li class="yanyuan">主演：
<a href="/search/%E6%9D%8E%E5%BA%B7%E7%94%9F" target="_blank">李康生</a> <a href="/search/%E7%8E%8B%E6%B8%9D%E6%96%87" target="_blank">王渝文</a> <a href="/tag/1649/" target="_blank">陈昭荣</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《青少年哪吒》在线观看" title="《青少年哪吒》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《青少年哪吒》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}欧美{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/14591344cO440-15T31.jpg{/dede:field}
