{dede:field name='keywords'}女贼的诱惑,女贼的诱惑迅{/dede:field}
{dede:field name='description'}最新电影《女贼的诱惑》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《女贼的诱惑》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋{/dede:field}
{dede:field name='title'}女贼的诱惑{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}孙建江 </li>
<li class="info_dq">地区：
大陆{/dede:field}
{dede:field name='yanyuan'}何蕴 依王越{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">一个骗子团伙，在各地流窜作案。在一个城市作案的时候，偶然认识了一个女孩儿，这个女孩要拜骗子团伙老大为师，用身世打动了男人，跟骗子团伙骗取了很多社会人士的钱财，如碰瓷儿的，好色的，奸商等。得知这个城市的首富是娟姐，然后骗子团伙设下了个局，利用了这个女孩儿，最后骗取了城市首富的一笔钱财。快过年了，所以团伙要散伙，当骗子老大利用完女孩儿，预将她抛弃之时，却发现自己爱上了她。可是，万万没想到的事是，这个女人是警察，卧底到骗子团伙.</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914B5193440-1a09.jpg{/dede:field}
