<?php
$z[0]=Array("field","女贼的诱惑,女贼的诱惑迅",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《女贼的诱惑》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《女贼的诱惑》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","女贼的诱惑",366,419);
$z[2][4]['name']="title";
$z[3]=Array("field","",421,460);
$z[3][4]['name']="writer";
$z[4]=Array("field","",462,501);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",503,544);
$z[5][4]['name']="time";
$z[6]=Array("field","孙建江 </li>\r\n<li class=\"info_dq\">地区：\r\n大陆",546,639);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","何蕴 依王越",641,697);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",699,743);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">一个骗子团伙，在各地流窜作案。在一个城市作案的时候，偶然认识了一个女孩儿，这个女孩要拜骗子团伙老大为师，用身世打动了男人，跟骗子团伙骗取了很多社会人士的钱财，如碰瓷儿的，好色的，奸商等。得知这个城市的首富是娟姐，然后骗子团伙设下了个局，利用了这个女孩儿，最后骗取了城市首富的一笔钱财。快过年了，所以团伙要散伙，当骗子老大利用完女孩儿，预将她抛弃之时，却发现自己爱上了她。可是，万万没想到的事是，这个女人是警察，卧底到骗子团伙.</span>",745,1544);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1546,1587);
$z[10][4]['name']="download";
$z[11]=Array("field","国语",1589,1633);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","大陆",1635,1678);
$z[12][4]['name']="area";
$z[13]=Array("field","",1680,1720);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914B5193440-1a09.jpg",1722,1816);
$z[14][4]['name']="litpic";

?>