<?php
$z[0]=Array("field","年轻一代第二季,年轻一代",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《年轻一代第二季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《年轻一代第二季》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","年轻一代第二季",366,425);
$z[2][4]['name']="title";
$z[3]=Array("field","",427,466);
$z[3][4]['name']="writer";
$z[4]=Array("field","",468,507);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",509,550);
$z[5][4]['name']="time";
$z[6]=Array("field","Darren Star",552,602);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","米利亚姆·肖尔 萨顿·福斯特 黛比·玛扎 尼可·托托雷拉 希拉里·达芙",604,736);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",738,782);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","",784,829);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",831,872);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",874,918);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","美剧",920,963);
$z[12][4]['name']="area";
$z[13]=Array("field","",965,1005);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914NP36040-115022.jpg",1007,1102);
$z[14][4]['name']="litpic";

?>