{dede:field name='keywords'}潘多拉--永恒之命,潘多拉{/dede:field}
{dede:field name='description'}最新电影《潘多拉--永恒之命》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《潘多拉--永恒之命》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让{/dede:field}
{dede:field name='title'}潘多拉--永恒之命{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2014{/dede:field}
{dede:field name='daoyan'}河毛俊作 </li>
<li class="info_dq">地区：
日韩{/dede:field}
{dede:field name='yanyuan'}堺雅人 尾野真千子 石黒賢 鈴木浩介 伊藤歩 高橋來 郭智博 中村敦夫 伊武雅刀 高橋克実 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《潘多拉--永恒之命》在线观看" title="《潘多拉--永恒之命》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《潘多拉--永恒之命》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}9.0{/dede:field}
{dede:field name='introduction'}{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}日语</li>
<li class="yanyuan">主演：
<a href="/tag/3121/" target="_blank">堺雅人</a> <a href="/search/%E5%B0%BE%E9%87%8E%E7%9C%9F%E5%8D%83%E5%AD%90" target="_blank">尾野真千子</a> <a href="/search/%E7%9F%B3%E9%BB%92%E8%B3%A2" target="_blank">石黒賢</a> <a href="/search/%E9%88%B4%E6%9C%A8%E6%B5%A9%E4%BB%8B" target="_blank">鈴木浩介</a> <a href="/search/%E4%BC%8A%E8%97%A4%E6%AD%A9" target="_blank">伊藤歩</a> <a href="/search/%E9%AB%98%E6%A9%8B%E4%BE%86" target="_blank">高橋來</a> <a href="/search/%E9%83%AD%E6%99%BA%E5%8D%9A" target="_blank">郭智博</a> <a href="/search/%E4%B8%AD%E6%9D%91%E6%95%A6%E5%A4%AB" target="_blank">中村敦夫</a> <a href="/search/%E4%BC%8A%E6%AD%A6%E9%9B%85%E5%88%80" target="_blank">伊武雅刀</a> <a href="/search/%E9%AB%98%E6%A9%8B%E5%85%8B%E5%AE%9F" target="_blank">高橋克実</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《潘多拉--永恒之命》在线观看" title="《潘多拉--永恒之命》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《潘多拉--永恒之命》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}日韩{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145913QO01960-212M4.jpg{/dede:field}
