<?php
$z[0]=Array("field","荒野猎人/复仇勇者,荒野猎",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《荒野猎人/复仇勇者》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《荒野猎人/复仇勇者》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，",78,367);
$z[1][4]['name']="description";
$z[2]=Array("field","荒野猎人/复仇勇者",369,432);
$z[2][4]['name']="title";
$z[3]=Array("field","",434,473);
$z[3][4]['name']="writer";
$z[4]=Array("field","",475,514);
$z[4][4]['name']="source";
$z[5]=Array("field","2000",516,557);
$z[5][4]['name']="time";
$z[6]=Array("field","亚利桑德罗·冈萨雷斯·伊纳里多 </li>\r\n<li class=\"info_dq\">地区：\r\n欧美",559,686);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","莱昂纳多·迪卡普里奥 汤姆·哈迪 威尔·保尔特 多姆纳尔·格里森",688,814);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","8.5",816,859);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","该片根据Michael Punke同名小说改编，由Mark L. \r\nSmith编剧。故事讲述19世纪一个皮草猎人被一头熊所伤，他乘的船的船长试图把他带回文明世界，但形势所迫，他无法做到，于是只好雇了两个人留下，目的是让他们送这个猎人最后一程。但这两个人利欲熏心，他们把这个受伤的可怜人洗劫一空，之后把他一个人抛弃在荒凉冰冷的野外等死。然而猎人奇迹般的活了下来，之后开始寻找这两个人开始复仇…",861,1434);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1436,1477);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",1479,1523);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","欧美",1525,1568);
$z[12][4]['name']="area";
$z[13]=Array("field","",1570,1610);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914BS195Z-22Y43.jpg",1612,1705);
$z[14][4]['name']="litpic";

?>