{dede:field name='keywords'}荒野猎人/复仇勇者,荒野猎{/dede:field}
{dede:field name='description'}最新电影《荒野猎人/复仇勇者》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《荒野猎人/复仇勇者》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，{/dede:field}
{dede:field name='title'}荒野猎人/复仇勇者{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2000{/dede:field}
{dede:field name='daoyan'}亚利桑德罗·冈萨雷斯·伊纳里多 </li>
<li class="info_dq">地区：
欧美{/dede:field}
{dede:field name='yanyuan'}莱昂纳多·迪卡普里奥 汤姆·哈迪 威尔·保尔特 多姆纳尔·格里森{/dede:field}
{dede:field name='pingfen'}8.5{/dede:field}
{dede:field name='introduction'}该片根据Michael Punke同名小说改编，由Mark L. 
Smith编剧。故事讲述19世纪一个皮草猎人被一头熊所伤，他乘的船的船长试图把他带回文明世界，但形势所迫，他无法做到，于是只好雇了两个人留下，目的是让他们送这个猎人最后一程。但这两个人利欲熏心，他们把这个受伤的可怜人洗劫一空，之后把他一个人抛弃在荒凉冰冷的野外等死。然而猎人奇迹般的活了下来，之后开始寻找这两个人开始复仇…{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}英语{/dede:field}
{dede:field name='area'}欧美{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914BS195Z-22Y43.jpg{/dede:field}
