<?php
$z[0]=Array("field","我的同学不是人,我的同学",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《我的同学不是人》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《我的同学不是人》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","我的同学不是人",366,425);
$z[2][4]['name']="title";
$z[3]=Array("field","",427,466);
$z[3][4]['name']="writer";
$z[4]=Array("field","",468,507);
$z[4][4]['name']="source";
$z[5]=Array("field","",509,549);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","10.0",551,595);
$z[6][4]['name']="pingfen";
$z[7]=Array("field","轩祥杰",597,645);
$z[7][4]['name']="daoyan";
$z[8]=Array("field","胡悦 高骏",647,700);
$z[8][4]['name']="yanyuan";
$z[9]=Array("field","2016",702,743);
$z[9][4]['name']="time";
$z[10]=Array("field","国语",745,789);
$z[10][4]['name']="yuyan";
$z[11]=Array("field","大陆",791,834);
$z[11][4]['name']="area";
$z[12]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">由北京光影华视文化传媒有限公司、MSI映美传媒、吉诺出品、撲度娱乐、龙胤盛世影业联合出品。女神诺兰（胡悦 饰）在生日当晚，目睹了班上另类学霸发生恐怖变异并惨遭攻击，第二天她对朋友说出真相却无人相信，当众指出变异者后反而受到众人嘲笑。唯一相信她的只有暗恋她多年的姚飞（高骏 饰）。但在姚飞决心拯救女神之际，变异病毒却在校园内飞速扩散甚至威胁到整座城市，姚飞更是遭到诺兰的怀疑。究竟谁才是威胁校园安全的变种人母体？姚飞又能否在千钧一发之际拯救整座城市的安全？</span>",836,1669);
$z[12][4]['name']="introduction";
$z[13]=Array("field","",1671,1712);
$z[13][4]['name']="download";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V33416430P-22c57.jpg",1714,1808);
$z[14][4]['name']="litpic";

?>