{dede:field name='keywords'}我的同学不是人,我的同学{/dede:field}
{dede:field name='description'}最新电影《我的同学不是人》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《我的同学不是人》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您{/dede:field}
{dede:field name='title'}我的同学不是人{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='daoyan'}轩祥杰{/dede:field}
{dede:field name='yanyuan'}胡悦 高骏{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">由北京光影华视文化传媒有限公司、MSI映美传媒、吉诺出品、撲度娱乐、龙胤盛世影业联合出品。女神诺兰（胡悦 饰）在生日当晚，目睹了班上另类学霸发生恐怖变异并惨遭攻击，第二天她对朋友说出真相却无人相信，当众指出变异者后反而受到众人嘲笑。唯一相信她的只有暗恋她多年的姚飞（高骏 饰）。但在姚飞决心拯救女神之际，变异病毒却在校园内飞速扩散甚至威胁到整座城市，姚飞更是遭到诺兰的怀疑。究竟谁才是威胁校园安全的变种人母体？姚飞又能否在千钧一发之际拯救整座城市的安全？</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160322/145V33416430P-22c57.jpg{/dede:field}
