<?php
$z[0]=Array("field","大城小妞/开放之城,大城小",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《大城小妞/开放之城》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《大城小妞/开放之城》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏",78,367);
$z[1][4]['name']="description";
$z[2]=Array("field","大城小妞/开放之城",369,432);
$z[2][4]['name']="title";
$z[3]=Array("field","",434,473);
$z[3][4]['name']="writer";
$z[4]=Array("field","",475,514);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",516,557);
$z[5][4]['name']="time";
$z[6]=Array("field","内详",559,604);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","Abbi Jacobson Ilana Glazer",606,672);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",674,718);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;\">白宫的民主党候选人希拉里-克林顿（HillaryClinton）将客串喜剧中心频道的《大城小妞》（BroadCity）第三季，该剧由《周六夜现场》（SaturdayNightLive）的卡司艾米-波勒（AmyPoehler）担任制片。很巧合的是，很多人认为艾米-波勒是《周六夜现场》中模仿希拉里最成功的人。</span>",720,1220);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1222,1263);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",1265,1309);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","美剧",1311,1354);
$z[12][4]['name']="area";
$z[13]=Array("field","",1356,1396);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914N550a0-264633.jpg",1398,1492);
$z[14][4]['name']="litpic";

?>