{dede:field name='keywords'}大城小妞/开放之城,大城小{/dede:field}
{dede:field name='description'}最新电视剧《大城小妞/开放之城》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《大城小妞/开放之城》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏{/dede:field}
{dede:field name='title'}大城小妞/开放之城{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}内详{/dede:field}
{dede:field name='yanyuan'}Abbi Jacobson Ilana Glazer{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">白宫的民主党候选人希拉里-克林顿（HillaryClinton）将客串喜剧中心频道的《大城小妞》（BroadCity）第三季，该剧由《周六夜现场》（SaturdayNightLive）的卡司艾米-波勒（AmyPoehler）担任制片。很巧合的是，很多人认为艾米-波勒是《周六夜现场》中模仿希拉里最成功的人。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}英语{/dede:field}
{dede:field name='area'}美剧{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914N550a0-264633.jpg{/dede:field}
