{dede:field name='keywords'}实习医生格蕾第十二季,实{/dede:field}
{dede:field name='description'}最新电视剧《实习医生格蕾第十二季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《实习医生格蕾第十二季》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，{/dede:field}
{dede:field name='title'}实习医生格蕾第十二季{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2015{/dede:field}
{dede:field name='daoyan'}内详{/dede:field}
{dede:field name='yanyuan'}内详{/dede:field}
{dede:field name='pingfen'}0.0{/dede:field}
{dede:field name='introduction'}<span style="color:#555555;font-family:宋体;font-size:13.333333969116211px;line-height:20.98958396911621px;">ABC正式宣布续订《实习医生格蕾》第十二季。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}英语{/dede:field}
{dede:field name='area'}美剧{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914N3956010-1LQ5.jpg{/dede:field}
