{dede:field name='keywords'}安娜·弗里茨的尸体,安娜{/dede:field}
{dede:field name='description'}最新电影《安娜·弗里茨的尸体》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《安娜·弗里茨的尸体》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏{/dede:field}
{dede:field name='title'}安娜·弗里茨的尸体{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}Vicens </li>
<li class="info_dq">地区：
其他{/dede:field}
{dede:field name='yanyuan'}Alba Ribas Bernat Saumell </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《安娜·弗里茨的尸体》在线观看" title="《安娜·弗里茨的尸体》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《安娜·弗里茨的尸体》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}7.3{/dede:field}
{dede:field name='introduction'}安娜·弗里茨,一个著名的和漂亮的女演员,最近去世。三个年轻人溜进太平间看到她裸体。着迷于她的美丽,他们决定成为过去的人与她做爱。{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}英语</li>
<li class="yanyuan">主演：
<a href="/search/Alba" target="_blank">Alba</a> <a href="/search/Ribas" target="_blank">Ribas</a> <a href="/search/Bernat" target="_blank">Bernat</a> <a href="/search/Saumell" target="_blank">Saumell</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《安娜·弗里茨的尸体》在线观看" title="《安娜·弗里茨的尸体》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《安娜·弗里茨的尸体》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}其他{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145913Q1R2220-SZ4.jpg{/dede:field}
