{dede:field name='keywords'}双叶庄的朋友,双叶庄的朋{/dede:field}
{dede:field name='description'}最新电影《双叶庄的朋友》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《双叶庄的朋友》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您{/dede:field}
{dede:field name='title'}双叶庄的朋友{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}平松惠美子 </li>
<li class="info_dq">地区：
日韩{/dede:field}
{dede:field name='yanyuan'}市原隼人 臼田麻美 中村伦也 阳月华{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">原舞台导演川村正治和他的妻子美江搬到了双叶庄居住。有一天，川村看到了26年前也住在这里的画家仓田的幻影，两人相似的境遇使他们交谈的很愉快……直到川村看到了无法相信的场景，而这些幻象是否是真实发生过的呢？令人惊讶的事实慢慢清晰了起来。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}日语{/dede:field}
{dede:field name='area'}日韩{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914BMN3P-1SI6.jpg{/dede:field}
