{dede:field name='keywords'}纹身室,纹身室迅雷下载{/dede:field}
{dede:field name='description'}最新电影《纹身室》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《纹身室》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共同享{/dede:field}
{dede:field name='title'}纹身室{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='pingfen'}6.7{/dede:field}
{dede:field name='daoyan'}Devon Downs Kenny Gage{/dede:field}
{dede:field name='yanyuan'}Robert LaSardo Anthony Del Negro 乔丹·詹姆斯·史密斯 Claire Garvey{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='yuyan'}英语{/dede:field}
{dede:field name='area'}欧美{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">一个神秘的游牧称为“艺术家”实践黑暗的艺术形式相传</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160322/145V332O43130-2043B.jpg{/dede:field}
