<?php
$z[0]=Array("field","花心最好命,花心最好命迅",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《花心最好命》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《花心最好命》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","花心最好命",366,419);
$z[2][4]['name']="title";
$z[3]=Array("field","",421,460);
$z[3][4]['name']="writer";
$z[4]=Array("field","",462,501);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",503,544);
$z[5][4]['name']="time";
$z[6]=Array("field","老鹰 </li>\r\n<li class=\"info_dq\">地区：\r\n大陆",546,636);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","夏以俪 亚孟乐",638,697);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","4.0",699,742);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">一个是终日混迹夜店，雅号夜店小王子的花心男罗琦。一个是惨遭未婚夫和闺蜜双双背叛的失意女张榕。两个性格南辕北辙的单身男女却随着一场刻意制造的艳遇，两人解不开理还乱的.</span>",744,1150);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1152,1193);
$z[10][4]['name']="download";
$z[11]=Array("field","国语",1195,1239);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","大陆",1241,1284);
$z[12][4]['name']="area";
$z[13]=Array("field","",1286,1326);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914BL5GP-1IB7.jpg",1328,1419);
$z[14][4]['name']="litpic";

?>