<?php
$z[0]=Array("field","唐僧肉惊天大骗局,唐僧肉",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《唐僧肉惊天大骗局》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《唐僧肉惊天大骗局》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","唐僧肉惊天大骗局",366,428);
$z[2][4]['name']="title";
$z[3]=Array("field","",430,469);
$z[3][4]['name']="writer";
$z[4]=Array("field","",471,510);
$z[4][4]['name']="source";
$z[5]=Array("field","7.0",512,555);
$z[5][4]['name']="pingfen";
$z[6]=Array("field","疙瘩",557,602);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","疙瘩 花旗",604,657);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","2016",659,700);
$z[8][4]['name']="time";
$z[9]=Array("field","国语",702,746);
$z[9][4]['name']="yuyan";
$z[10]=Array("field","大陆",748,791);
$z[10][4]['name']="area";
$z[11]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">唐僧（疙瘩 饰）和沙僧（黄旭高 饰）穿越到现代，偶遇长相一模一样的转世唐僧，更巧的是转世唐僧竟然是个悍匪，两个唐僧引发一场惊天大骗局。</span>",793,1152);
$z[11][4]['name']="introduction";
$z[12]=Array("field","",1154,1195);
$z[12][4]['name']="download";
$z[13]=Array("field","",1197,1237);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V332GAE0-156409.jpg",1239,1332);
$z[14][4]['name']="litpic";

?>