{dede:field name='keywords'}青少年哪吒,青少年哪吒迅{/dede:field}
{dede:field name='description'}最新电影《青少年哪吒》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《青少年哪吒》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋{/dede:field}
{dede:field name='title'}青少年哪吒{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='daoyan'}蔡明亮{/dede:field}
{dede:field name='yanyuan'}李康生 王渝文 陈昭荣{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='yuyan'}{/dede:field}
{dede:field name='area'}欧美{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">拿着退来的补习费用逃离压抑的补习班后，小康（李康生）开始漫无目的的在西门町晃荡，偶遇有着另一种身份过着另一种日子的“不良少年”阿泽（陈昭荣），被其吸引，渴望融入其生活。但阿泽只是表面看来光鲜，打电动、开一辆重型机车在街上呼啸只因可以暂时让自己看起来像个胜利者，内心却一样是封闭孤独的。 　　在跟踪阿泽的过程中，小康渐发觉自己的性向可能与大多数人有别，也发现阿泽生活的单调与苦闷。但好过小康的是，阿泽虽也几乎不知何为亲情，却有“好兄弟”阿彬（任长彬）常陪左右，有阿桂（王渝文）暂当女友，来过“当天和尚撞天钟”的生活。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160322/145V3340512160-155P4.jpg{/dede:field}
