<?php
$z[0]=Array("field","青少年哪吒,青少年哪吒迅",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《青少年哪吒》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《青少年哪吒》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","青少年哪吒",366,419);
$z[2][4]['name']="title";
$z[3]=Array("field","",421,460);
$z[3][4]['name']="writer";
$z[4]=Array("field","",462,501);
$z[4][4]['name']="source";
$z[5]=Array("field","10.0",503,547);
$z[5][4]['name']="pingfen";
$z[6]=Array("field","蔡明亮",549,597);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","李康生 王渝文 陈昭荣",599,668);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","2016",670,711);
$z[8][4]['name']="time";
$z[9]=Array("field","",713,751);
$z[9][4]['name']="yuyan";
$z[10]=Array("field","欧美",753,796);
$z[10][4]['name']="area";
$z[11]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">拿着退来的补习费用逃离压抑的补习班后，小康（李康生）开始漫无目的的在西门町晃荡，偶遇有着另一种身份过着另一种日子的“不良少年”阿泽（陈昭荣），被其吸引，渴望融入其生活。但阿泽只是表面看来光鲜，打电动、开一辆重型机车在街上呼啸只因可以暂时让自己看起来像个胜利者，内心却一样是封闭孤独的。 　　在跟踪阿泽的过程中，小康渐发觉自己的性向可能与大多数人有别，也发现阿泽生活的单调与苦闷。但好过小康的是，阿泽虽也几乎不知何为亲情，却有“好兄弟”阿彬（任长彬）常陪左右，有阿桂（王渝文）暂当女友，来过“当天和尚撞天钟”的生活。</span>",798,1729);
$z[11][4]['name']="introduction";
$z[12]=Array("field","",1731,1772);
$z[12][4]['name']="download";
$z[13]=Array("field","",1774,1814);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V3340512160-155P4.jpg",1816,1911);
$z[14][4]['name']="litpic";

?>