<?php
$z[0]=Array("field","第五波\\第五天劫,第五波",0,73);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《第五波\\第五天劫》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《第五波\\第五天劫》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您",75,364);
$z[1][4]['name']="description";
$z[2]=Array("field","第五波\\第五天劫",366,426);
$z[2][4]['name']="title";
$z[3]=Array("field","",428,467);
$z[3][4]['name']="writer";
$z[4]=Array("field","",469,508);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",510,551);
$z[5][4]['name']="time";
$z[6]=Array("field","J·布莱克森 </li>\r\n<li class=\"info_dq\">地区：\r\n欧美",553,652);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","科洛·莫瑞兹 尼克·罗宾森 朗·里维斯顿 玛姬·丝弗",654,762);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",764,808);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">影片改编自同名畅销小说，故事讲述地球遭到外星人攻击，人类文明退回石器时代，16岁少女凯西作为仅存人类之一，挣扎生存，寻找希望</span>",810,1154);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1156,1197);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",1199,1243);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","欧美",1245,1288);
$z[12][4]['name']="area";
$z[13]=Array("field","",1290,1330);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914B6000A0-K0b.jpg",1332,1424);
$z[14][4]['name']="litpic";

?>