{dede:field name='keywords'}第五波\第五天劫,第五波{/dede:field}
{dede:field name='description'}最新电影《第五波\第五天劫》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《第五波\第五天劫》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您{/dede:field}
{dede:field name='title'}第五波\第五天劫{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}J·布莱克森 </li>
<li class="info_dq">地区：
欧美{/dede:field}
{dede:field name='yanyuan'}科洛·莫瑞兹 尼克·罗宾森 朗·里维斯顿 玛姬·丝弗{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">影片改编自同名畅销小说，故事讲述地球遭到外星人攻击，人类文明退回石器时代，16岁少女凯西作为仅存人类之一，挣扎生存，寻找希望</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}英语{/dede:field}
{dede:field name='area'}欧美{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914B6000A0-K0b.jpg{/dede:field}
