{dede:field name='keywords'}反黑行动组/反帮派,反黑行{/dede:field}
{dede:field name='description'}最新电影《反黑行动组/反帮派》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《反黑行动组/反帮派》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，{/dede:field}
{dede:field name='title'}反黑行动组/反帮派{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='daoyan'}Benjamin Rocher{/dede:field}
{dede:field name='yanyuan'}让·雷诺 卡特琳娜·莫里诺 蒂埃里·钮维{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='yuyan'}英语{/dede:field}
{dede:field name='area'}欧美{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">Serge Buren追踪不法分子方法很不一般。他与女同事有私情，而新上任的上司恰好又是同事的老公。在追踪珠宝抢劫犯的案中，上司把他的编队隔离出来，事后证明，这是劫匪的调虎离山计。他独自行动跟上犯人却遇到激励火拼，伤亡惨重，女同事死了，他是否可以用自己的方法破案呢？</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160322/145V333YSZ-5c62.jpg{/dede:field}
