<?php
$z[0]=Array("field","重生之名流巨星,重生之名",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《重生之名流巨星》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《重生之名流巨星》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","重生之名流巨星",366,425);
$z[2][4]['name']="title";
$z[3]=Array("field","",427,466);
$z[3][4]['name']="writer";
$z[4]=Array("field","",468,507);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",509,550);
$z[5][4]['name']="time";
$z[6]=Array("field","赵小溪",552,600);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","马可 纳瓦·君拉纳拉 徐海乔",602,679);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","9.6",681,724);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">根据作家青罗扇子同名小说改编，由企鹅影业、新派系文化传媒联合出品，马可、张馨予、Pong、韩彩英、徐海乔等主演的娱乐圈悬疑偶像剧《重生之名流巨星》已于2015年12月杀青，预计2016年春季在腾讯视频独播。 　　该剧讲述了经历变故后再入娱乐圈的云修，从一个名不见经传的小演员，一步步迈向顶峰的故事。被誉为韩剧画质、美剧节奏的励志悬偶剧《重生之名流巨星》，不仅集结中韩意泰优秀演员，更将多角度全景式的展现娱乐圈：作为大众情人的明星们，内心世界到底拥有怎样的色彩？星光熠熠的娱乐圈幕后，是否有着不为人知的辛酸？</span>",726,1617);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1619,1660);
$z[10][4]['name']="download";
$z[11]=Array("field","国语",1662,1706);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","大陆",1708,1751);
$z[12][4]['name']="area";
$z[13]=Array("field","",1753,1793);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914NI3260-J636.jpg",1795,1887);
$z[14][4]['name']="litpic";

?>