{dede:field name='keywords'}澄沙之味,澄沙之味迅雷下{/dede:field}
{dede:field name='description'}最新电影《澄沙之味》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《澄沙之味》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共{/dede:field}
{dede:field name='title'}澄沙之味电影迅雷高清下载,澄沙之味高清下载在线观看 - 其他 - a67手机电影网{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}河濑直美 </li>
<li class="info_dq">地区：
其他{/dede:field}
{dede:field name='yanyuan'}树木希林 永濑正敏 市原悦子 内田伽罗 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《澄沙之味》在线观看" title="《澄沙之味》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《澄沙之味》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">日本老牌女星树木希林与市原悦子，确定出演由导演河濑直美执导的新片《澄沙之味》，这是两位日本元老级女星的首度合作。 该片根据明川哲也的同名小说改编，全片以一家铜锣烧店为舞台，讲述了曾身患汉森病的老人德江（树木希林饰）与周围人展开的温情交流物语。首度与导演河濑合作的市原，扮演女主人公德江的好友、在疗养所咖啡馆内工作的佳子。此外，扮演铜锣烧店老板的是实力派男星永濑正敏。 都市一隅，樱花盛开的公园内，经营着名为“铜锣之春”的铜锣烧专卖店。拥有不堪回首过去的千太郎（永濑正敏 饰）因缘际会成为专卖店的雇佣店长，他和作为常客的初中生若菜（内田伽罗 饰）日复一日打发这无聊单调的时光。这一天，一位老太太不期而至。她名叫德江（树木希林 饰），因看到专卖店的招聘小广告而登门拜访。德江带来了自己熬制的豆馅儿，本想敷衍一下将老人打发走的千太郎，在尝过豆馅儿后发现意外地好吃。以此为机缘，老人成为“铜锣之春”的一员，这家小店也由此变得热闹起来。就在此时，针对于德江无情的传言悄然蔓延，小店的经营状况江河日下，千太郎被逼着做出重要的决定。不经意间，这些平凡之人的命运彻底改变……</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}日语</li>
<li class="yanyuan">主演：
<a href="/search/%E6%A0%91%E6%9C%A8%E5%B8%8C%E6%9E%97" target="_blank">树木希林</a> <a href="/search/%E6%B0%B8%E6%BF%91%E6%AD%A3%E6%95%8F" target="_blank">永濑正敏</a> <a href="/search/%E5%B8%82%E5%8E%9F%E6%82%A6%E5%AD%90" target="_blank">市原悦子</a> <a href="/search/%E5%86%85%E7%94%B0%E4%BC%BD%E7%BD%97" target="_blank">内田伽罗</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《澄沙之味》在线观看" title="《澄沙之味》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《澄沙之味》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}其他{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/14591344LK410-15D4.jpg{/dede:field}
