<?php
$z[0]=Array("field","牯岭街少年杀人事件,牯岭",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《牯岭街少年杀人事件》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《牯岭街少年杀人事件》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","牯岭街少年杀人事件",366,431);
$z[2][4]['name']="title";
$z[3]=Array("field","",433,472);
$z[3][4]['name']="writer";
$z[4]=Array("field","",474,513);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",515,556);
$z[5][4]['name']="time";
$z[6]=Array("field","杨德昌 </li>\r\n<li class=\"info_dq\">地区：\r\n港台",558,651);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","张震 杨静怡",653,709);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","6.5",711,754);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;\">结识小明（杨静怡）前，小四（张震）是典型的乖仔，是父母的希望和兄妹的骄傲（一家人指望他考上名牌大学将来提升全家的社会地位），他有一个喜欢摇滚乐的自称“小猫王（王启赞）”的好友，两人虽会去树林看人幽会，但过的是与周围诸多在“小公园”混的少年人完全两样的生活。 喜欢上小明后，小四便像跌进一个无底深渊，开始被外界的各种力量牵着鼻子走。新识仰慕对象honey（林鸿铭）猝死，一向敬重的父亲的自尊与精神因为某次事件严重受损，加上将一次次“欺骗玩弄”他感情的小明“看透”，血气方刚又有很强道德感的小四终于走上犯罪的道路，期望用自己的刀结束事件的根源。但小四不知的是，他眼中的根源只是这条食物链中微不足道的一环。</span>",756,1791);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1793,1834);
$z[10][4]['name']="download";
$z[11]=Array("field","国语",1836,1880);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","港台",1882,1925);
$z[12][4]['name']="area";
$z[13]=Array("field","",1927,1967);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914C0243C0-644J.jpg",1969,2062);
$z[14][4]['name']="litpic";

?>