{dede:field name='keywords'}牯岭街少年杀人事件,牯岭{/dede:field}
{dede:field name='description'}最新电影《牯岭街少年杀人事件》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《牯岭街少年杀人事件》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收{/dede:field}
{dede:field name='title'}牯岭街少年杀人事件{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}杨德昌 </li>
<li class="info_dq">地区：
港台{/dede:field}
{dede:field name='yanyuan'}张震 杨静怡{/dede:field}
{dede:field name='pingfen'}6.5{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">结识小明（杨静怡）前，小四（张震）是典型的乖仔，是父母的希望和兄妹的骄傲（一家人指望他考上名牌大学将来提升全家的社会地位），他有一个喜欢摇滚乐的自称“小猫王（王启赞）”的好友，两人虽会去树林看人幽会，但过的是与周围诸多在“小公园”混的少年人完全两样的生活。 喜欢上小明后，小四便像跌进一个无底深渊，开始被外界的各种力量牵着鼻子走。新识仰慕对象honey（林鸿铭）猝死，一向敬重的父亲的自尊与精神因为某次事件严重受损，加上将一次次“欺骗玩弄”他感情的小明“看透”，血气方刚又有很强道德感的小四终于走上犯罪的道路，期望用自己的刀结束事件的根源。但小四不知的是，他眼中的根源只是这条食物链中微不足道的一环。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}港台{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914C0243C0-644J.jpg{/dede:field}
