{dede:field name='keywords'}私家法医第一季,私家法医{/dede:field}
{dede:field name='description'}最新电视剧《私家法医第一季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《私家法医第一季》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让{/dede:field}
{dede:field name='title'}私家法医第一季{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}理查德·谢帕德{/dede:field}
{dede:field name='yanyuan'}摩里斯·切斯塔特  麦琪·伊丽莎白·琼斯  欧文·哈恩{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">Miami pathologist, Dr. Rosewood, finds secrets in people's bodies using his , state-of-the-art laboratory equipment.</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}英语{/dede:field}
{dede:field name='area'}美剧{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914O059DZ-22YM.jpg{/dede:field}
