<?php
$z[0]=Array("field","私家法医第一季,私家法医",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《私家法医第一季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《私家法医第一季》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","私家法医第一季",366,425);
$z[2][4]['name']="title";
$z[3]=Array("field","",427,466);
$z[3][4]['name']="writer";
$z[4]=Array("field","",468,507);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",509,550);
$z[5][4]['name']="time";
$z[6]=Array("field","理查德·谢帕德",552,611);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","摩里斯·切斯塔特  麦琪·伊丽莎白·琼斯  欧文·哈恩",613,722);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",724,768);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;\">Miami pathologist, Dr. Rosewood, finds secrets in people's bodies using his , state-of-the-art laboratory equipment.</span>",770,1033);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1035,1076);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",1078,1122);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","美剧",1124,1167);
$z[12][4]['name']="area";
$z[13]=Array("field","",1169,1209);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914O059DZ-22YM.jpg",1211,1303);
$z[14][4]['name']="litpic";

?>