<?php
$z[0]=Array("field","霹雳囧花,霹雳囧花迅雷下",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《霹雳囧花》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《霹雳囧花》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","霹雳囧花",366,416);
$z[2][4]['name']="title";
$z[3]=Array("field","",418,457);
$z[3][4]['name']="writer";
$z[4]=Array("field","",459,498);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",500,541);
$z[5][4]['name']="time";
$z[6]=Array("field","卓韵芝 </li>\r\n<li class=\"info_dq\">地区：\r\n大陆",543,636);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","周秀娜 卢颂之 余晓彤 徐天佑",638,717);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",719,763);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">阿宝（周秀娜 饰），阿娇（卢颂之 饰）和TT（余晓彤 饰）各自面对着她们的深渊，一时之间找不到解决问题的方法，人生陷入了停顿和困境之中。一笔飞来横财吸引三人踏上了远赴马来西亚的旅途，她们以为，在那里等待着她们的会是充满了幸福和快乐的生活，以及享用不尽的荣华富贵。 　　然而，令三人没有想到的是，从她们踏上旅途的那一刻起，即落入了神秘女子诸葛（童冰玉 饰）一手策划的圈套之中，三人不仅没能享福，甚至还落入了贩卖妇女的人贩手中。兔子急了也要人，可不要小看这三个看似孱弱的女人，当她们尽情使用女人的手段来对抗专门欺辱压迫女人的罪犯们之时，可没有几个人能够与她们匹敌哦。</span>",765,1756);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1758,1799);
$z[10][4]['name']="download";
$z[11]=Array("field","国语",1801,1845);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","大陆",1847,1890);
$z[12][4]['name']="area";
$z[13]=Array("field","",1892,1932);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914B9E0510-2Q51.jpg",1934,2027);
$z[14][4]['name']="litpic";

?>