{dede:field name='keywords'}东京伤情故事,东京伤情故{/dede:field}
{dede:field name='description'}最新电影《东京伤情故事》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《东京伤情故事》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您{/dede:field}
{dede:field name='title'}东京伤情故事{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2014{/dede:field}
{dede:field name='daoyan'}未知</li>
<li class="info_dq">地区：
日韩{/dede:field}
{dede:field name='yanyuan'}吉田钢太郎 高畑充希 片桐仁 高冈早纪 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《东京伤情故事》在线观看" title="《东京伤情故事》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《东京伤情故事》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}5.7{/dede:field}
{dede:field name='introduction'}{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}日语</li>
<li class="yanyuan">主演：
<a href="/search/%E5%90%89%E7%94%B0%E9%92%A2%E5%A4%AA%E9%83%8E" target="_blank">吉田钢太郎</a> <a href="/search/%E9%AB%98%E7%95%91%E5%85%85%E5%B8%8C" target="_blank">高畑充希</a> <a href="/search/%E7%89%87%E6%A1%90%E4%BB%81" target="_blank">片桐仁</a> <a href="/search/%E9%AB%98%E5%86%88%E6%97%A9%E7%BA%AA" target="_blank">高冈早纪</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《东京伤情故事》在线观看" title="《东京伤情故事》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《东京伤情故事》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}日韩{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145913Q156160-63K4.jpg{/dede:field}
