<?php
$z[0]=Array("field","最佳恋人,最佳恋人电视剧",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《最佳恋人》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《最佳恋人》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","最佳恋人",366,416);
$z[2][4]['name']="title";
$z[3]=Array("field","",418,457);
$z[3][4]['name']="writer";
$z[4]=Array("field","",459,498);
$z[4][4]['name']="source";
$z[5]=Array("field","2015",500,541);
$z[5][4]['name']="time";
$z[6]=Array("field","崔昌旭",543,591);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","河熙罗 姜敏京 赵安 姜泰伍 郑灿 郭熙成",593,686);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","6.2",688,731);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"color:#555555;font-family:宋体;line-height:21px;\">该剧以三对母女为中心，讲述了与在她们身边发生的有关<a href=\"\" target=\"_target\">韩国</a>社会的现状。</span>",733,981);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",983,1024);
$z[10][4]['name']="download";
$z[11]=Array("field","韩语",1026,1070);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","韩剧",1072,1115);
$z[12][4]['name']="area";
$z[13]=Array("field","",1117,1157);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914N2X3350-123O4.jpg",1159,1253);
$z[14][4]['name']="litpic";

?>