{dede:field name='keywords'}降魔传,降魔传迅雷下载{/dede:field}
{dede:field name='description'}最新电影《降魔传》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《降魔传》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共同享{/dede:field}
{dede:field name='title'}降魔传{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}未知</li>
<li class="info_dq">地区：
大陆{/dede:field}
{dede:field name='yanyuan'}于歌 傅筱{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">在中国几千年的文化传承中流传着诸多人、神、妖三界有关的玄幻故事传说如《白娘子传奇》《八仙过海》等等，人们总是对玄幻的世界充满了好奇。《降魔传》则讲述了道教弟子——看护太合殿太衡宝盒的道童张小虎因心慈善怜，相信了美丽兔妖的百般请求，意外开启了尘封已久关押着众妖的太衡宝盒，导致被镇压的众妖四散奔逃且纷纷逃到了结界之外，重现人间。张小虎带着师傅所赐的玉佩进城助其寻找有缘人方可一举降服群妖。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914C1645640-141I4.jpg{/dede:field}
