{dede:field name='keywords'}城市不知我哭泣,城市不知{/dede:field}
{dede:field name='description'}最新电影《城市不知我哭泣》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《城市不知我哭泣》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您{/dede:field}
{dede:field name='title'}城市不知我哭泣{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='daoyan'}袁一木{/dede:field}
{dede:field name='yanyuan'}田子琳 郝旭晖 马鑫鑫 周莹{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">农村女孩边菲菲在大学毕业后，发誓要自己走出一片天地，改变自己的人生。可面对纷繁复杂的社会，和尔虞我诈的人间是非，边菲菲真是感到很难很难。从求职屡屡受挫，到当上饭店普通服务员。好朋友的出现改变了她的一切，她从车模到堕落的糜烂生活，很长一段时间里，边菲菲沉浸在纸醉金迷的世界里，而她却在糜烂的生活中一次次受到伤害，让她在一次事件中彻底懂了人生的真谛。她决定改变自己，用自己的双手撑起一片属于自己的蓝天，时尚内涵携带着对梦想的追求，或许一片新的蓝天会呈现在她的面前--</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160322/145V33264220F-b443.jpg{/dede:field}
