{dede:field name='keywords'}道歉大师,道歉大师迅雷下{/dede:field}
{dede:field name='description'}最新电影《道歉大师》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《道歉大师》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共{/dede:field}
{dede:field name='title'}道歉大师{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2013{/dede:field}
{dede:field name='daoyan'}水田伸生 </li>
<li class="info_dq">地区：
日韩{/dede:field}
{dede:field name='yanyuan'}阿部隆史 井上真央 冈田将生 尾野真千子 高桥克实 松雪泰子 竹野内丰 荒川良良 滨田岳 小野武彦 滨田麻里 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《道歉大师》在线观看" title="《道歉大师》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《道歉大师》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}6.3{/dede:field}
{dede:field name='introduction'}{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}日语</li>
<li class="yanyuan">主演：
<a href="/search/%E9%98%BF%E9%83%A8%E9%9A%86%E5%8F%B2" target="_blank">阿部隆史</a> <a href="/tag/2541/" target="_blank">井上真央</a> <a href="/tag/7075/" target="_blank">冈田将生</a> <a href="/search/%E5%B0%BE%E9%87%8E%E7%9C%9F%E5%8D%83%E5%AD%90" target="_blank">尾野真千子</a> <a href="/search/%E9%AB%98%E6%A1%A5%E5%85%8B%E5%AE%9E" target="_blank">高桥克实</a> <a href="/tag/7485/" target="_blank">松雪泰子</a> <a href="/search/%E7%AB%B9%E9%87%8E%E5%86%85%E4%B8%B0" target="_blank">竹野内丰</a> <a href="/search/%E8%8D%92%E5%B7%9D%E8%89%AF%E8%89%AF" target="_blank">荒川良良</a> <a href="/search/%E6%BB%A8%E7%94%B0%E5%B2%B3" target="_blank">滨田岳</a> <a href="/search/%E5%B0%8F%E9%87%8E%E6%AD%A6%E5%BD%A6" target="_blank">小野武彦</a> <a href="/search/%E6%BB%A8%E7%94%B0%E9%BA%BB%E9%87%8C" target="_blank">滨田麻里</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《道歉大师》在线观看" title="《道歉大师》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《道歉大师》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}日韩{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145913Q5316310-21N0.jpg{/dede:field}
