{dede:field name='keywords'}战狼传说,战狼传说迅雷下{/dede:field}
{dede:field name='description'}最新电影《战狼传说》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《战狼传说》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共{/dede:field}
{dede:field name='title'}战狼传说{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}1997{/dede:field}
{dede:field name='daoyan'}甄子丹 </li>
<li class="info_dq">地区：
港台{/dede:field}
{dede:field name='yanyuan'}甄子丹 李若彤 黄子华{/dede:field}
{dede:field name='pingfen'}7.6{/dede:field}
{dede:field name='introduction'}<p>
	《战狼传说》是甄子丹导演生涯的处女作，可以说这是一部奇妙的作品，一半笼罩在晨曦天雾的朦胧光影里；而另一半则是标准的黑帮故事。片中充满了顶级的动作、激烈狂野的打斗。令香港电影评论家Po Kam-hung由衷地称赞道：单刃的刀锋迎战飞斧黑帮，从双腿间飞过的柴刀，T形凳脚对决铁链重击，赤手空拳血拼锋利鹰爪。高速拍摄，创造性的动作场景，实验性的运镜和剪辑，贯穿全片的流畅的韵律在这时已经指明了甄子丹导演事业日后的发展方向。<br />
江湖传说的战狼，战无不胜，武功深不可测。战狼隐姓埋名多年，几乎没有人见过他的真面目，但无人知道他的身份，而且每一个人都想挑战他。年轻人BEN(梁汉文饰)不断通过电脑互联网寻访战狼。有一天，他终于接受到答复，根据神秘的指示去赴约，接头人威出现，带BEN见到战狼。战狼不过是个老者冯文轩(甄子丹饰)，BEN见轩并非想像中的战狼，十分失望，更出言讥讽，威心有不忿，并道出战狼传说……<br />
战后的农村，民不聊生。孤儿阿威流落乡村，山贼伏击村落。衣着光鲜、沉默寡言的刀客战狼前来相救，用神速刀法如斩乱麻一般将来敌击退，并道出此行的目的是找寻昔日的情侣。当战狼在残破小屋遇上青梅竹马的情人“怡”时，却又因失去记忆难成姻缘，而当两人得搭昔日情时，“怡”偏偏被凶残的七狼党抓去，战狼别无选择，只有独自向凶狠残暴的七狼党发起进攻……
</p>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}粤语{/dede:field}
{dede:field name='area'}港台{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914C2343950-1c641.jpg{/dede:field}
