<?php
$z[0]=Array("field","再见了德彪西～钢琴侦探",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《再见了德彪西～钢琴侦探岬洋介》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《再见了德彪西～钢琴侦探岬洋介》完整版迅雷高清下载，以及高清在线播",76,363);
$z[1][4]['name']="description";
$z[2]=Array("field","再见了德彪西～钢琴侦探岬洋介",365,445);
$z[2][4]['name']="title";
$z[3]=Array("field","",447,486);
$z[3][4]['name']="writer";
$z[4]=Array("field","",488,527);
$z[4][4]['name']="source";
$z[5]=Array("field","10.0",529,573);
$z[5][4]['name']="pingfen";
$z[6]=Array("field","菅原伸太郎",575,629);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","东出昌大 黑岛结菜 北大路欣也",631,712);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","2016",714,755);
$z[8][4]['name']="time";
$z[9]=Array("field","日语",757,801);
$z[9][4]['name']="yuyan";
$z[10]=Array("field","日韩",803,846);
$z[10][4]['name']="area";
$z[11]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">该剧改编自获得第八届“这本推理小说真了不起”大奖的中山七里的畅销作品《再见了德彪西》，2013年曾被翻拍成电影，由桥本爱主演。电视剧中，左耳突然失聪的天才钢琴师、名侦探岬洋介针对发生在其钢琴课女学生（黑岛结菜）身边的事件进行侦查和破解。</span>",848,1356);
$z[11][4]['name']="introduction";
$z[12]=Array("field","",1358,1399);
$z[12][4]['name']="download";
$z[13]=Array("field","",1401,1441);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V333c154F-1153L.jpg",1443,1536);
$z[14][4]['name']="litpic";

?>