{dede:field name='keywords'}萤火侠,萤火侠迅雷下载{/dede:field}
{dede:field name='description'}最新电影《萤火侠》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《萤火侠》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共同享{/dede:field}
{dede:field name='title'}萤火侠电影迅雷高清下载,萤火侠高清下载在线观看 - 其他 - a67手机电影网{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2014{/dede:field}
{dede:field name='daoyan'}蔡业翰 钟明桦 </li>
<li class="info_dq">地区：
其他{/dede:field}
{dede:field name='yanyuan'}程旭辉 邱文博 陈美君 林静苗 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《萤火侠》在线观看" title="《萤火侠》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《萤火侠》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}8.9{/dede:field}
{dede:field name='introduction'}《萤火侠》汇聚了新加坡和马来西亚多位谐星、无厘头的喜剧情节和正义的故事结构。电影讲述一位伸张正义的阿发把自己变成超级英雄，但是本身完全没有超能力，歪打正着后小有名气。并聘请了一位超级英雄助理，和另外一班反派超级英雄为社会打击罪犯。 这是一部以打击罪犯概念出發，以超级英雄为题材的時裝电影。所以电影里会出现美式超级英雄服装，多位演员在戏里演超级英雄，将会有很酷的超级英雄服装。在美式超级英雄电影里的英雄都偏爱紧身服，凸现其健硕肌肉的线条美，散发男性的雄壮，露出部分面部。{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}马来语</li>
<li class="yanyuan">主演：
<a href="/tag/5531/" target="_blank">程旭辉</a> <a href="/search/%E9%82%B1%E6%96%87%E5%8D%9A" target="_blank">邱文博</a> <a href="/search/%E9%99%88%E7%BE%8E%E5%90%9B" target="_blank">陈美君</a> <a href="/search/%E6%9E%97%E9%9D%99%E8%8B%97" target="_blank">林静苗</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《萤火侠》在线观看" title="《萤火侠》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《萤火侠》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}其他{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/14591344021FP-U516.jpg{/dede:field}
