{dede:field name='keywords'}薛定谔的猫,薛定谔的猫迅{/dede:field}
{dede:field name='description'}最新电影《薛定谔的猫》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《薛定谔的猫》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋{/dede:field}
{dede:field name='title'}薛定谔的猫{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}冯桂云 </li>
<li class="info_dq">地区：
大陆{/dede:field}
{dede:field name='yanyuan'}阮晓伟 王馨瑶 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《薛定谔的猫》在线观看" title="《薛定谔的猫》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《薛定谔的猫》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}归国当天意外邂逅了身着古装戏的替身艾金，尾随着艾金而后进入了片场并且见识到了国内的拍戏方式。之后，晓艺在酒吧里被国内的旧友Tony跟笑笑灌输追女孩子的方法。Tony是个典型的“快餐爱情”消费者，无时无刻都在运用自己的科学理论泡妞，无时无刻都处于猎艳的状态，为了让晓艺成功追上艾金，Tony教授给晓艺一个理论——“薛定谔的猫”（把猫关在一个放置毒气开关的箱子里，猫的死活取决于你打开箱子那瞬间，在没打开箱子之前，猫处于一种“即生又死”的状态）晓艺根据Tony的理论对艾金展开追求攻势，在眼看得手之际，艾金却没接受晓艺。{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语</li>
<li class="yanyuan">主演：
<a href="/search/%E9%98%AE%E6%99%93%E4%BC%9F" target="_blank">阮晓伟</a> <a href="/search/%E7%8E%8B%E9%A6%A8%E7%91%B6" target="_blank">王馨瑶</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《薛定谔的猫》在线观看" title="《薛定谔的猫》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《薛定谔的猫》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145913Q311HZ-1O942.jpg{/dede:field}
