{dede:field name='keywords'}相棒第十四季,相棒第十四{/dede:field}
{dede:field name='description'}最新电视剧《相棒第十四季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《相棒第十四季》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和{/dede:field}
{dede:field name='title'}相棒第十四季{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2015{/dede:field}
{dede:field name='daoyan'}和泉圣治{/dede:field}
{dede:field name='yanyuan'}水谷丰 反町隆史 铃木杏树 石坂浩二{/dede:field}
{dede:field name='pingfen'}0.0{/dede:field}
{dede:field name='introduction'}<span style="color:#555555;font-family:simsun;font-size:13px;line-height:26px;">相棒第十四季</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}日语{/dede:field}
{dede:field name='area'}韩剧{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914N3534c0-164341.jpg{/dede:field}
