<?php
$z[0]=Array("field","相棒第十四季,相棒第十四",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《相棒第十四季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《相棒第十四季》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","相棒第十四季",366,422);
$z[2][4]['name']="title";
$z[3]=Array("field","",424,463);
$z[3][4]['name']="writer";
$z[4]=Array("field","",465,504);
$z[4][4]['name']="source";
$z[5]=Array("field","2015",506,547);
$z[5][4]['name']="time";
$z[6]=Array("field","和泉圣治",549,600);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","水谷丰 反町隆史 铃木杏树 石坂浩二",602,690);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","0.0",692,735);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"color:#555555;font-family:simsun;font-size:13px;line-height:26px;\">相棒第十四季</span>",737,887);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",889,930);
$z[10][4]['name']="download";
$z[11]=Array("field","日语",932,976);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","韩剧",978,1021);
$z[12][4]['name']="area";
$z[13]=Array("field","",1023,1063);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914N3534c0-164341.jpg",1065,1160);
$z[14][4]['name']="litpic";

?>