{dede:field name='keywords'}埃尔塞差点改变世界的人{/dede:field}
{dede:field name='description'}最新电影《埃尔塞差点改变世界的人》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《埃尔塞差点改变世界的人》完整版迅雷高清下载，以及高清在线播放，轻轻一点{/dede:field}
{dede:field name='title'}埃尔塞差点改变世界的人{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pingfen'}7.0{/dede:field}
{dede:field name='daoyan'}奥利弗·西斯贝格{/dede:field}
{dede:field name='yanyuan'}卡塔琳娜·舒特勒 伯格哈特·克莱斯纳 菲力克斯·伊特纳{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='yuyan'}英语{/dede:field}
{dede:field name='area'}欧美{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">《埃尔塞: 将近改变世界的人》讲述的是刺杀希特勒事件，但影片里的史实比《行动目标希特勒》要早几年。1939年。希特勒差一点被一个名叫埃尔塞的木匠干掉。那一年，希特勒的权力正在逐渐迈向顶峰，当大多数人都在狂热崇拜之时，埃尔塞成了少数几个的正义斗士。在精密的计划之下，他在希特勒演讲的讲台附近设置一个定时炸弹。可惜的是，希特勒的演讲结束得太早，炸弹引爆时希特勒已经不在现场。埃尔塞在当年11月遭到了纳粹的逮捕，遭处决。影片讲述了一段惊心动魄的故事，本土演员的演出保持了原汁原味。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160322/145V333P14Z-294E6.jpg{/dede:field}
