<?php
$z[0]=Array("field","埃尔塞差点改变世界的人",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《埃尔塞差点改变世界的人》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《埃尔塞差点改变世界的人》完整版迅雷高清下载，以及高清在线播放，轻轻一点",76,363);
$z[1][4]['name']="description";
$z[2]=Array("field","埃尔塞差点改变世界的人",365,436);
$z[2][4]['name']="title";
$z[3]=Array("field","",438,477);
$z[3][4]['name']="writer";
$z[4]=Array("field","",479,518);
$z[4][4]['name']="source";
$z[5]=Array("field","7.0",520,563);
$z[5][4]['name']="pingfen";
$z[6]=Array("field","奥利弗·西斯贝格",565,627);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","卡塔琳娜·舒特勒 伯格哈特·克莱斯纳 菲力克斯·伊特纳",629,743);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","2016",745,786);
$z[8][4]['name']="time";
$z[9]=Array("field","英语",788,832);
$z[9][4]['name']="yuyan";
$z[10]=Array("field","欧美",834,877);
$z[10][4]['name']="area";
$z[11]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">《埃尔塞: 将近改变世界的人》讲述的是刺杀希特勒事件，但影片里的史实比《行动目标希特勒》要早几年。1939年。希特勒差一点被一个名叫埃尔塞的木匠干掉。那一年，希特勒的权力正在逐渐迈向顶峰，当大多数人都在狂热崇拜之时，埃尔塞成了少数几个的正义斗士。在精密的计划之下，他在希特勒演讲的讲台附近设置一个定时炸弹。可惜的是，希特勒的演讲结束得太早，炸弹引爆时希特勒已经不在现场。埃尔塞在当年11月遭到了纳粹的逮捕，遭处决。影片讲述了一段惊心动魄的故事，本土演员的演出保持了原汁原味。</span>",879,1736);
$z[11][4]['name']="introduction";
$z[12]=Array("field","",1738,1779);
$z[12][4]['name']="download";
$z[13]=Array("field","",1781,1821);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V333P14Z-294E6.jpg",1823,1915);
$z[14][4]['name']="litpic";

?>