{dede:field name='keywords'}大人情歌,大人情歌电视剧{/dede:field}
{dede:field name='description'}最新电视剧《大人情歌》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《大人情歌》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友{/dede:field}
{dede:field name='title'}大人情歌{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}张佳贤{/dede:field}
{dede:field name='yanyuan'}李维维 邱凯伟 苗可丽 Keli Miao{/dede:field}
{dede:field name='pingfen'}5.3{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">2016年三立华人电视剧八点档系列第十五部作品，宝丽来国际娱乐股份有限公司制作。三立都会台暂定于2016年2月15日起晚间8点首播，东森综合台则于当日晚间9点首播，接档《恋爱邻距离》。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}港台{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914N5D2110-2GA3.jpg{/dede:field}
