<?php
$z[0]=Array("field","大人情歌,大人情歌电视剧",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《大人情歌》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《大人情歌》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","大人情歌",366,416);
$z[2][4]['name']="title";
$z[3]=Array("field","",418,457);
$z[3][4]['name']="writer";
$z[4]=Array("field","",459,498);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",500,541);
$z[5][4]['name']="time";
$z[6]=Array("field","张佳贤",543,591);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","李维维 邱凯伟 苗可丽 Keli Miao",593,672);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","5.3",674,717);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;\">2016年三立华人电视剧八点档系列第十五部作品，宝丽来国际娱乐股份有限公司制作。三立都会台暂定于2016年2月15日起晚间8点首播，东森综合台则于当日晚间9点首播，接档《恋爱邻距离》。</span>",719,1116);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1118,1159);
$z[10][4]['name']="download";
$z[11]=Array("field","国语",1161,1205);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","港台",1207,1250);
$z[12][4]['name']="area";
$z[13]=Array("field","",1252,1292);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914N5D2110-2GA3.jpg",1294,1387);
$z[14][4]['name']="litpic";

?>