{dede:field name='keywords'}进击的巨人真人版后篇.世{/dede:field}
{dede:field name='description'}最新电影《进击的巨人真人版后篇.世界终结》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《进击的巨人真人版后篇.世界终结》完整版迅雷高清下载，以及高清在线播{/dede:field}
{dede:field name='title'}进击的巨人真人版后篇.世界终结{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='pingfen'}8.5{/dede:field}
{dede:field name='daoyan'}樋口真嗣{/dede:field}
{dede:field name='yanyuan'}三浦春马 长谷川博己 水原希子 三浦贵大{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='yuyan'}日语{/dede:field}
{dede:field name='area'}其他{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">在那个弥漫着不祥气息的晴朗日子，长眠于人类内心最深处的恐惧毫无预兆地苏醒了。 一百多年前，地球各地突然出现神秘莫测的巨人。巨人和普通人类有着巨大的身形落差，他们捕食人类，贪婪无度。突如其来的天敌让弱小的人类没有任何反抗的能力，半数以上的人类变成肉泥进入捕食者的嘴里，曾经显赫的文明彻底崩溃。 幸存的人类无以为抗，只得筑起三座高大厚重的坚固墙壁——玛莉亚、露丝和希娜，以抵御巨人永无止境的食欲和进攻。在这座被隔绝有如孤岛的封闭城市内，幸存者们总算得到了长达一个多世纪的安宁岁月，他们甚至在不知不觉间忘记了百年前的灭顶之灾。 少年艾伦·叶卡（三浦春马 饰）自幼生活在城中，他早已厌烦这座巴掌大且了无生趣的城市，一直渴望到墙外的世界见识一番。直到这一天，艾伦的愿望以极其残酷血腥的方式实现了。前所未 有的超大型巨人从墙的另一面探出头来，并将号称永不可破的墙壁打出缺口。梦魇一般的巨人疯狂涌入内城，无情吞噬着尚完全搞不清状况的人类。痛苦绝望的哀嚎 响彻城中每一个角落，曾经幸福祥和的城市霎时间变成了血肉横飞的人间地狱。 百年和平土崩瓦解，人类为自己的疏忽大意付出惨烈的代价，从屠戮中活下来的人类被迫撤往内部的城池。次年，再无退路的人类统治者成立了配备立体机动装置的调查兵团，以期在修复外壁的同时，从巨人手中夺回沦陷的土地。 在上一年的噩梦中经历了惨痛悲剧的艾伦，和好友三笠·阿克曼（水原希子 饰）、阿明·阿诺德（本乡奏多 饰）共同加入了训练兵团。经过艰苦的训练，他们逐渐成长为勇猛果敢的战士。艾伦以凶险非常且伤亡率极其之高的调查兵团作为目标，发誓要手刃所有的巨人。一 日，艾伦等人受命去修复外墙，而在此征途中，他们遇到了可怕的超大型巨人。 少男少女必将在血与火的洗礼中，蜕变为无情而强大的战士……</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160322/145V3325560D0-35216.jpg{/dede:field}
