{dede:field name='keywords'}独家报道：良辰杀人记,独{/dede:field}
{dede:field name='description'}最新电影《独家报道：良辰杀人记》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《独家报道：良辰杀人记》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把{/dede:field}
{dede:field name='title'}独家报道：良辰杀人记电影迅雷高清下载,独家报道：良辰杀人记高清下载在线观看 - 日韩 - a67手机电影网{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}未知</li>
<li class="info_dq">地区：
日韩{/dede:field}
{dede:field name='yanyuan'}曹正锡 李荷娜 李美淑 金义城 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《独家报道：良辰杀人记》在线观看" title="《独家报道：良辰杀人记》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《独家报道：良辰杀人记》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">韩国投资发行公司乐天娱乐制作发行。 　　《独家报道：良辰杀人记》讲述的是社会部记者许武赫在偶然的机会下得到了关于连锁杀人事件的举报，误报的恶劣影响越来越严重，各家记者展开了炙热的取材竞争，然而却发生了真实的连锁杀人事件，竟然和之前报道描述的一模一样。导演卢德此前执导的处女作《恋爱的温度》于2013年上映时累计观影人数达186万人，并多次入围电影节奖项提名，导演卢德也备受关注。 　　曺政奭饰演的是一直顺风顺水的社会部记者许武赫，然而却身陷职场和家庭的双重危机。李荷娜饰演许武赫的妻子秀真。李美淑饰演冷酷的白局长。金义成饰演白局长的左右手文理事。裴成宇饰演调查杀人事件的刑警吴班长。金大明饰演提供线索的勇敢市民。太仁镐饰演许武赫的直属上司刘组长。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}韩语</li>
<li class="yanyuan">主演：
<a href="/search/%E6%9B%B9%E6%AD%A3%E9%94%A1" target="_blank">曹正锡</a> <a href="/search/%E6%9D%8E%E8%8D%B7%E5%A8%9C" target="_blank">李荷娜</a> <a href="/search/%E6%9D%8E%E7%BE%8E%E6%B7%91" target="_blank">李美淑</a> <a href="/search/%E9%87%91%E4%B9%89%E5%9F%8E" target="_blank">金义城</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《独家报道：良辰杀人记》在线观看" title="《独家报道：良辰杀人记》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《独家报道：良辰杀人记》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}日韩{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/14591343Z42010-19D9.jpg{/dede:field}
