{dede:field name='keywords'}最终复仇弓,最终复仇弓迅{/dede:field}
{dede:field name='description'}最新电影《最终复仇弓》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《最终复仇弓》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋{/dede:field}
{dede:field name='title'}最终复仇弓{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='daoyan'}阳子政{/dede:field}
{dede:field name='yanyuan'}栗菡 李宜坤{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">供职于省射箭队队员的纪冬,在妹妹纪雪遭遇强暴惨遭杀害后的复仇故事。独自找出租房的纪雪被暴力杀人狂向南残忍杀害,纪冬痛不欲生,为找到嫌疑人开始独立追查凶手。经过一番调查,终于将目标锁定在中介经理向南身上。向南性格极度扭曲,经常袭击夜归女子,并将她们强暴后无情杀害。一场复仇游戏由此开始</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160322/145V332L135F-1R148.jpg{/dede:field}
