{dede:field name='keywords'}东京伤情故事,东京伤情故{/dede:field}
{dede:field name='description'}最新电影《东京伤情故事》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《东京伤情故事》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您{/dede:field}
{dede:field name='title'}东京伤情故事{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='pingfen'}5.7{/dede:field}
{dede:field name='daoyan'}未知{/dede:field}
{dede:field name='yanyuan'}吉田钢太郎 高畑充希 片桐仁 高冈早纪{/dede:field}
{dede:field name='time'}2014{/dede:field}
{dede:field name='yuyan'}日语{/dede:field}
{dede:field name='area'}日韩{/dede:field}
{dede:field name='introduction'}<div>
	由在《花子与安妮》中有出色表演的吉田钢太郎初主演。在东京的言问桥有一家名为“久留米屋”的点心老店。店的继承人久留米卓三是土生土长的东京人。从小被古板的父亲严格教育，虽然在点心工艺的造诣超越了父亲，但却离过三次婚。55岁过着悠闲日子的他，兴趣是拿着幼时父亲买给他的相机，拍下日益变化的东京。在这样的生活中，他偶尔与过去仰慕过的女性相会。在美酒与佳肴前相互倾诉的二人。卓三的恋慕是否能实现...?{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160322/145V332D05160-1230B.jpg{/dede:field}
