{dede:field name='keywords'}嘻哈西游之五指山,嘻哈西{/dede:field}
{dede:field name='description'}最新电影《嘻哈西游之五指山》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《嘻哈西游之五指山》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，{/dede:field}
{dede:field name='title'}嘻哈西游之五指山电影迅雷高清下载,嘻哈西游之五指山高清下载在线观看 - 大陆 - a67手机电影网{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}李葱 </li>
<li class="info_dq">地区：
大陆{/dede:field}
{dede:field name='yanyuan'}于小鱼 杨文 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《嘻哈西游之五指山》在线观看" title="《嘻哈西游之五指山》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《嘻哈西游之五指山》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}5.5{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">新媒体电影《嘻哈西游之五指山》故事取材于《西游记》中唐僧在五指山相遇孙悟空的章节。故事以孙悟空和紫霞被挟持开始，劫匪绑架了孙悟空和紫霞，一同来到五指山客栈投宿，没想到这竟是猪八戒和老沙合伙经营的黑店！他们总想着给客人下药.......碰巧唐三藏要去西天取经，路过五指山，不巧又有一群妖怪想吃唐三藏，他们抓唐三藏抓到了五指山客栈，却不知，五指山客栈已经鱼龙混杂！一系列啼笑皆非的情节由此展开....</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语</li>
<li class="yanyuan">主演：
<a href="/search/%E4%BA%8E%E5%B0%8F%E9%B1%BC" target="_blank">于小鱼</a> <a href="/search/%E6%9D%A8%E6%96%87" target="_blank">杨文</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《嘻哈西游之五指山》在线观看" title="《嘻哈西游之五指山》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《嘻哈西游之五指山》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145913449C6020-133445.jpg{/dede:field}
