{dede:field name='keywords'}恶灵之门,恶灵之门迅雷下{/dede:field}
{dede:field name='description'}最新电影《恶灵之门》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《恶灵之门》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共{/dede:field}
{dede:field name='title'}恶灵之门电影迅雷高清下载,恶灵之门高清下载在线观看 - 大陆 - a67手机电影网{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}郭大雷 </li>
<li class="info_dq">地区：
大陆{/dede:field}
{dede:field name='yanyuan'}莫少聪 朱珠 陈廷嘉 金士杰 诸葛橙橙 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《恶灵之门》在线观看" title="《恶灵之门》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《恶灵之门》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}7.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">你有听说过恶灵之门吗？一旦开启这道门人生的厄运便会接踵而来。恐怖小说家泽田（莫少聪 饰）因创作了杀人小说名声大噪，身边的亲朋好友随后竟然完全按照他书中描述的轨迹发生了意外。妻子周丹和儿子原本守在他身边过着简单而幸福的生活，然而一个午夜，门外发生的一切改变了这个家庭的命运。 　　新搬来的性感女邻张静茹（朱珠 饰）敲开了泽田家的大门，一次次如幽灵般的进出泽田家，她的凄美、她的幽冷，像一个美丽的迷局，带给泽田致命般的吸引。泽田疯狂而又贪婪地幻想着她的身体，无法自拔，同时也打破了泽田与妻子周丹（陈廷嘉 饰）的和睦生活。周丹怀疑丈夫出轨，愈发的无助和神经，一次次的挽留丈夫泽田和请求张静茹。此时张静茹身边开始出现一些“恶灵”人物让周丹心生恐惧，他们做出一些令人发指的行径让泽田也开始忌惮。妻子周丹和儿子小天在撞破二人的苟且后，出车祸意外惨死，一时间泽田家破人亡，平静的..</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语</li>
<li class="yanyuan">主演：
<a href="/tag/3559/" target="_blank">莫少聪</a> <a href="/search/%E6%9C%B1%E7%8F%A0" target="_blank">朱珠</a> <a href="/search/%E9%99%88%E5%BB%B7%E5%98%89" target="_blank">陈廷嘉</a> <a href="/tag/1597/" target="_blank">金士杰</a> <a href="/search/%E8%AF%B8%E8%91%9B%E6%A9%99%E6%A9%99" target="_blank">诸葛橙橙</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《恶灵之门》在线观看" title="《恶灵之门》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《恶灵之门》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/14591344N42620-22R5.jpg{/dede:field}
