{dede:field name='keywords'}战神：只是爱着你,战神：{/dede:field}
{dede:field name='description'}最新电影《战神：只是爱着你》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《战神：只是爱着你》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，{/dede:field}
{dede:field name='title'}战神：只是爱着你{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pingfen'}8.7{/dede:field}
{dede:field name='daoyan'}新城毅彦{/dede:field}
{dede:field name='yanyuan'}玉木宏 宫崎葵 黑木明纱 青木崇高 小出惠介 上原美佐 大西麻惠{/dede:field}
{dede:field name='time'}2006{/dede:field}
{dede:field name='yuyan'}日语{/dede:field}
{dede:field name='area'}日韩{/dede:field}
{dede:field name='introduction'}<p>
	濑川诚人(玉木宏&nbsp;饰)是一个大学新鲜人，他不愿参加学校的开学典礼而选择了在校园附近闲逛。他在马路旁遇到了里中静流(宫崎葵&nbsp;饰)，她古怪的行径使热爱摄影的诚人忍不住按下了快门。自此静流喜欢上了诚人，可诚人只当她是朋友。随后他们成为了朋友，诚人也喜欢上了同班的富山美雪(黑木明纱&nbsp;饰)。他跟静流发现了一个环境优美的树林，因为喜欢诚人的关系，静流也喜欢上摄影。静流要和诚人一起参加摄影比赛，而她的作品就是拍下跟诚人在湖边接吻的画面。但是当天傍晚，静流却不辞而别……
</p>
<p>
	<br />
</p>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160322/145V333W12530-35113.jpg{/dede:field}
