{dede:field name='keywords'}心跳零距离/让心跳动,心跳{/dede:field}
{dede:field name='description'}最新电影《心跳零距离/让心跳动》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《心跳零距离/让心跳动》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a6{/dede:field}
{dede:field name='title'}心跳零距离/让心跳动电影迅雷高清下载,心跳零距离/让心跳动高清下载在线观看 - 其他 - a67手机电影网{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}卓娅·阿赫塔尔 </li>
<li class="info_dq">地区：
其他{/dede:field}
{dede:field name='yanyuan'}亚尼·卡普 普里扬卡·乔普拉 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《心跳零距离/让心跳动》在线观看" title="《心跳零距离/让心跳动》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《心跳零距离/让心跳动》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">Kamal Mehra（亚尼·卡普 Anil Kapoor 饰）是一位成功的商人，但他的公司却濒临破产，他与妻子Neelam（Shefali Shetty 饰）感情不和，他们的儿子Kabir（兰维尔·辛格 Ranveer Singh 饰）不愿继承家业，而是渴望当一名飞行 员，女儿Ayesha（普里扬卡·乔普拉 Priyanka Chopra 饰）拥有一家旅行社，但因被安排嫁给Manav（Rahul Bose 饰）而郁郁寡欢。为庆祝父母的30周年结婚纪念日，兄妹二人邀请亲朋好友参加为期十天的海上旅行，而旅行的过程却并不平静…</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}</li>
<li class="yanyuan">主演：
<a href="/search/%E4%BA%9A%E5%B0%BC%C2%B7%E5%8D%A1%E6%99%AE" target="_blank">亚尼·卡普</a> <a href="/search/%E6%99%AE%E9%87%8C%E6%89%AC%E5%8D%A1%C2%B7%E4%B9%94%E6%99%AE%E6%8B%89" target="_blank">普里扬卡·乔普拉</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《心跳零距离/让心跳动》在线观看" title="《心跳零距离/让心跳动》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《心跳零距离/让心跳动》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}其他{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/14591345050WF-1cS5.jpg{/dede:field}
