{dede:field name='keywords'}确认,确认迅雷下载,确认高{/dede:field}
{dede:field name='description'}最新电影《确认》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《确认》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共同享受下{/dede:field}
{dede:field name='title'}确认电影迅雷高清下载,确认高清下载在线观看 - 欧美 - a67手机电影网{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}Bob Nelson </li>
<li class="info_dq">地区：
欧美{/dede:field}
{dede:field name='yanyuan'}克里夫·欧文 玛丽亚·贝罗 帕顿·奥斯瓦尔特 斯蒂芬·托布罗斯基 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《确认》在线观看" title="《确认》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《确认》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">八岁的安东尼有点不安花周末和他的酒鬼,耗尽了木匠爸爸沃尔特,而他的妈妈邦妮和她的新丈夫凯尔一起去天主教撤退。沃尔特一样不安与安东尼,尤其是第一天一起不幸的是一系列的典型事件,包括他的卡车打破,他的房东锁定了他的房子,和窃取他的工具箱,他需要为即将到来的工作。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}英语</li>
<li class="yanyuan">主演：
<a href="/tag/881/" target="_blank">克里夫·欧文</a> <a href="/tag/6547/" target="_blank">玛丽亚·贝罗</a> <a href="/search/%E5%B8%95%E9%A1%BF%C2%B7%E5%A5%A5%E6%96%AF%E7%93%A6%E5%B0%94%E7%89%B9" target="_blank">帕顿·奥斯瓦尔特</a> <a href="/search/%E6%96%AF%E8%92%82%E8%8A%AC%C2%B7%E6%89%98%E5%B8%83%E7%BD%97%E6%96%AF%E5%9F%BA" target="_blank">斯蒂芬·托布罗斯基</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《确认》在线观看" title="《确认》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《确认》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}欧美{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
