{dede:field name='keywords'}恶灵之门,恶灵之门迅雷下{/dede:field}
{dede:field name='description'}最新电影《恶灵之门》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《恶灵之门》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共{/dede:field}
{dede:field name='title'}恶灵之门{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='pingfen'}5.5{/dede:field}
{dede:field name='daoyan'}郭大雷{/dede:field}
{dede:field name='yanyuan'}莫少聪 朱珠 陈廷嘉 金士杰 诸葛橙橙{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">你有听说过恶灵之门吗？一旦开启这道门人生的厄运便会接踵而来。恐怖小说家泽田（莫少聪 饰）因创作了杀人小说名声大噪，身边的亲朋好友随后竟然完全按照他书中描述的轨迹发生了意外。妻子周丹和儿子原本守在他身边过着简单而幸福的生活，然而一个午夜，门外发生的一切改变了这个家庭的命运。 　　新搬来的性感女邻张静茹（朱珠 饰）敲开了泽田家的大门，一次次如幽灵般的进出泽田家，她的凄美、她的幽冷，像一个美丽的迷局，带给泽田致命般的吸引。泽田疯狂而又贪婪地幻想着她的身体，无法自拔，同时也打破了泽田与妻子周丹（陈廷嘉 饰）的和睦生活。周丹怀疑丈夫出轨，愈发的无助和神经，一次次的挽留丈夫泽田和请求张静茹。此时张静茹身边开始出现一些“恶灵”人物让周丹心生恐惧，他们做出一些令人发指的行径让泽田也开始忌惮。妻子周丹和儿子小天在撞破二人的苟且后，出车祸意外惨死，一时间泽田家破人亡，平静的..</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160322/145V333UE960-22246.jpg{/dede:field}
