<?php
$z[0]=Array("field","怒拳,怒拳迅雷下载,怒拳高",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《怒拳》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《怒拳》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共同享受下",78,365);
$z[1][4]['name']="description";
$z[2]=Array("field","怒拳",367,411);
$z[2][4]['name']="title";
$z[3]=Array("field","",413,452);
$z[3][4]['name']="writer";
$z[4]=Array("field","",454,493);
$z[4][4]['name']="source";
$z[5]=Array("field","",495,535);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","10.0",537,581);
$z[6][4]['name']="pingfen";
$z[7]=Array("field","李长虹",583,631);
$z[7][4]['name']="daoyan";
$z[8]=Array("field","杜亚南 释延秀",633,692);
$z[8][4]['name']="yanyuan";
$z[9]=Array("field","2016",694,735);
$z[9][4]['name']="time";
$z[10]=Array("field","国语",737,781);
$z[10][4]['name']="yuyan";
$z[11]=Array("field","大陆",783,826);
$z[11][4]['name']="area";
$z[12]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">一个出身武术世家的何新武，从小对于武术深度迷恋，想成为武林高手，拿世界冠军是他的梦想，偏偏开设拳馆的哥哥何丰早早给何新武安排了未来，给何新武组建了家庭，娶了老婆有了孩子，这让何新武无法进行自己的梦想，何丰不想让自己的弟弟何新武走父亲的老路，当年何新武的父亲是个武术高手，最后还是倒在了拳台上，是哥哥何丰一手把新武帯大的，新武大部分都会听哥哥的，唯独学习功夫让他寸步难行.</span>",828,1543);
$z[12][4]['name']="introduction";
$z[13]=Array("field","",1545,1586);
$z[13][4]['name']="download";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V333J15F-25KY.jpg",1588,1679);
$z[14][4]['name']="litpic";

?>