<?php
$z[0]=Array("field","德云三逗士,德云三逗士迅",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《德云三逗士》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《德云三逗士》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","德云三逗士",366,419);
$z[2][4]['name']="title";
$z[3]=Array("field","",421,460);
$z[3][4]['name']="writer";
$z[4]=Array("field","",462,501);
$z[4][4]['name']="source";
$z[5]=Array("field","10.0",503,547);
$z[5][4]['name']="pingfen";
$z[6]=Array("field","张莫闲",549,597);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","郭德纲 于谦",599,655);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","2016",657,698);
$z[8][4]['name']="time";
$z[9]=Array("field","国语",700,744);
$z[9][4]['name']="yuyan";
$z[10]=Array("field","大陆",746,789);
$z[10][4]['name']="area";
$z[11]=Array("field","<span style=\"font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;\">本片以搞笑、活泼的手法讲述一群“贱男”在大都市生活的种种糗事。每集都会为“贱男“配备不同的性感都市美女，用写实手法让大家在莞尔一笑同时产生共鸣,提升“话题感”。以时下时髦的生活方式,以及族群为标本,让大家在搞笑同时,也崇尚这种自由自在的生活态度,以及对人生的“囧”刻也能轻松的心情对待</span>",791,1354);
$z[11][4]['name']="introduction";
$z[12]=Array("field","",1356,1397);
$z[12][4]['name']="download";
$z[13]=Array("field","",1399,1439);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V332615230-O228.jpg",1441,1534);
$z[14][4]['name']="litpic";

?>