<?php
$z[0]=Array("field","海女奇缘,海女奇缘迅雷下",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《海女奇缘》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《海女奇缘》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","海女奇缘",366,416);
$z[2][4]['name']="title";
$z[3]=Array("field","",418,457);
$z[3][4]['name']="writer";
$z[4]=Array("field","",459,498);
$z[4][4]['name']="source";
$z[5]=Array("field","9.5",500,543);
$z[5][4]['name']="pingfen";
$z[6]=Array("field","杨木生",545,593);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","梁向阳 吴侑霓",595,654);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","2016",656,697);
$z[8][4]['name']="time";
$z[9]=Array("field","国语",699,743);
$z[9][4]['name']="yuyan";
$z[10]=Array("field","大陆",745,788);
$z[10][4]['name']="area";
$z[11]=Array("field","<span style=\"font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;\">美丽的渔村有一个天生憨傻的村民，他叫小伍。他自幼父母双亡，与阿嬷相依为命。一转眼小伍20出头了，依然只有十岁孩子的智商。村里人虽然知道他是一个傻瓜，但都视他为难缠的要命的小冤家，哭笑不得。小伍每天都会去鱼摊抢惠姐的鱼，也经常撞翻把母鸡当宠物的龅牙少妇......总之，因为傻瓜小伍的存在，村子每天都在上演鸡飞狗跳的剧情</span>",790,1398);
$z[11][4]['name']="introduction";
$z[12]=Array("field","",1400,1441);
$z[12][4]['name']="download";
$z[13]=Array("field","",1443,1483);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V3325XC40-5Y12.jpg",1485,1577);
$z[14][4]['name']="litpic";

?>