<?php
$z[0]=Array("field","猴王与女妖,猴王与女妖迅",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《猴王与女妖》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《猴王与女妖》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","猴王与女妖",366,419);
$z[2][4]['name']="title";
$z[3]=Array("field","",421,460);
$z[3][4]['name']="writer";
$z[4]=Array("field","",462,501);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",503,544);
$z[5][4]['name']="time";
$z[6]=Array("field","张晖 </li>\r\n<li class=\"info_dq\">地区：\r\n大陆",546,636);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","张皓翔 杨莹莹",638,697);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","6.8",699,742);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">本片故事讲述的是 五百年前 孙悟空西行之前落难时被心地善良的秀娘救起，而后二人彼此心存牵挂。不久 为保声誉在父亲的强烈干预下孙悟空被赶出家门。至此 孙悟空孤独一人踏上..</span>",744,1149);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1151,1192);
$z[10][4]['name']="download";
$z[11]=Array("field","国语",1194,1238);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","大陆",1240,1283);
$z[12][4]['name']="area";
$z[13]=Array("field","",1285,1325);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914BO0KP-1bW6.jpg",1327,1418);
$z[14][4]['name']="litpic";

?>