{dede:field name='keywords'}猴王与女妖,猴王与女妖迅{/dede:field}
{dede:field name='description'}最新电影《猴王与女妖》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《猴王与女妖》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋{/dede:field}
{dede:field name='title'}猴王与女妖{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}张晖 </li>
<li class="info_dq">地区：
大陆{/dede:field}
{dede:field name='yanyuan'}张皓翔 杨莹莹{/dede:field}
{dede:field name='pingfen'}6.8{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">本片故事讲述的是 五百年前 孙悟空西行之前落难时被心地善良的秀娘救起，而后二人彼此心存牵挂。不久 为保声誉在父亲的强烈干预下孙悟空被赶出家门。至此 孙悟空孤独一人踏上..</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914BO0KP-1bW6.jpg{/dede:field}
