{dede:field name='keywords'}工作狂第六季,工作狂第六{/dede:field}
{dede:field name='description'}最新电视剧《工作狂第六季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《工作狂第六季》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和{/dede:field}
{dede:field name='title'}工作狂第六季{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}内详{/dede:field}
{dede:field name='yanyuan'}Blake Anderson Adam DeVine Anders Holm{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">Workaholics讲述了三位男子的生活故事。他们曾是大学同学，毕业后他们一起生活，一起工作。他们的工作是通过电话推销产品。 三人中，安德斯经常能想出一些出人意料的好主意，亚当最为自信，布莱克则拥有一头长长的卷发，在电影院里时，你绝对不会想坐在他的背后。他们嗜好大麻，饮 酒无数，脑筋更多的是花在想怪点子上，而非工作。离开大学校园后好日子就结束了？用不着那么悲观。三个好伙伴试图向你证明：即便在残酷的现实世界中，他们 同样可以寻欢作乐。从早上9点到下午5点，他们在一起做电视推销员；从下午5点到早上9点，他们在一起寻找「自我娱乐」的方法。他们从来就不是什么优秀员 工，迟到、带着醉意去上班……已经成了家常便饭。他们甚至经常忘记日子！</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}英语{/dede:field}
{dede:field name='area'}美剧{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914N1G3X0-5Z60.jpg{/dede:field}
