<?php
$z[0]=Array("field","工作狂第六季,工作狂第六",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《工作狂第六季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《工作狂第六季》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","工作狂第六季",366,422);
$z[2][4]['name']="title";
$z[3]=Array("field","",424,463);
$z[3][4]['name']="writer";
$z[4]=Array("field","",465,504);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",506,547);
$z[5][4]['name']="time";
$z[6]=Array("field","内详",549,594);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","Blake Anderson Adam DeVine Anders Holm",596,674);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",676,720);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;\">Workaholics讲述了三位男子的生活故事。他们曾是大学同学，毕业后他们一起生活，一起工作。他们的工作是通过电话推销产品。 三人中，安德斯经常能想出一些出人意料的好主意，亚当最为自信，布莱克则拥有一头长长的卷发，在电影院里时，你绝对不会想坐在他的背后。他们嗜好大麻，饮 酒无数，脑筋更多的是花在想怪点子上，而非工作。离开大学校园后好日子就结束了？用不着那么悲观。三个好伙伴试图向你证明：即便在残酷的现实世界中，他们 同样可以寻欢作乐。从早上9点到下午5点，他们在一起做电视推销员；从下午5点到早上9点，他们在一起寻找「自我娱乐」的方法。他们从来就不是什么优秀员 工，迟到、带着醉意去上班……已经成了家常便饭。他们甚至经常忘记日子！</span>",722,1782);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1784,1825);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",1827,1871);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","美剧",1873,1916);
$z[12][4]['name']="area";
$z[13]=Array("field","",1918,1958);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914N1G3X0-5Z60.jpg",1960,2052);
$z[14][4]['name']="litpic";

?>