{dede:field name='keywords'}澄沙之味,澄沙之味迅雷下{/dede:field}
{dede:field name='description'}最新电影《澄沙之味》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《澄沙之味》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共{/dede:field}
{dede:field name='title'}澄沙之味{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='daoyan'}河濑直美{/dede:field}
{dede:field name='yanyuan'}树木希林 永濑正敏 市原悦子 内田伽罗{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='yuyan'}日语{/dede:field}
{dede:field name='area'}其他{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">日本老牌女星树木希林与市原悦子，确定出演由导演河濑直美执导的新片《澄沙之味》，这是两位日本元老级女星的首度合作。 该片根据明川哲也的同名小说改编，全片以一家铜锣烧店为舞台，讲述了曾身患汉森病的老人德江（树木希林饰）与周围人展开的温情交流物语。首度与导演河濑合作的市原，扮演女主人公德江的好友、在疗养所咖啡馆内工作的佳子。此外，扮演铜锣烧店老板的是实力派男星永濑正敏。 都市一隅，樱花盛开的公园内，经营着名为“铜锣之春”的铜锣烧专卖店。拥有不堪回首过去的千太郎（永濑正敏 饰）因缘际会成为专卖店的雇佣店长，他和作为常客的初中生若菜（内田伽罗 饰）日复一日打发这无聊单调的时光。这一天，一位老太太不期而至。她名叫德江（树木希林 饰），因看到专卖店的招聘小广告而登门拜访。德江带来了自己熬制的豆馅儿，本想敷衍一下将老人打发走的千太郎，在尝过豆馅儿后发现意外地好吃。以此为机缘，老人成为“铜锣之春”的一员，这家小店也由此变得热闹起来。就在此时，针对于德江无情的传言悄然蔓延，小店的经营状况江河日下，千太郎被逼着做出重要的决定。不经意间，这些平凡之人的命运彻底改变……</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160322/145V333T251F-19248.jpg{/dede:field}
