<?php
$z[0]=Array("field","安娜·弗里茨的尸体,安娜",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《安娜·弗里茨的尸体》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《安娜·弗里茨的尸体》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏",76,364);
$z[1][4]['name']="description";
$z[2]=Array("field","安娜·弗里茨的尸体",366,430);
$z[2][4]['name']="title";
$z[3]=Array("field","",432,471);
$z[3][4]['name']="writer";
$z[4]=Array("field","",473,512);
$z[4][4]['name']="source";
$z[5]=Array("field","",514,554);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","7.9",556,599);
$z[6][4]['name']="pingfen";
$z[7]=Array("field","Vicens",601,646);
$z[7][4]['name']="daoyan";
$z[8]=Array("field","Alba Ribas Bernat Saumell",648,713);
$z[8][4]['name']="yanyuan";
$z[9]=Array("field","2016",715,756);
$z[9][4]['name']="time";
$z[10]=Array("field","英语",758,802);
$z[10][4]['name']="yuyan";
$z[11]=Array("field","其他",804,847);
$z[11][4]['name']="area";
$z[12]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">安娜·弗里茨,一个著名的和漂亮的女演员,最近去世。三个年轻人溜进太平间看到她裸体。着迷于她的美丽,他们决定成为过去的人与她做爱。</span>",849,1196);
$z[12][4]['name']="introduction";
$z[13]=Array("field","",1198,1239);
$z[13][4]['name']="download";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V332F3320-142540.jpg",1241,1335);
$z[14][4]['name']="litpic";

?>