{dede:field name='keywords'}我家是战国,我家是战国电{/dede:field}
{dede:field name='description'}最新电视剧《我家是战国》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《我家是战国》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的{/dede:field}
{dede:field name='title'}我家是战国{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}王伟忠{/dede:field}
{dede:field name='yanyuan'}谢祖武 殷悦 柯淑勤 杨荞安 海裕芬{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">《我家是战国》，2015年八大电视八点档。由谢祖武、Melody、柯淑勤、杨荞安、海裕芬、林若亚、郭鑫、花花、张兆志、夏语心、NueNue领衔主演。 　　本剧故事主要针对中年人面对父母年迈、夫妻空窗期、小孩青春叛逆期......等家庭社会问题。 　　曾大涵（谢祖物 饰）：张佳晴的丈夫。新事业发展业务部经理 　　张佳晴（Melody 饰）：曾大涵的妻子。百货公司保养品专柜柜姐 　　曾王美兆（柯淑勤 饰）：曾大涵、曾晓燕的母亲。退休的训导主任。 　　曾晓燕（海裕芬 饰）：曾大涵的妹妹，38岁单身市府公务员。 　　曾楚楚（杨荞安 饰）：曾大涵、张佳晴的女儿 　　白莉琪（林若亚 饰）：曾大涵的青梅竹马兼上司。 　　李正尉（郭鑫 饰）：张佳晴的表弟，从美国回台的ABC，自己经营一家小咖啡店。 　　卫娟娟（花花 饰）：宋千里的妻子，专业贵妇 　　宋千里（张兆志 饰）：卫娟娟的丈夫 　　小鲁（NueNue 饰）：万人迷柜姐，张佳晴的专柜同事。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}港台{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914N5SZ20-2RI2.jpg{/dede:field}
