<?php
$z[0]=Array("field","我的狐朋狗友,我的狐朋狗",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《我的狐朋狗友》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《我的狐朋狗友》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","我的狐朋狗友",366,422);
$z[2][4]['name']="title";
$z[3]=Array("field","",424,463);
$z[3][4]['name']="writer";
$z[4]=Array("field","",465,504);
$z[4][4]['name']="source";
$z[5]=Array("field","",506,546);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","7.8",548,591);
$z[6][4]['name']="pingfen";
$z[7]=Array("field","霍猛",593,638);
$z[7][4]['name']="daoyan";
$z[8]=Array("field","王景春 佟悦 刘冠成 戴江",640,713);
$z[8][4]['name']="yanyuan";
$z[9]=Array("field","2016",715,756);
$z[9][4]['name']="time";
$z[10]=Array("field","国语",758,802);
$z[10][4]['name']="yuyan";
$z[11]=Array("field","大陆",804,847);
$z[11][4]['name']="area";
$z[12]=Array("field","<span style=\"font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;\">一个风流成性的男青年唐明军勾引了黑道大哥昆山的女友，大哥借机前来 讹诈 。危难之际，他只好找来最好的三个兄弟一起解决困难，但四个怂蛋无法和大哥抗衡，只好去向昆山当年最好的兄弟求援，在逃亡过程中，四个浑浑噩噩的兄弟遇到了一位美女，并在曾经的初恋、冷漠的孩子和强势的老婆之间周旋，惹上了各种新的麻烦。</span>",849,1436);
$z[12][4]['name']="introduction";
$z[13]=Array("field","",1438,1479);
$z[13][4]['name']="download";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V333NJJ0-2QB5.jpg",1481,1572);
$z[14][4]['name']="litpic";

?>