<?php
$z[0]=Array("field","昨日的果实,昨日的果实迅",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《昨日的果实》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《昨日的果实》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","昨日的果实",366,419);
$z[2][4]['name']="title";
$z[3]=Array("field","",421,460);
$z[3][4]['name']="writer";
$z[4]=Array("field","",462,501);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",503,544);
$z[5][4]['name']="time";
$z[6]=Array("field","古桑 </li>\r\n<li class=\"info_dq\">地区：\r\n欧美",546,636);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","赛米·汉拉缇 詹森·刘易斯 瑞秋·卡帕尼",638,731);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",733,777);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">继第一部亲兄妹结为夫妇后，2个儿子长大成 人后的事，少年时期他们已了解自己的身世，大儿子很正常，小儿子心理扭曲，夫妇俩收养了一个小女儿。第三部讲小儿子少年时碰见外婆心理逐渐变态的故事。</span>",779,1213);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1215,1256);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",1258,1302);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","欧美",1304,1347);
$z[12][4]['name']="area";
$z[13]=Array("field","",1349,1389);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914B953c10-11A8.jpg",1391,1484);
$z[14][4]['name']="litpic";

?>