{dede:field name='keywords'}怒拳,怒拳迅雷下载,怒拳高{/dede:field}
{dede:field name='description'}最新电影《怒拳》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《怒拳》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共同享受下{/dede:field}
{dede:field name='title'}怒拳{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}李长虹 </li>
<li class="info_dq">地区：
大陆{/dede:field}
{dede:field name='yanyuan'}杜亚南 释延秀{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">一个出身武术世家的何新武，从小对于武术深度迷恋，想成为武林高手，拿世界冠军是他的梦想，偏偏开设拳馆的哥哥何丰早早给何新武安排了未来，给何新武组建了家庭，娶了老婆有了孩子，这让何新武无法进行自己的梦想，何丰不想让自己的弟弟何新武走父亲的老路，当年何新武的父亲是个武术高手，最后还是倒在了拳台上，是哥哥何丰一手把新武帯大的，新武大部分都会听哥哥的，唯独学习功夫让他寸步难行.</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914C221620-1V524.jpg{/dede:field}
