{dede:field name='keywords'}全境封锁：特工起源,全境{/dede:field}
{dede:field name='description'}最新电影《全境封锁：特工起源》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《全境封锁：特工起源》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收{/dede:field}
{dede:field name='title'}全境封锁：特工起源{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}德文·格雷厄姆 </li>
<li class="info_dq">地区：
欧美{/dede:field}
{dede:field name='yanyuan'}Matt Lynch Sasha Andreev Amanda Day{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">育碧为《全境封锁》拍摄一部真人系列短片《特工起源》介绍游戏的世界观。 《全境封锁：特工起源》共分为四个部分，由四个不同的团队制作。讲述了四名休眠特工在纽约遭受病毒危机后苏醒并聚在一起最终解救一起人质危机。四部短片主题各不相同但又有联系，在最后一部里汇聚。特效非常棒，枪战，动作，爆炸，追击一个都不少。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}英语{/dede:field}
{dede:field name='area'}欧美{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914B92W10-2a041.jpg{/dede:field}
