{dede:field name='keywords'}实习医生第二季,实习医生{/dede:field}
{dede:field name='description'}最新电视剧《实习医生第二季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《实习医生第二季》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让{/dede:field}
{dede:field name='title'}实习医生第二季{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2015{/dede:field}
{dede:field name='daoyan'}内详{/dede:field}
{dede:field name='yanyuan'}内详{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;white-space:normal;color:#555555;line-height:21px;background-color:#ffffff;">故事的主角是四个年轻的实习医生。他们经常会干一些傻事，而他们的“领导”贝科夫医生很“乐意”监督他们，给他们出一些难题，最终他们的关系会如何？会发生怎样<a href="" target="_target">搞笑</a>的故事呢？</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}英语{/dede:field}
{dede:field name='area'}美剧{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914N463T50-21c56.jpg{/dede:field}
