<?php
$z[0]=Array("field","屌丝女士第四季,屌丝女士",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《屌丝女士第四季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《屌丝女士第四季》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","屌丝女士第四季",366,425);
$z[2][4]['name']="title";
$z[3]=Array("field","",427,466);
$z[3][4]['name']="writer";
$z[4]=Array("field","",468,507);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",509,550);
$z[5][4]['name']="time";
$z[6]=Array("field","内详 </li>\r\n<li class=\"info_dq\">地区：\r\n欧美",552,642);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","玛蒂娜·希尔",644,701);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",703,747);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">德国搞笑微电《屌丝女士 KnallerFrauen》是德国SAT.1电视台每个星期五晚上11点15分播放的一部喜剧小品。由曾六次获得德国喜剧奖的女演员玛蒂娜·希尔（Martina Hill）扮演“炸弹妞，有时是母亲，有时是单身女性，有时是女朋友，有时是行人或是OL，角色都是现实生活中的各种女性，只不过她们对待人和对事的反应与表现都非常特别。她们为了达到目而采用的荒诞手段，常常令人捧腹大笑。 无厘头是本剧的看点，动作表演及其神经质。6位剧中配角，两个是男性分别扮演女主老公和女主的男朋友。两个是女性扮演好朋友及同事。还有两个常任女主的父母的老人，本剧较重口味，未成年人不建议观看，但是并无露点等不和谐内容出现剧中。</span>",749,1756);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1758,1799);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",1801,1845);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","欧美",1847,1890);
$z[12][4]['name']="area";
$z[13]=Array("field","",1892,1932);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914BP32N0-203b2.jpg",1934,2027);
$z[14][4]['name']="litpic";

?>