{dede:field name='keywords'}最后一个道士的往事,最后{/dede:field}
{dede:field name='description'}最新电影《最后一个道士的往事》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《最后一个道士的往事》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收{/dede:field}
{dede:field name='title'}最后一个道士的往事电影迅雷高清下载,最后一个道士的往事高清下载在线观看 - 大陆 - a67手机电影网{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}林育塘 </li>
<li class="info_dq">地区：
大陆{/dede:field}
{dede:field name='yanyuan'}廉捷 高天景 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《最后一个道士的往事》在线观看" title="《最后一个道士的往事》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《最后一个道士的往事》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}6.7{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">住在城里的夏家闹鬼，于是寻找有本事捉鬼降妖的人，陈言谷（马宗彬 饰）闻讯带着两徒弟进城捉鬼。帮夏家驱除恶鬼之后，陈言谷得到100万。而师傅从此出去花天酒地。不顾两个徒弟刘梦阳（廉捷 饰）、顾博（高天景 饰）。而顾博则想办法偷到了师傅钱箱的钥匙，骗师弟一起去城里。路上顾博耍心机带钱跑了，留下了刘梦阳一人。刘梦阳走投无路到了足疗店工作，不巧又碰到师兄，却发现师兄不学正道跑入偏门，为了解救师兄，刘梦阳展开了一系列的行动……</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语</li>
<li class="yanyuan">主演：
<a href="/search/%E5%BB%89%E6%8D%B7" target="_blank">廉捷</a> <a href="/search/%E9%AB%98%E5%A4%A9%E6%99%AF" target="_blank">高天景</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《最后一个道士的往事》在线观看" title="《最后一个道士的往事》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《最后一个道士的往事》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/1459134414T250-1LO5.jpg{/dede:field}
