{dede:field name='keywords'}我是和尚,我是和尚迅雷下{/dede:field}
{dede:field name='description'}最新电影《我是和尚》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《我是和尚》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共{/dede:field}
{dede:field name='title'}我是和尚电影迅雷高清下载,我是和尚高清下载在线观看 - 日韩 - a67手机电影网{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}真壁幸紀 </li>
<li class="info_dq">地区：
日韩{/dede:field}
{dede:field name='yanyuan'}伊藤淳史 山本美月 溝端淳平 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《我是和尚》在线观看" title="《我是和尚》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《我是和尚》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">该片根据日本爱媛县今治市荣福寺的方丈白川密成的真人真事改编，主人公白川光丹是个24岁的书店店员，由于方丈祖父的去世，光丹辞掉工作进入到了从未接触过的“和尚世界”。山本饰演女主角京子。女主角京子与主人公光丹、好友真治人是从小一起长大的好朋友，在光丹与真治眼中，京子是位大美女。本片主演伊藤淳史曾以一部日剧《电车男》被亚洲观众熟知。此次《我是和尚》剧组最终选择福州作为影片世界首映的地点，足以证明主创人员对本届丝绸之路国际电影节的重视。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}日语</li>
<li class="yanyuan">主演：
<a href="/tag/1077/" target="_blank">伊藤淳史</a> <a href="/search/%E5%B1%B1%E6%9C%AC%E7%BE%8E%E6%9C%88" target="_blank">山本美月</a> <a href="/search/%E6%BA%9D%E7%AB%AF%E6%B7%B3%E5%B9%B3" target="_blank">溝端淳平</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《我是和尚》在线观看" title="《我是和尚》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《我是和尚》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}日韩{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/14591344ZIE0-c301.jpg{/dede:field}
