<?php
$z[0]=Array("field","房主/房屋神灵,房主/房屋",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《房主/房屋神灵》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《房主/房屋神灵》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和",76,365);
$z[1][4]['name']="description";
$z[2]=Array("field","房主/房屋神灵",367,424);
$z[2][4]['name']="title";
$z[3]=Array("field","",426,465);
$z[3][4]['name']="writer";
$z[4]=Array("field","",467,506);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",508,549);
$z[5][4]['name']="time";
$z[6]=Array("field","内详",551,596);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","杰西达邦·福尔迪 Por Thrisadee Sahawong 施莉达",598,694);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",696,740);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;\">《房主》这个剧有鬼元素，也可以说叫神。这个神住在一幢老房子里，也不总是个好人，他活着的时候对妻子做了坏事，于是死了之后就去不了别处。他总是在他的老房子里萦绕不去，最后帮助了一个穷困的单身妈妈和她的孩子。</span>",742,1192);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1194,1235);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",1237,1281);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","其他",1283,1326);
$z[12][4]['name']="area";
$z[13]=Array("field","",1328,1368);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914N50494F-231431.jpg",1370,1465);
$z[14][4]['name']="litpic";

?>