<?php
$z[0]=Array("field","维京传奇第四季,维京传奇",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《维京传奇第四季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《维京传奇第四季》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","维京传奇第四季",366,425);
$z[2][4]['name']="title";
$z[3]=Array("field","",427,466);
$z[3][4]['name']="writer";
$z[4]=Array("field","",468,507);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",509,550);
$z[5][4]['name']="time";
$z[6]=Array("field","克莱恩·唐纳利 乔韩·瑞克",552,626);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","崔维斯·费米尔 古斯塔·斯卡斯加德 凯瑟琳·温妮克",628,736);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","9.5",738,781);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","",783,828);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",830,871);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",873,917);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","美剧",919,962);
$z[12][4]['name']="area";
$z[13]=Array("field","",964,1004);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914N304L60-131303.jpg",1006,1101);
$z[14][4]['name']="litpic";

?>