{dede:field name='keywords'}通学途中,通学途中迅雷下{/dede:field}
{dede:field name='description'}最新电影《通学途中》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《通学途中》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共{/dede:field}
{dede:field name='title'}通学途中{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}川野浩司 </li>
<li class="info_dq">地区：
日韩{/dede:field}
{dede:field name='yanyuan'}中川大志 森川葵 藤本泉 赤楚衛二 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《通学途中》在线观看" title="《通学途中》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《通学途中》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}8.0{/dede:field}
{dede:field name='introduction'}腼腆的女孩由纪（森川葵 饰）渴望体会一下心似小鹿乱撞的感觉，可是命中注定的白马王子迟迟未曾出现。同在美术部的弘（中川大志 饰）始终暖暖注视着由纪，他为了这位“好朋友”的恋情给出了自己的建议。而对由纪来说，谁才能让她领悟到“真正的恋情”呢？ 本片根据访问量超过770万人次、累计发行量超过135万部的网络小说“通学系列”改编，上部《通学电车》定于2015年11月7日上映{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}日语</li>
<li class="yanyuan">主演：
<a href="/search/%E4%B8%AD%E5%B7%9D%E5%A4%A7%E5%BF%97" target="_blank">中川大志</a> <a href="/search/%E6%A3%AE%E5%B7%9D%E8%91%B5" target="_blank">森川葵</a> <a href="/search/%E8%97%A4%E6%9C%AC%E6%B3%89" target="_blank">藤本泉</a> <a href="/search/%E8%B5%A4%E6%A5%9A%E8%A1%9B%E4%BA%8C" target="_blank">赤楚衛二</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《通学途中》在线观看" title="《通学途中》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《通学途中》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}日韩{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145913Q3B6320-212E2.jpg{/dede:field}
