<?php
$z[0]=Array("global","",12,37);
$z[0][4]['name']="autoindex";
$z[1]=Array("litpic","",92,107);
$z[2]=Array("title","",124,138);
$z[3]=Array("yuyan","",156,170);
$z[4]=Array("arcurl","",193,208);
$z[5]=Array("title","",226,240);
$z[6]=Array("global","",265,293);
$z[6][4]['name']="cfg_plus_dir";
$z[7]=Array("global","",401,434);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("pingfen","",466,482);

?>