{dede:field name='keywords'}抱紧他,抱紧他迅雷下载{/dede:field}
{dede:field name='description'}最新电影《抱紧他》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《抱紧他》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共同享{/dede:field}
{dede:field name='title'}抱紧他{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}尼尔·尼尔阿姆菲尔德 </li>
<li class="info_dq">地区：
欧美{/dede:field}
{dede:field name='yanyuan'}盖·皮尔斯 杰弗里·拉什{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:Simsun;font-size:medium;line-height:normal;white-space:normal;">帅气的高中男校足球队队长约翰，与戏剧社中跑龙套的小演员提姆，两人携手面对过许多外界的歧视、批评，也曾在诱惑与忌妒间摆荡，相识相恋15年至今，原本以为他们的爱情已是圆满，直到爱无法解决的问题逐渐浮现，考验着他们之间的关系。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}英语{/dede:field}
{dede:field name='area'}欧美{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914BZ1330-2J600.jpg{/dede:field}
