<?php
$z[0]=Array("field","抱紧他,抱紧他迅雷下载",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《抱紧他》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《抱紧他》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共同享",74,361);
$z[1][4]['name']="description";
$z[2]=Array("field","抱紧他",363,410);
$z[2][4]['name']="title";
$z[3]=Array("field","",412,451);
$z[3][4]['name']="writer";
$z[4]=Array("field","",453,492);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",494,535);
$z[5][4]['name']="time";
$z[6]=Array("field","尼尔·尼尔阿姆菲尔德 </li>\r\n<li class=\"info_dq\">地区：\r\n欧美",537,650);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","盖·皮尔斯 杰弗里·拉什",652,724);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",726,770);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:Simsun;font-size:medium;line-height:normal;white-space:normal;\">帅气的高中男校足球队队长约翰，与戏剧社中跑龙套的小演员提姆，两人携手面对过许多外界的歧视、批评，也曾在诱惑与忌妒间摆荡，相识相恋15年至今，原本以为他们的爱情已是圆满，直到爱无法解决的问题逐渐浮现，考验着他们之间的关系。</span>",772,1239);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1241,1282);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",1284,1328);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","欧美",1330,1373);
$z[12][4]['name']="area";
$z[13]=Array("field","",1375,1415);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914BZ1330-2J600.jpg",1417,1510);
$z[14][4]['name']="litpic";

?>