<?php
$z[0]=Array("field","密谍伙伴第二季,密谍伙伴",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《密谍伙伴第二季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《密谍伙伴第二季》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","密谍伙伴第二季",366,425);
$z[2][4]['name']="title";
$z[3]=Array("field","",427,466);
$z[3][4]['name']="writer";
$z[4]=Array("field","",468,507);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",509,550);
$z[5][4]['name']="time";
$z[6]=Array("field","Grant Harvey",552,603);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","伊夫林·布洛初 杰克·拉斯基 沃伦·布朗 卡伦·普莱西",605,716);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",718,762);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;\">根据真人真事改编的《密谍伙伴》描述五个加拿大、美国和英国年轻人在二战期间前往安大略湖一个绝密训练基地接受间谍技能训练（包括破坏、暗杀、爆破、勒索、摩斯密码、地图学和招募年轻人投身抵抗运动的口才），他们随后被派到德军占领地区执行重要任务。联邦调查局和战略情报局（Office of Strategic Services）负责训练和监管这个团队。</span>",764,1368);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1370,1411);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",1413,1457);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","美剧",1459,1502);
$z[12][4]['name']="area";
$z[13]=Array("field","",1504,1544);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914N4UT60-222b1.jpg",1546,1639);
$z[14][4]['name']="litpic";

?>