<?php
$z[0]=Array("field","洛杉矶捣蛋计划,洛杉矶捣",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《洛杉矶捣蛋计划》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《洛杉矶捣蛋计划》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","洛杉矶捣蛋计划",366,425);
$z[2][4]['name']="title";
$z[3]=Array("field","",427,466);
$z[3][4]['name']="writer";
$z[4]=Array("field","",468,507);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",509,550);
$z[5][4]['name']="time";
$z[6]=Array("field","郑潇 </li>\r\n<li class=\"info_dq\">地区：\r\n大陆",552,642);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","夏雨 宋祖儿 杨紫 吴大维",644,717);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","4.3",719,762);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">落魄经纪人黄伯伦（夏雨 饰）来到美国洛杉矶寻找一位失踪艺人（杨紫 饰）不幸滞留在美国，却意外地成为了五名不同肤色的美国萌娃的爸爸。黄伯伦一边要继续寻找失踪艺人，一边还要照顾5个青春期的孩子。在经历一系列波折之后，这个不负责任的“临时奶爸”却逐渐成长为一个真正的好爸爸，得到了他人生的二次成长。</span>",764,1358);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1360,1401);
$z[10][4]['name']="download";
$z[11]=Array("field","国语",1403,1447);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","大陆",1449,1492);
$z[12][4]['name']="area";
$z[13]=Array("field","",1494,1534);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914C3Q2520-295R6.jpg",1536,1630);
$z[14][4]['name']="litpic";

?>