{dede:field name='keywords'}格林第五季,格林第五季电{/dede:field}
{dede:field name='description'}最新电视剧《格林第五季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《格林第五季》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的{/dede:field}
{dede:field name='title'}格林第五季{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2015{/dede:field}
{dede:field name='daoyan'}NorbertoBarba{/dede:field}
{dede:field name='yanyuan'}大卫·君图力 罗素·霍恩斯比 比茜·图诺克 塞拉斯·威尔·米切尔 萨沙·罗伊茨{/dede:field}
{dede:field name='pingfen'}0.0{/dede:field}
{dede:field name='introduction'}<div>
	顾名思义，《格林》根据著名的《格林童话》改编，但两者完全不是一回事。{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}英语{/dede:field}
{dede:field name='area'}美剧{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914N53D1Z-259606.jpg{/dede:field}
