<?php
$z[0]=Array("field","格林第五季,格林第五季电",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《格林第五季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《格林第五季》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","格林第五季",366,419);
$z[2][4]['name']="title";
$z[3]=Array("field","",421,460);
$z[3][4]['name']="writer";
$z[4]=Array("field","",462,501);
$z[4][4]['name']="source";
$z[5]=Array("field","2015",503,544);
$z[5][4]['name']="time";
$z[6]=Array("field","NorbertoBarba",546,598);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","大卫·君图力 罗素·霍恩斯比 比茜·图诺克 塞拉斯·威尔·米切尔 萨沙·罗伊茨",600,743);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","0.0",745,788);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<div>\r\n	顾名思义，《格林》根据著名的《格林童话》改编，但两者完全不是一回事。",790,945);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",947,988);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",990,1034);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","美剧",1036,1079);
$z[12][4]['name']="area";
$z[13]=Array("field","",1081,1121);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914N53D1Z-259606.jpg",1123,1217);
$z[14][4]['name']="litpic";

?>