<?php
$z[0]=Array("field","征服2016,征服2016迅雷下载",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《征服2016》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《征服2016》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共同享",76,365);
$z[1][4]['name']="description";
$z[2]=Array("field","征服2016",367,415);
$z[2][4]['name']="title";
$z[3]=Array("field","",417,456);
$z[3][4]['name']="writer";
$z[4]=Array("field","",458,497);
$z[4][4]['name']="source";
$z[5]=Array("field","",499,539);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","10.0",541,585);
$z[6][4]['name']="pingfen";
$z[7]=Array("field","王小凯",587,635);
$z[7][4]['name']="daoyan";
$z[8]=Array("field","王凯 唐涛",637,690);
$z[8][4]['name']="yanyuan";
$z[9]=Array("field","2016",692,733);
$z[9][4]['name']="time";
$z[10]=Array("field","国语",735,779);
$z[10][4]['name']="yuyan";
$z[11]=Array("field","大陆",781,824);
$z[11][4]['name']="area";
$z[12]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">权利、利益、女人、金钱交织而成却又充斥着的整个氛围——黑帮。《征服2016》是一部男人情节浓厚的影片，本片主要描写的就是黑帮因利益而发生冲突后，黑帮内外的状...</span>",826,1217);
$z[12][4]['name']="introduction";
$z[13]=Array("field","",1219,1260);
$z[13][4]['name']="download";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V33421AV0-2515A.jpg",1262,1355);
$z[14][4]['name']="litpic";

?>