<?php
$z[0]=Array("field","分手再说我爱你,分手再说",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《分手再说我爱你》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《分手再说我爱你》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","分手再说我爱你",366,425);
$z[2][4]['name']="title";
$z[3]=Array("field","",427,466);
$z[3][4]['name']="writer";
$z[4]=Array("field","",468,507);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",509,550);
$z[5][4]['name']="time";
$z[6]=Array("field","叶念琛 </li>\r\n<li class=\"info_dq\">地区：\r\n大陆",552,645);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","方力申 邓丽欣 李丽珍 邵仲衡 张继聪",647,736);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","9.1",738,781);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;\">林嘉华（方力申 饰）和邝美宝（邓丽欣 饰）结婚十周年，决定到瑞士滑雪庆祝，但在出发前，华重遇几年前的老友琪琪（盛朗熙 饰），二人发觉对对方的情愫从未减退。那边，阿宝竟突然提出不去瑞士，而她对阿华原来也有一个不可告人的秘密。</span>",783,1257);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1259,1300);
$z[10][4]['name']="download";
$z[11]=Array("field","国语",1302,1346);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","大陆",1348,1391);
$z[12][4]['name']="area";
$z[13]=Array("field","",1393,1433);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914C2XL60-234002.jpg",1435,1529);
$z[14][4]['name']="litpic";

?>