{dede:field name='keywords'}闪魂电影,闪魂电影迅雷下{/dede:field}
{dede:field name='description'}最新电影《闪魂电影》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《闪魂电影》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共{/dede:field}
{dede:field name='title'}闪魂电影{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2014{/dede:field}
{dede:field name='daoyan'}戴维 </li>
<li class="info_dq">地区：
大陆{/dede:field}
{dede:field name='yanyuan'}斯力更 陈圆 戴维 李伟 常海波 许起鳯 姜耀 王震南 王健 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《闪魂电影》在线观看" title="《闪魂电影》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《闪魂电影》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}6.5{/dede:field}
{dede:field name='introduction'}{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语</li>
<li class="yanyuan">主演：
<a href="/search/%E6%96%AF%E5%8A%9B%E6%9B%B4" target="_blank">斯力更</a> <a href="/search/%E9%99%88%E5%9C%86" target="_blank">陈圆</a> <a href="/search/%E6%88%B4%E7%BB%B4" target="_blank">戴维</a> <a href="/search/%E6%9D%8E%E4%BC%9F" target="_blank">李伟</a> <a href="/search/%E5%B8%B8%E6%B5%B7%E6%B3%A2" target="_blank">常海波</a> <a href="/search/%E8%AE%B8%E8%B5%B7%E9%B3%AF" target="_blank">许起鳯</a> <a href="/search/%E5%A7%9C%E8%80%80" target="_blank">姜耀</a> <a href="/search/%E7%8E%8B%E9%9C%87%E5%8D%97" target="_blank">王震南</a> <a href="/search/%E7%8E%8B%E5%81%A5" target="_blank">王健</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《闪魂电影》在线观看" title="《闪魂电影》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《闪魂电影》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}大陆{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145913Q55E920-49B6.jpg{/dede:field}
