{dede:field name='keywords'}黑胶时代第一季,黑胶时代{/dede:field}
{dede:field name='description'}最新电视剧《黑胶时代第一季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《黑胶时代第一季》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让{/dede:field}
{dede:field name='title'}黑胶时代第一季{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}马丁·斯科塞斯 彼得·苏列特{/dede:field}
{dede:field name='yanyuan'}保罗·本-维克托 P·J·伯恩 马克斯·凯塞拉 詹姆斯·贾格尔{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">这出背景设定在1970年代纽约的HBO全新戏剧影集， 由大导演马丁史柯西斯、滚石乐团主唱米克杰格及知名编剧兼制作人特伦斯温特连手打造。本片透过巴比康纳维尔所饰演的唱片公司总裁里奇范斯特拉之眼，在他努力不毁灭任何人的情况下，拯救公司和自身灵魂的过程中，看尽充斥着性与毒品的音乐产业的百态。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}英语{/dede:field}
{dede:field name='area'}美剧{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914N4110920-1YV5.jpg{/dede:field}
