<?php
$z[0]=Array("field","黑胶时代第一季,黑胶时代",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《黑胶时代第一季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《黑胶时代第一季》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","黑胶时代第一季",366,425);
$z[2][4]['name']="title";
$z[3]=Array("field","",427,466);
$z[3][4]['name']="writer";
$z[4]=Array("field","",468,507);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",509,550);
$z[5][4]['name']="time";
$z[6]=Array("field","马丁·斯科塞斯 彼得·苏列特",552,629);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","保罗·本-维克托 P·J·伯恩 马克斯·凯塞拉 詹姆斯·贾格尔",631,747);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","10.0",749,793);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;\">这出背景设定在1970年代纽约的HBO全新戏剧影集， 由大导演马丁史柯西斯、滚石乐团主唱米克杰格及知名编剧兼制作人特伦斯温特连手打造。本片透过巴比康纳维尔所饰演的唱片公司总裁里奇范斯特拉之眼，在他努力不毁灭任何人的情况下，拯救公司和自身灵魂的过程中，看尽充斥着性与毒品的音乐产业的百态。</span>",795,1355);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1357,1398);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",1400,1444);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","美剧",1446,1489);
$z[12][4]['name']="area";
$z[13]=Array("field","",1491,1531);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914N4110920-1YV5.jpg",1533,1627);
$z[14][4]['name']="litpic";

?>