<?php
$z[0]=Array("field","少男奶爸第五季,少男奶爸",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《少男奶爸第五季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《少男奶爸第五季》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","少男奶爸第五季",366,425);
$z[2][4]['name']="title";
$z[3]=Array("field","",427,466);
$z[3][4]['name']="writer";
$z[4]=Array("field","",468,507);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",509,550);
$z[5][4]['name']="time";
$z[6]=Array("field","内详",552,597);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","让-卢克·比洛多 塔吉·莫里 切尔西·斯特伯 梅莉莎·彼得曼 德雷克·迪勒",599,735);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","8.7",737,780);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;\">ABC Family续订《少男奶爸 Baby Daddy》第五季，早前该台取消了《御姐奶爸 Melissa &amp; Joey》。</span>",782,1047);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1049,1090);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",1092,1136);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","美剧",1138,1181);
$z[12][4]['name']="area";
$z[13]=Array("field","",1183,1223);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914N335JP-15P39.jpg",1225,1318);
$z[14][4]['name']="litpic";

?>