<?php
$z[0]=Array("field","天上的约定,天上的约定电",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《天上的约定》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《天上的约定》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","天上的约定",366,419);
$z[2][4]['name']="title";
$z[3]=Array("field","",421,460);
$z[3][4]['name']="writer";
$z[4]=Array("field","",462,501);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",503,544);
$z[5][4]['name']="time";
$z[6]=Array("field","全宇盛",546,594);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","李宥利 徐俊英 朴河娜 宋钟浩 李钟源 金惠莉 尹朱尚 吴英实 尹福仁",596,725);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","7.5",727,770);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;\">该剧讲述为了给死去的姐姐报仇，进行伪装和仇人弟弟结婚的一个勇敢女人的凄惨故事。</span>",772,1036);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1038,1079);
$z[10][4]['name']="download";
$z[11]=Array("field","韩语",1081,1125);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","韩剧",1127,1170);
$z[12][4]['name']="area";
$z[13]=Array("field","",1172,1212);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914N2D2640-11M25.jpg",1214,1308);
$z[14][4]['name']="litpic";

?>