{dede:field name='keywords'}天上的约定,天上的约定电{/dede:field}
{dede:field name='description'}最新电视剧《天上的约定》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《天上的约定》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的{/dede:field}
{dede:field name='title'}天上的约定{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}全宇盛{/dede:field}
{dede:field name='yanyuan'}李宥利 徐俊英 朴河娜 宋钟浩 李钟源 金惠莉 尹朱尚 吴英实 尹福仁{/dede:field}
{dede:field name='pingfen'}7.5{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">该剧讲述为了给死去的姐姐报仇，进行伪装和仇人弟弟结婚的一个勇敢女人的凄惨故事。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}韩语{/dede:field}
{dede:field name='area'}韩剧{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914N2D2640-11M25.jpg{/dede:field}
