<?php
$z[0]=Array("field","致命怪谈,致命怪谈迅雷下",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《致命怪谈》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《致命怪谈》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","致命怪谈",366,416);
$z[2][4]['name']="title";
$z[3]=Array("field","",418,457);
$z[3][4]['name']="writer";
$z[4]=Array("field","",459,498);
$z[4][4]['name']="source";
$z[5]=Array("field","10.0",500,544);
$z[5][4]['name']="pingfen";
$z[6]=Array("field","依平",546,591);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","刘青 周浩东 苏婷 杨海超 魏建云",593,676);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","2016",678,719);
$z[8][4]['name']="time";
$z[9]=Array("field","国语",721,765);
$z[9][4]['name']="yuyan";
$z[10]=Array("field","大陆",767,810);
$z[10][4]['name']="area";
$z[11]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">妙龄少女天天（刘青 饰）因为童年阴影患上了严重的广场恐惧症，一直把自己锁闭在家中。一天一觉醒来她突然发现自己被关在血腥的禁闭囚室中，耳边传来阵阵磨刀声和惨烈的嘶叫声，隔壁的囚禁者一个个的被面具杀人魔残虐而死，天天即将成为下一个目标……</span>",812,1323);
$z[11][4]['name']="introduction";
$z[12]=Array("field","",1325,1366);
$z[12][4]['name']="download";
$z[13]=Array("field","",1368,1408);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V333Zc3Z-63613.jpg",1410,1502);
$z[14][4]['name']="litpic";

?>