{dede:field name='keywords'}太阳的后裔,太阳的后裔电{/dede:field}
{dede:field name='description'}最新电视剧《太阳的后裔》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《太阳的后裔》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的{/dede:field}
{dede:field name='title'}太阳的后裔{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}未知{/dede:field}
{dede:field name='yanyuan'}李应福{/dede:field}
{dede:field name='pingfen'}8.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">该剧主要讲述了特战部队海外派兵组组长刘时镇和外科医生姜暮烟，在韩国和派兵地区之间往返相爱的故事。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}韩语{/dede:field}
{dede:field name='area'}韩剧{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914N2543030-1022X.jpg{/dede:field}
