{dede:field name='keywords'}我是和尚,我是和尚迅雷下{/dede:field}
{dede:field name='description'}最新电影《我是和尚》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《我是和尚》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共{/dede:field}
{dede:field name='title'}我是和尚{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='daoyan'}真壁幸紀{/dede:field}
{dede:field name='yanyuan'}伊藤淳史 山本美月 溝端淳平{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='yuyan'}日语{/dede:field}
{dede:field name='area'}日韩{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">该片根据日本爱媛县今治市荣福寺的方丈白川密成的真人真事改编，主人公白川光丹是个24岁的书店店员，由于方丈祖父的去世，光丹辞掉工作进入到了从未接触过的“和尚世界”。山本饰演女主角京子。女主角京子与主人公光丹、好友真治人是从小一起长大的好朋友，在光丹与真治眼中，京子是位大美女。本片主演伊藤淳史曾以一部日剧《电车男》被亚洲观众熟知。此次《我是和尚》剧组最终选择福州作为影片世界首映的地点，足以证明主创人员对本届丝绸之路国际电影节的重视。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160322/145V33394I330-cK6.jpg{/dede:field}
