<?php
$z[0]=Array("field","我是和尚,我是和尚迅雷下",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《我是和尚》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《我是和尚》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","我是和尚",366,416);
$z[2][4]['name']="title";
$z[3]=Array("field","",418,457);
$z[3][4]['name']="writer";
$z[4]=Array("field","",459,498);
$z[4][4]['name']="source";
$z[5]=Array("field","10.0",500,544);
$z[5][4]['name']="pingfen";
$z[6]=Array("field","真壁幸紀",546,597);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","伊藤淳史 山本美月 溝端淳平",599,677);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","2016",679,720);
$z[8][4]['name']="time";
$z[9]=Array("field","日语",722,766);
$z[9][4]['name']="yuyan";
$z[10]=Array("field","日韩",768,811);
$z[10][4]['name']="area";
$z[11]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">该片根据日本爱媛县今治市荣福寺的方丈白川密成的真人真事改编，主人公白川光丹是个24岁的书店店员，由于方丈祖父的去世，光丹辞掉工作进入到了从未接触过的“和尚世界”。山本饰演女主角京子。女主角京子与主人公光丹、好友真治人是从小一起长大的好朋友，在光丹与真治眼中，京子是位大美女。本片主演伊藤淳史曾以一部日剧《电车男》被亚洲观众熟知。此次《我是和尚》剧组最终选择福州作为影片世界首映的地点，足以证明主创人员对本届丝绸之路国际电影节的重视。</span>",813,1619);
$z[11][4]['name']="introduction";
$z[12]=Array("field","",1621,1662);
$z[12][4]['name']="download";
$z[13]=Array("field","",1664,1704);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V33394I330-cK6.jpg",1706,1798);
$z[14][4]['name']="litpic";

?>