<?php
$z[0]=Array("field","蝼蛄,蝼蛄迅雷下载,蝼蛄高",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《蝼蛄》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《蝼蛄》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友共同享受下",78,365);
$z[1][4]['name']="description";
$z[2]=Array("field","蝼蛄",367,411);
$z[2][4]['name']="title";
$z[3]=Array("field","",413,452);
$z[3][4]['name']="writer";
$z[4]=Array("field","",454,493);
$z[4][4]['name']="source";
$z[5]=Array("field","2016",495,536);
$z[5][4]['name']="time";
$z[6]=Array("field","木村ひさし </li>\r\n<li class=\"info_dq\">地区：\r\n大陆",538,637);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","北村一辉 滨田岳 山下莉绪 牧田哲也 佐野和真",639,740);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","7.5",742,785);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;\">一张接着黑社会桑原角色一輝北村建设顾问成员二宫角色更多岳扮演。剧情,拥有500万名信徒宗教法人的宝物——幅长卷总长的丑闻的味道,别人桑原和成员二宫,大阪、京都、名古屋、东京为舞台,讲述了腐败的警察和黑社会的美人画廊经营者的“恶人”,大的东西。《破門(瘟神罢了)》一样,剧本,导演酒井雅秋木扑了过来。</span>",787,1357);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1359,1400);
$z[10][4]['name']="download";
$z[11]=Array("field","日语",1402,1446);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","大陆",1448,1491);
$z[12][4]['name']="area";
$z[13]=Array("field","",1493,1533);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914C010P10-52R0.jpg",1535,1628);
$z[14][4]['name']="litpic";

?>