{dede:field name='keywords'}神战：权力之眼/埃及神战{/dede:field}
{dede:field name='description'}最新电影《神战：权力之眼/埃及神战》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《神战：权力之眼/埃及神战》完整版迅雷高清下载，以及高清在线播放，轻轻一点{/dede:field}
{dede:field name='title'}神战：权力之眼/埃及神战电影迅雷高清下载,神战：权力之眼/埃及神战高清下载在线观看 - 欧美 - a67手机电影网{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}亚历克斯·普罗亚斯 </li>
<li class="info_dq">地区：
欧美{/dede:field}
{dede:field name='yanyuan'}尼古拉·科斯特-瓦尔道 杰拉德·巴特勒 布伦顿·思韦茨 </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《神战：权力之眼/埃及神战》在线观看" title="《神战：权力之眼/埃及神战》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《神战：权力之眼/埃及神战》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;">故事发生在矗立着宫殿和金字塔的婉转萦回的尼罗河畔。 当时的古埃及充满了魔法、怪兽和神灵。无情的黑暗之神赛特,夺取了原本属于天神荷鲁斯的埃及王权,并让曾经繁荣和平的国家陷入冲突与混乱。人类的存亡与世界的安定岌岌可危。 一位年轻的窃贼贝克被神所眷顾,为拯救世界和自己的真爱踏上了一场惊险的奇幻旅程。为了成功,他必须寻求并得到强大的荷鲁斯神的帮助,与其组成一个看似不太可能的“英雄” 联盟。随着人类生命的危在旦夕,两个英雄站了出来,开启了对抗邪恶的不归路...... 作为荷鲁斯与贝克强有力的敌人,赛特指派心腹为他们的对抗制造重重艰难险阻。如果荷鲁斯神与凡人贝克希望在这场对抗中最终获胜,他们就必须通过一系列对勇气和牺牲的考验。</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}英语</li>
<li class="yanyuan">主演：
<a href="/search/%E5%B0%BC%E5%8F%A4%E6%8B%89%C2%B7%E7%A7%91%E6%96%AF%E7%89%B9-%E7%93%A6%E5%B0%94%E9%81%93" target="_blank">尼古拉·科斯特-瓦尔道</a> <a href="/tag/3103/" target="_blank">杰拉德·巴特勒</a> <a href="/search/%E5%B8%83%E4%BC%A6%E9%A1%BF%C2%B7%E6%80%9D%E9%9F%A6%E8%8C%A8" target="_blank">布伦顿·思韦茨</a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《神战：权力之眼/埃及神战》在线观看" title="《神战：权力之眼/埃及神战》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《神战：权力之眼/埃及神战》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}欧美{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145913450D45P-20X25.jpg{/dede:field}
