<?php
$z[0]=Array("field","海军罪案调查处:洛杉矶第",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《海军罪案调查处:洛杉矶第七季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《海军罪案调查处:洛杉矶第七季》电视剧全集迅雷高清下载，以及高清在线播放",77,366);
$z[1][4]['name']="description";
$z[2]=Array("field","海军罪案调查处:洛杉矶第七季",368,446);
$z[2][4]['name']="title";
$z[3]=Array("field","",448,487);
$z[3][4]['name']="writer";
$z[4]=Array("field","",489,528);
$z[4][4]['name']="source";
$z[5]=Array("field","2015",530,571);
$z[5][4]['name']="time";
$z[6]=Array("field","ChrisO'Donnel",573,625);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","克里斯·奥唐纳 丹妮拉·鲁阿 艾瑞克·克里斯蒂安·奥森 琳达·亨特",627,755);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","5.0",757,800);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<div>\r\n	加入该小组的成员都是训练有素的精英特工，他们运用尖端科技手段和各种各样的假身份秘密开展工作。他们潜藏得很深，有时连家人也不知道他们的真实身份。为了完成任务，他们不顾个人安危，每天都游走于生与死的边缘。",802,1155);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1157,1198);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",1200,1244);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","美剧",1246,1289);
$z[12][4]['name']="area";
$z[13]=Array("field","",1291,1331);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914N4501340-209529.jpg",1333,1429);
$z[14][4]['name']="litpic";

?>