{dede:field name='keywords'}甘味人生,甘味人生电视剧{/dede:field}
{dede:field name='description'}最新电视剧《甘味人生》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《甘味人生》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友{/dede:field}
{dede:field name='title'}甘味人生{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2015{/dede:field}
{dede:field name='daoyan'}龚美富 郭建宏 冯凯{/dede:field}
{dede:field name='yanyuan'}王识贤 黄少祺 亮哲 李燕 曾婉婷{/dede:field}
{dede:field name='pingfen'}6.3{/dede:field}
{dede:field name='introduction'}<div>
	《甘味人生》 ，播出前原定名为《打拼出头天》，是三立<a href="" target="_target">励志</a>温馨为题材的八点档连续剧。本剧2015年05月18日开镜，全剧采用HD拍摄，目前也正在紧锣密鼓的拍摄中，接档于《世间情》之后，每周一至周五晚间八点播出。由映画传播事业股份有限公司和升华娱乐传播有限公司制作。本剧由日立变频冷气冠名赞助，名称为《日立变频冷气 甘味人生》。{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}港台{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914N15V0P-4bA.jpg{/dede:field}
