<?php
$z[0]=Array("field","甘味人生,甘味人生电视剧",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《甘味人生》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《甘味人生》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","甘味人生",366,416);
$z[2][4]['name']="title";
$z[3]=Array("field","",418,457);
$z[3][4]['name']="writer";
$z[4]=Array("field","",459,498);
$z[4][4]['name']="source";
$z[5]=Array("field","2015",500,541);
$z[5][4]['name']="time";
$z[6]=Array("field","龚美富 郭建宏 冯凯",543,608);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","王识贤 黄少祺 亮哲 李燕 曾婉婷",610,693);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","6.3",695,738);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<div>\r\n	《甘味人生》 ，播出前原定名为《打拼出头天》，是三立<a href=\"\" target=\"_target\">励志</a>温馨为题材的八点档连续剧。本剧2015年05月18日开镜，全剧采用HD拍摄，目前也正在紧锣密鼓的拍摄中，接档于《世间情》之后，每周一至周五晚间八点播出。由映画传播事业股份有限公司和升华娱乐传播有限公司制作。本剧由日立变频冷气冠名赞助，名称为《日立变频冷气 甘味人生》。",740,1287);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",1289,1330);
$z[10][4]['name']="download";
$z[11]=Array("field","国语",1332,1376);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","港台",1378,1421);
$z[12][4]['name']="area";
$z[13]=Array("field","",1423,1463);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914N15V0P-4bA.jpg",1465,1556);
$z[14][4]['name']="litpic";

?>