{dede:field name='keywords'}地狱之门：耶路撒冷,地狱{/dede:field}
{dede:field name='description'}最新电影《地狱之门：耶路撒冷》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《地狱之门：耶路撒冷》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收{/dede:field}
{dede:field name='title'}地狱之门：耶路撒冷{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}Doron Paz   Yoav Paz  </li>
<li class="info_dq">地区：
其他{/dede:field}
{dede:field name='yanyuan'}耶尔·格洛格拉斯 Yael Grobglas  </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         

                         

                         

                         

                         <span class="bds_more">更多</span>

                         

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<img alt="《地狱之门：耶路撒冷》在线观看" title="《地狱之门：耶路撒冷》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/>
<span>《地狱之门：耶路撒冷》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='pingfen'}8.5{/dede:field}
{dede:field name='introduction'}{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}英语</li>
<li class="yanyuan">主演：
<a href="/search/%E8%80%B6%E5%B0%94%C2%B7%E6%A0%BC%E6%B4%9B%E6%A0%BC%E6%8B%89%E6%96%AF" target="_blank">耶尔·格洛格拉斯</a> <a href="/search/Yael" target="_blank">Yael</a> <a href="/search/Grobglas" target="_blank">Grobglas</a> <a href="/tag/1005/" target="_blank"></a> </li>
</ul>
<div class="gg_img"><script>c275_1()</script></div>
</div>
<div class="content250"><script>c250_1()</script></div>
</div>
<div class="menu_button">
<div class="menu_fx">
<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">

                         <a class="bds_qzone"></a>

                         <a class="bds_tsina"></a>

                         <a class="bds_tqq"></a>

                         <a class="bds_renren"></a>

                         <span class="bds_more">更多</span>

                         <a class="shareCount"></a>

</div>

<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=783439" ></script>

<script type="text/javascript" id="bdshell_js"></script>

<script type="text/javascript">

document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();

</script>

<!-- Baidu Button END -->

</div>

        <div class="con_gg"><script>c468_1()</script></div>

</div>

<div class="banner728">
<script>c728_1()</script>
</div>

<div class="downtb">

<div class="downurls">

  
<ul id="type_1_361381" name="_mp4_hdmp4">
<li>
<a  href="#" target="_blank" id="tuiguang"><img alt="《地狱之门：耶路撒冷》在线观看" title="《地狱之门：耶路撒冷》在线观看" src="/style/image/play_pic_m.gif"  border="0" style="cursor:pointer"/></a>
<span>《地狱之门：耶路撒冷》看视频和影音高清，点击播放！</span>{/dede:field}
{dede:field name='area'}其他{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145913Q519250-162D.jpg{/dede:field}
