<?php
$z[0]=Array("field","下一站歌后第四季,下一站",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电视剧《下一站歌后第四季》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《下一站歌后第四季》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏",77,364);
$z[1][4]['name']="description";
$z[2]=Array("field","下一站歌后第四季",366,428);
$z[2][4]['name']="title";
$z[3]=Array("field","",430,469);
$z[3][4]['name']="writer";
$z[4]=Array("field","",471,510);
$z[4][4]['name']="source";
$z[5]=Array("field","2015",512,553);
$z[5][4]['name']="time";
$z[6]=Array("field","未知",555,600);
$z[6][4]['name']="daoyan";
$z[7]=Array("field","康妮·布里登 海顿·潘妮蒂尔 查尔斯·伊斯滕 克里斯·卡马克 山姆·帕莱迪奥",602,743);
$z[7][4]['name']="yanyuan";
$z[8]=Array("field","0.0",745,788);
$z[8][4]['name']="pingfen";
$z[9]=Array("field","<span style=\"color:#111111;font-family:Helvetica, Arial, sans-serif;line-height:19px;\"> ABC正式宣布续订《音乐之乡》第四季。</span>",790,981);
$z[9][4]['name']="introduction";
$z[10]=Array("field","",983,1024);
$z[10][4]['name']="download";
$z[11]=Array("field","英语",1026,1070);
$z[11][4]['name']="yuyan";
$z[12]=Array("field","美剧",1072,1115);
$z[12][4]['name']="area";
$z[13]=Array("field","",1117,1157);
$z[13][4]['name']="pubdate";
$z[14]=Array("field","/dedecms/uploads/allimg/c160328/145914N522JP-241413.jpg",1159,1253);
$z[14][4]['name']="litpic";

?>