{dede:field name='keywords'}1989一念间,1989一念间电视{/dede:field}
{dede:field name='description'}最新电视剧《1989一念间》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供《1989一念间》电视剧全集迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和您的朋友{/dede:field}
{dede:field name='title'}1989一念间{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='time'}2016{/dede:field}
{dede:field name='daoyan'}未知{/dede:field}
{dede:field name='yanyuan'}张立昂 邵雨薇 蔡黄汝{/dede:field}
{dede:field name='pingfen'}10.0{/dede:field}
{dede:field name='introduction'}<span style="font-family:宋体;line-height:16px;white-space:normal;background-color:#FFFFFF;">《1989一念间》（英语：Back To 1989），2016年三立华人电视剧周五档系列的第九部作品，本剧张立昂、邵雨薇、蔡黄汝领衔主演。本剧将在三立都会台、Astro双星、Astro双星HD于1月8日晚上10点首播，东森综合台于1月9日晚上8点30分播出。接档《料理高校生》。本剧为三立华人电视剧首部时代剧！ 　　念间的当下，你选择爱或不爱？ 陈澈（张立昂饰）是位金融股市的金童，没想到一场意外，摔出了一趟回到过去的时空之旅，他穿越回到出生的前一年，也就是1989年，遇到当时才22岁的“妈妈”（豆花妹饰），也就是在那个时候，他的“妈妈”还没生下他。而穿越回到1989年的陈澈甚至还与“妈妈”的闺密叶真真（邵雨薇饰）发展出一段恋情……当2016年的他，遇上1989年的她，爱上一个“不能爱”的人，陈澈在这一念间的当下，究竟要选择爱或不爱？</span>{/dede:field}
{dede:field name='download'}{/dede:field}
{dede:field name='yuyan'}国语{/dede:field}
{dede:field name='area'}港台{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/dedecms/uploads/allimg/c160328/145914N113Q50-1AX.jpg{/dede:field}
