<?php
$z[0]=Array("field","EU超时任务粤语,EU超时任务",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最新电影《EU超时任务粤语》全集迅雷下载在线观看，a67手机电影网免费为广大用户提供电影《EU超时任务粤语》完整版迅雷高清下载，以及高清在线播放，轻轻一点，把a67收藏，让您和",78,366);
$z[1][4]['name']="description";
$z[2]=Array("field","EU超时任务粤语",368,426);
$z[2][4]['name']="title";
$z[3]=Array("field","",428,467);
$z[3][4]['name']="writer";
$z[4]=Array("field","",469,508);
$z[4][4]['name']="source";
$z[5]=Array("field","",510,550);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","10.0",552,596);
$z[6][4]['name']="pingfen";
$z[7]=Array("field","林志华",598,646);
$z[7][4]['name']="daoyan";
$z[8]=Array("field","王浩信 朱千雪 袁伟豪 单立文",648,727);
$z[8][4]['name']="yanyuan";
$z[9]=Array("field","2016",729,770);
$z[9][4]['name']="time";
$z[10]=Array("field","粤语",772,816);
$z[10][4]['name']="yuyan";
$z[11]=Array("field","港台",818,861);
$z[11][4]['name']="area";
$z[12]=Array("field","<span style=\"font-family:宋体;font-size:12px;line-height:16px;white-space:normal;background-color:#FFFFFF;\">《EU超时任务》是香港电视广播有限公司拍摄制作的警匪时装剧，由朱千雪、袁伟豪、王浩信领衔主演。</span>",863,1162);
$z[12][4]['name']="introduction";
$z[13]=Array("field","",1164,1205);
$z[13][4]['name']="download";
$z[14]=Array("field","/dedecms/uploads/allimg/c160322/145V33413311P-203103.jpg",1207,1302);
$z[14][4]['name']="litpic";

?>